### ISSUE TITLE
[notebook] Unable to shutdown/restart dead kernel

### ISSUE THREAD

**Issue by burnpanck** [ipython/ipython#8742] opened 2015-08-19 08:41 UTC
I had a dead kernel that could not be restart or shut-down by any means available from the web-interface (i.e. neither in the open notebook, nor from the manager). From within the notebook I would get a message along the lines of 'try manual restart'. The notebook app gave the following traceback to the log output and the mozilla developer console:
```
Traceback (most recent call last):
  File "/usr/local/bin/ipython3", line 9, in <module>
    load_entry_point('ipython==3.1.0', 'console_scripts', 'ipython3')()
  File "/usr/local/lib/python3.4/dist-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/usr/local/lib/python3.4/dist-packages/IPython/terminal/ipapp.py", line 367, in start
    return self.subapp.start()
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/notebookapp.py", line 1103, in start
    self.cleanup_kernels()
  File "/usr/local/lib/python3.4/dist-packages/IPython/html/notebookapp.py", line 1021, in cleanup_kernels
    self.kernel_manager.shutdown_all()
  File "/usr/local/lib/python3.4/dist-packages/IPython/kernel/multikernelmanager.py", line 160, in shutdown_all
    self.request_shutdown(kid)
  File "/usr/local/lib/python3.4/dist-packages/IPython/kernel/multikernelmanager.py", line 33, in wrapped
    r = method(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/kernel/manager.py", line 252, in request_shutdown
    self.session.send(self._control_socket, msg)
  File "/usr/local/lib/python3.4/dist-packages/IPython/kernel/zmq/session.py", line 664, in send
    stream.send_multipart(to_send, copy=copy)
AttributeError: 'NoneType' object has no attribute 'send_multipart'
```
From the mozilla developer console I could further find something that looks like a kernel ID/hash. When attempting to manually kill the corresponding process, I found none with that ID running. From these information, I suspect the kernel was already dead but the notebook app did not take proper notice of this and got into an invalid internal state. The only remedy to re-start that kernel was to kill the whole notebook app, taking down any remaining open kernels.

I have no idea what brought me there. I was having the same notebook open in two browser windows, because I used a PyThreeJS widget to display a scene that I was updating from the notebook using the other browser window. The display-only window then repeatedly warned me about the notebook being overwritten, leading to multiple overlapping warning windows if I did not dismiss them immediately (should I file this as a separate non-critical bug?). Could any of this be related to the behaviour I was encountering?

**Comment by Carreau** [comment] 2015-08-19 08:47
Hi, I would try to update to 3.2 at least, see if this can be reproduce. 

We just release 4.0 a week ago also, it's up to you. 

Usually yes you can open 1 ticket per bug, as otherwise we will forget on of the reported bugs. 
WE are aware of the multiple overlapping windows IIRC, and are working on fixes.

**Comment by burnpanck** [comment] 2015-08-19 09:17
Actually I don't care too much for those overlapping windows, it was more meant as a side-note; if you are aware of them, then all is fine.
The other bug, unfortunately, I don't know how to reproduce the bug even with 3.1. Or: Fortunately, that bug seems to be very rare. Could be a race condition with me clicking "restart" to often and at a bad moment. Possibly hard to fix and thus maybe not worth to follow if it doesn't appear more often.
I was actually rather thinking that maybe one would want an additional safety net for such cases: Implementing a manual way to tell the notebook app that a kernel is gone, such that I can start a new one.

With respect to 4.0: I wasn't aware of the release. Since IPython is making such tremendous progress lately, I'm generally trying to keep up with new versions. I'll definitely try it out!

**Comment by Carreau** [comment] 2015-08-19 09:22
If the kernel dies, we should be aware after a few seconds because the heartbeats stops. 
If a session is still present, even with dead kernel, it should be cleaned automatically on first attempt to use it. 

We'll keep a eye on that. 

As for 4.0 it's the first release where IPython is in multiple package, so you might want to read last post of  that : blog.jupyter.org

Also at least update to 3.2 that have security updates.

**Comment by takluyver** [comment] 2016-01-26 14:42
Closing as it's not clear how to reproduce the issue. If someone does find a way, please open a new issue on the jupyter/notebook repo.

**Closed by takluyver** 2016-01-26 14:42 UTC
