### ISSUE TITLE
In-process embedded qtconsole requires pressing Shift-Enter to execute commands

### ISSUE THREAD

**Issue by kupiakos** [ipython/ipython#8731] opened 2015-08-14 05:31 UTC
Using [this code](https://gist.github.com/kupiakos/4d049a7fc493ca2a1c09) on IPython 4.0.0, it seems that an embedded IPython qtconsole is functional, with one strange exception. In order to execute commands, Shift-Enter must be pressed instead of Enter. When enter is pressed, there is a short (and irritating) delay before the console asks for the next line of Python code. Very similar code ran as expected in IPython 3.

Digging further into the code, it looks like the `RichJupyterWidget` can't detect when valid code has been entered, timing out in its detection.

Here is the digging I've done so far:

1. [`ConsoleWidget._event_filter_console_keypress`](https://github.com/jupyter/qtconsole/blob/33d92cb73ed39f556da2fccc58035ec734c997d9/qtconsole/console_widget.py#L1166) calls `ConsoleWidget.execute` with `interactive = not shift_down`. So, if shift isn't pressed (as normal), interactivity is enabled.

2. [`ConsoleWidget.execute`](https://github.com/jupyter/qtconsole/blob/33d92cb73ed39f556da2fccc58035ec734c997d9/qtconsole/console_widget.py#L602) checks if we've enabled execute-on-enter and if interactivity is enabled (shift is not pressed). If so, it executes `FrontendWidget._is_complete`.

3. [`FrontendWidget._is_complete`](https://github.com/jupyter/qtconsole/blob/33d92cb73ed39f556da2fccc58035ec734c997d9/qtconsole/frontend_widget.py#L244) executes [`KernelClient.is_complete`](https://github.com/jupyter/jupyter_client/blob/522774cdf37d313bf61c195cbcef5f54eef831bf/jupyter_client/client.py#L375), which appears to send an `is_complete_request` to its session.

4. [`FrontendWidget._is_complete`](https://github.com/jupyter/qtconsole/blob/33d92cb73ed39f556da2fccc58035ec734c997d9/qtconsole/frontend_widget.py#L247) executes `ZMQSocketChannel.get_msg` with a `timeout` of (by default) `.25`, which seems to be where the delay on enter presses comes from.

5. [`ZMQSocketChannel.get_msg`](https://github.com/jupyter/jupyter_client/blob/522774cdf37d313bf61c195cbcef5f54eef831bf/jupyter_client/blocking/channels.py#L50) polls the socket with a timeout of `250` milliseconds to timeout. With my sample code, the socket will always timeout and set `ready` to `0` after the short delay.

6. [`ZMQSocketChannel.get_msg`](https://github.com/jupyter/jupyter_client/blob/522774cdf37d313bf61c195cbcef5f54eef831bf/jupyter_client/blocking/channels.py#L57) will raise an `Empty` exception as it couldn't read from the socket within the timeout.

7. [`FrontendWidget._is_complete`](https://github.com/jupyter/qtconsole/blob/33d92cb73ed39f556da2fccc58035ec734c997d9/qtconsole/frontend_widget.py#L250) catches the `Empty` exception and returns `(False, u'')` to indicate that the code was not complete (even if it was), prompting the line to be continued by the `RichJupyterWidget`.

So in the end, it appears the problem comes from something involving the communication between the kernel, the widget, and/or the socket channel, but I'm not incredibly familiar with IPython/Jupyter to know well enough what the problem might be, or whether it's a legitimate bug in IPython. All I know is that very similar code to this would work on IPython 3.0, and now it won't work in IPython 4.0. The problem occurs with Python 2 and 3, Windows and Linux. PySide is being used.

**Comment by minrk** [comment] 2015-08-14 17:00
duplicate of jupyter/qtconsole#32, will be closed by jupyter/qtconsole#33

**Closed by minrk** 2015-08-14 17:00 UTC
