### ISSUE TITLE
Tab completion within the console crashes the kernel

### ISSUE THREAD

**Issue by hobson** [ipython/ipython#12766] opened 2021-01-10 23:05 UTC
## versions
```
Python Version   : 3.8.5
Operating System : Linux-5.4.0-60-generic-x86_64-with-glibc2.10   # Also happens on Mac OSX with similar Anaconda environment 
Python Path      : /home/hobs/anaconda3/envs/rasaenv/bin/python
```

```console
$ pip list | egrep -i 'jupyter|python|torn' 
dnspython               1.16.0
ipython                 7.19.0
ipython-genutils        0.2.0
jupyter                 1.0.0
jupyter-client          6.1.7
jupyter-console         6.2.0
jupyter-core            4.7.0
jupyterlab-pygments     0.1.2
jupyterlab-widgets      1.0.0
kafka-python            2.0.2
python-crfsuite         0.9.7
python-dateutil         2.8.1
python-engineio         3.13.2
python-socketio         4.6.1
tornado                 6.1
```

## Repro

Launch `ipython` or `jupyter console` from a Linux terminal (bash shell).
```python
>>> import os
>>> os.path.ex #<TAB> to attempt tab auto-complete
```

## Error (Traceback):

```console
In [1]: import os
In [2]: os.path.expand('$HOME')
Traceback (most recent call last):
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 129, in _get_completions
    for c in completions:
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hobs/anaconda3/envs/rasaenv/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 564, in mainloop
    self.interact()
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 547, in interact
    code = self.prompt_for_code()
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 473, in prompt_for_code
    text = self.pt_app.prompt(
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 816, in run
    return loop.run_until_complete(
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 783, in run_async
    return await _run_async2()
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 771, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 872, in cancel_and_wait_for_background_tasks
    await task
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1854, in new_coroutine
    await coroutine(*a, **kw)
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1683, in async_completer
    async for completion in self.completer.get_completions_async(
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 269, in get_completions_async
    async for completion in completer.get_completions_async(
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/home/hobs/anaconda3/envs/rasaenv/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    exc_type, exc_value, exc_tb = sys.exc_info()
NameError: name 'sys' is not defined

If you suspect this is an IPython 7.19.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by hobson** [comment] 2021-01-10 23:08
@seyoumha this is my repro of the crash that you were experiencing on Mac OSX

**Comment by grlee77** [comment] 2021-01-11 06:18
Thanks reporting @hobson (I came here due to the same issue), but this appears to be a duplicate of #12740.

**Closed** 2021-01-12 10:20 UTC
