### ISSUE TITLE
dropdown widget prevents shift-enter from working

### ISSUE THREAD

**Issue by PBrockmann** [ipython/ipython#7555] opened 2015-01-23 21:06 UTC
Just to relay this issue that has been described in Julia Language project
https://github.com/JuliaLang/Interact.jl/issues/31

Let me know if this issue has been taken into account and if there is a workaround.

**Comment by takluyver** [comment] 2015-01-23 21:13
Thanks, I think I ran into this the other day, but I couldn't immediately reproduce it.

**Comment by PBrockmann** [comment] 2015-01-23 21:21
The problem appears only with dropdown once it has been used (open and choose one).

**Comment by minrk** [comment] 2015-01-23 23:21
If the widget elements have focus, keyboard events are disabled.

**Comment by PBrockmann** [comment] 2015-01-23 23:36
Not sure to understand. 
What I do is just after having choosen 'B' in the  dropdown is to execute the next cell. But then it is not possible anymore with shift-enter. If I do this I pass to the line.
Can you reproduce this behaviour (only on firefox for me).

**Comment by takluyver** [comment] 2015-01-23 23:57
I can reproduce this in Firefox (haven't tried elsewhere). For instance, execute this cell from the 'Widget List' example notebook:

```python
from IPython.html import widgets
w = widgets.Dropdown(
    values={'One': 1, 'Two': 2, 'Three': 3},
    value=2,
    description='Number:',
)
display(w)
```

Now open the dropdown and select a value. Now it's possible to click on other cells, and visually be in command or edit mode on another cell, even typing into another cell, and the IPython keyboard shortcuts are still disabled. Clicking save in the toolbar brings the shortcuts back, presumably because they're restored when focus returns from the toolbar.

**Comment by minrk** [comment] 2015-01-23 23:59
Just tested in Chrome and Firefox, and this appears to be yet another FF-specific bug.

**Comment by takluyver** [comment] 2015-01-24 00:03
It's not as though there are no webkit specific bugs, and there are probably quite a few more that we don't even notice are webkit specific.

**Comment by minrk** [comment] 2015-01-24 00:10
With some excellent console.log debugging, the issue is that after blurring the dropdown element, an anchor tag *inside* the element is focused, and no blur event is fired on that element, even though it does lose focus.

We probably need a workaround, but this seems pretty clearly to be a bug in Firefox.

**Comment by minrk** [comment] 2015-01-24 01:14
I opened #7565 to allow mitigating the issue, and any other similar bug, by clicking on an input area. I'm not sure how to actually work around Firefox's bug here, and I expect any workaround would likely cause new problems. I think #7565 is probably good enough that this shouldn't block 3.0. I'll ping @jdfreder for any brilliant ideas for workarounds for Firefox missing events, just in case.

**Comment by takluyver** [comment] 2015-01-26 22:53
#7565 was merged, mitigating this. Since we don't know of a way to fix it properly, milestoning this as wishlist.

**Comment by jdfreder** [comment] 2015-01-27 00:05
This is ouchy.  Reminds me of the bug where CodeMirror was firing focus before blur (two elements focused at once).  Sorry @minrk , no magic fixes from me WRT this yet.  Pinging @ellisonbg since he has spent a lot of time debugging browser focus & blur events too.

**Comment by ellisonbg** [comment] 2015-01-27 00:08
I am crying ;-(

On Mon, Jan 26, 2015 at 4:06 PM, Jonathan Frederic <notifications@github.com
> wrote:

> This is ouchy. Reminds me of the bug where CodeMirror was firing focus
> before blur (two elements focused at once). Sorry @minrk
> <https://github.com/minrk> , no magic fixes from me WRT this yet. Pinging
> @ellisonbg <https://github.com/ellisonbg> since he has spent a lot of
> time debugging browser focus & blur events too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7555#issuecomment-71565300>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment] 2015-01-27 01:07
After an hour or two debugging this, I was ready to burn down the building. I think we should put together a minimal test case to send upstream to Firefox and call it a day. #7565 at least makes it possible for users to recover from this and any future bug getting stuck in command mode.

**Comment by ellisonbg** [comment] 2015-01-27 01:18
Thank you Min, now I am not crying, but rather laughing.

On Mon, Jan 26, 2015 at 5:07 PM, Min RK <notifications@github.com> wrote:

> After an hour or two debugging this, I was ready to burn down the
> building. I think we should put together a minimal test case to send
> upstream to Firefox and call it a day. #7565
> <https://github.com/ipython/ipython/pull/7565> at least makes it possible
> for users to recover from this and any future bug getting stuck in command
> mode.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7555#issuecomment-71572023>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Closed** 2024-10-27 18:05 UTC
Labels: notebook, widgets
