### ISSUE TITLE
No ipython-script.py after installing on Windows?

### ISSUE THREAD

**Issue by ziyuang** [ipython/ipython#7690] opened 2015-02-05 02:36 UTC
OS: Windows 8.1
Python: 3.4.2

I don't see the `ipython-script.py` under the `Scripts` folder as before. In this case, how should I create a shortcut for `ipython qtconsole` without launching the additional console window? I used `pythonw.exe ipython-script.py qtconsole` for this purpose.

**Comment by takluyver** [comment] 2015-02-05 17:55
What do you see under scripts? There should be some variant of 'ipython' there that you can launch with `pythonw`.

**Comment by ziyuang** [comment] 2015-02-05 20:26
C:\Python34\Scripts>dir ipy*
  
     Directory of C:\Python34\Scripts
    
    2015/02/05  04:23            95,074 ipython.exe
    2015/02/05  04:23            32,580 ipython.ico
    2015/02/05  04:23            95,074 ipython3.exe
    2015/02/05  04:23            44,204 ipython_nb.ico
    2015/02/05  04:23             5,151 ipython_win_post_install.py
                   5 File(s)        272,083 bytes
                   0 Dir(s)  420,783,964,160 bytes free

**Comment by takluyver** [comment] 2015-02-05 21:29
That's bizarre. Can you try uninstalling IPython and installing it again? How did you install it? I think every installation method should put Python scripts in there.

**Comment by ziyuang** [comment] 2015-02-05 21:45
I uninstalled and tried both installing from the [whl](http://www.lfd.uci.edu/~gohlke/pythonlibs/#ipython) file and from PyPI with `pip`. In either case there is no `ipython-script.py` in the `Scripts` folder. The only difference is that there will be a `ipython_win_post_install.py` if installing from .whl file. But this script fails to run directly because it complains `get_special_folder_path` is not defined.

**Comment by takluyver** [comment] 2015-02-05 22:21
OK, I have reproduced this on Windows. This seems to be the way pip behaves with wheels now. You can work around it by:

- Bypassing wheels with the `--no-use-wheel` flag. This will do a slower installation from source, which still creates the `-script.py` files.
- Start it using `pythonw -m IPython.qt.console` ... as soon as PR #7695 gets merged, because I just noticed that this is broken.

I don't think there's anything better we can do about this.

**Comment by ziyuang** [comment] 2015-02-05 22:26
OK, works, thank you.

**Closed** 2015-02-05 22:28 UTC
