### ISSUE TITLE
intermittent kernel connection issues (OSX Yosemite)

### ISSUE THREAD

**Issue by jonathon-love** [ipython/ipython#7334] opened 2014-12-27 15:51 UTC
hi, i'm having some issues using the IPython 3.0 (master) notebook under OS X Yosemite.

sometimes when i open a notebook, the commands generate no output (they don't appear to make it to a kernel). other times when i open a notebook, they do all work.

this is a screenshot of when they don't work:

![screen shot 2014-12-27 at 4 38 25 pm](https://cloud.githubusercontent.com/assets/3240247/5561677/a82a5888-8de7-11e4-9739-cc4d1955aa85.png)

but then if i close it down, then restart it, sometimes it will work:

![screen shot 2014-12-27 at 4 37 36 pm](https://cloud.githubusercontent.com/assets/3240247/5561678/bbcd3036-8de7-11e4-8fe8-0ffdcae6e4ef.png)

when it doesn't work, some 404's appear in the console:

    [D 16:38:05.180 NotebookApp] Initializing websocket connection /api/kernels/4e61f027-395e-41a4-80a4-062a4fc7172b/iopub
    [W 16:38:05.181 NotebookApp] 404 GET /api/kernels/4e61f027-395e-41a4-80a4-062a4fc7172b/iopub?session_id=8593BEC6CC454DE194ED165B82293BFA (::1): Kernel does not exist: 4e61f027-395e-41a4-80a4-062a4fc7172b
    [D 16:38:05.182 NotebookApp] Using contents: services/contents
    [W 16:38:05.188 NotebookApp] 404 GET /api/kernels/4e61f027-395e-41a4-80a4-062a4fc7172b/iopub?session_id=8593BEC6CC454DE194ED165B82293BFA (::1) 8.75ms referer=None
    [D 16:38:06.662 NotebookApp] 200 GET /api/sessions?_=1419694640361 (::1) 0.62ms
    [D 16:38:06.672 NotebookApp] 200 GET /clusters?_=1419694640362 (::1) 2.54ms
    [D 16:38:06.738 NotebookApp] 200 GET /api/contents?type=directory&_=1419694640363 (::1) 2.95ms
    [I 16:38:14.848 NotebookApp] Creating new notebook in 
    [D 16:38:14.850 NotebookApp] Saving /Users/jonathon/Documents/projects/ipykern/Untitled2.ipynb
    [D 16:38:14.860 NotebookApp] 201 POST /api/contents (::1) 12.15ms

here is my system info:

    bin/python -c "import IPython; print(IPython.sys_info())"
    {'commit_hash': u'911aaed',
     'commit_source': 'repository',
     'default_encoding': 'UTF-8',
     'ipython_path': '/Users/jonathon/Documents/projects/ipython/IPython',
     'ipython_version': '3.0.0-dev',
     'os_name': 'posix',
     'platform': 'Darwin-14.0.0-x86_64-i386-64bit',
     'sys_executable': '/Users/jonathon/Documents/projects/ipykern/bin/python',
     'sys_platform': 'darwin',
     'sys_version': '2.7.6 (default, Sep  9 2014, 15:04:36) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]'}

is there any other information i can provide?

with thanks

**Comment by minrk** [comment] 2015-01-13 17:29
I think this is a duplicate of #7328

**Closed by minrk** 2015-01-13 17:29 UTC
Labels: notebook, type-bug

**Comment by jonathon-love** [comment] 2015-01-13 18:18
FWIW, i'm pretty sure this isn't a duplicate of #7328, but i've done a pull, rerun it, and the problem seems to be fixed - so i'm happy for this issue to be closed.
