### ISSUE TITLE
Assertion Error causes crash when using help magic 

### ISSUE THREAD

**Issue by ocehugo** [ipython/ipython#10381] opened 2017-03-06 01:16 UTC
Hi,

an annoying bug haunts me everytime I try to inspect the help of a function during assignment:

```pyhton
import numpy as np
x=np.zeros?  # pressing tab here 
```
generates assertion Error and crashes the session. I would expect that at least the session would be continued after. 

Full output and py/ipython version below:
```
ipython3
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06)
Type "copyright", "credits" or "license" for more information.

IPython 5.2.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import numpy as np

In [2]: x=np.zeros?
Docstring:
zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_like : Return an array of zeros with shape and type of input.
ones_like : Return an array of ones with shape and type of input.
empty_like : Return an empty array with shape and type of input.
ones : Return a new array setting values to one.
empty : Return a new uninitialized array.

Examples
--------
>>> np.zeros(5)
array([ 0.,  0.,  0.,  0.,  0.])

>>> np.zeros((5,), dtype=np.int)
array([0, 0, 0, 0, 0])

>>> np.zeros((2, 1))
array([[ 0.],
       [ 0.]])

>>> s = (2,2)
>>> np.zeros(s)
array([[ 0.,  0.],
       [ 0.,  0.]])

>>> np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom dtype
array([(0, 0), (0, 0)],
      dtype=[('x', '<i4'), ('y', '<i4')])
Type:      builtin_function_or_method

In [3]: x=np.zeros?
Traceback (most recent call last):
  File "/u/hbastos/.eddy/bin/ipython3", line 11, in <module>
    sys.exit(start_ipython())
  File "/u/hbastos/.eddy/apps/miniconda3/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/u/hbastos/.eddy/apps/miniconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/u/hbastos/.eddy/apps/miniconda3/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/u/hbastos/.eddy/apps/miniconda3/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 455, in mainloop
    self.interact()
  File "/u/hbastos/.eddy/apps/miniconda3/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 438, in interact
    code = self.prompt_for_code()
  File "/u/hbastos/.eddy/apps/miniconda3/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 343, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/u/hbastos/.eddy/apps/miniconda3/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 408, in run
    self._pre_run(pre_run)
  File "/u/hbastos/.eddy/apps/miniconda3/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 383, in _pre_run
    pre_run()
  File "/u/hbastos/.eddy/apps/miniconda3/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 425, in pre_prompt
    self.pt_cli.application.buffer.text = cast_unicode_py2(self.rl_next_input)
  File "/u/hbastos/.eddy/apps/miniconda3/lib/python3.5/site-packages/prompt_toolkit/buffer.py", line 371, in text
    assert self.cursor_position <= len(value)
AssertionError

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by Carreau** [comment] 2017-03-06 17:39
can you try updating prompt_toolkit ? I think it's a known error (see #10348 that seem to be a duplicate).

**Comment by takluyver** [comment] 2017-03-06 18:00
You need to upgrade *IPython* to 5.3 (or downgrade prompt_toolkit, but there's no particular reason to do that now that IPython has been updated).

**Comment by ocehugo** [comment] 2017-03-06 23:05
thanks, problem solved. sorry for the duplicate, I forgot to search the closed issues.

**Comment by Carreau** [comment] 2017-03-07 00:22
> thanks, problem solved. sorry for the duplicate, I forgot to search the closed issues.

It' ok, not always easy to find !

Closing.

**Comment by Carreau** [comment] 2017-03-07 00:22
> thanks, problem solved. sorry for the duplicate, I forgot to search the closed issues.

It' ok, not always easy to find !

Closing.

**Closed by Carreau** 2017-03-07 00:22 UTC

**Comment by ocehugo** [comment] 2017-06-06 01:40
@takluyver 

Just tested with Ipython 6.1.0/Python 3.5.1 and prompt-toolkit 1.0.14 and the problem persists. Should I freeze prompt-toolkit to 1.0.9 ?

trying:
```python
fig,ax = plt.subplots(nrows=2)
ax[0].set_xticklabels?
```
crash the session with Assertion Error.

**Comment by takluyver** [comment] 2017-06-08 13:43
I can't reproduce it. Are you sure that it's definitely running IPython 6.1, and that the traceback you see is exactly as above?

**Comment by ocehugo** [comment] 2017-07-27 00:43
Sorry, completely forgot about this one since I solved by falling back to old prompt kit.

I just face the problem again after a global pip update.

Going to a console session and doing:
```python
x = np.array?
#help is displayed
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/site-packages/jupyter_console/app.py", line 155, in start
    self.shell.mainloop()
  File "/usr/local/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 490, in mainloop
    self.interact()
  File "/usr/local/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 474, in interact
    code = self.prompt_for_code()
  File "/usr/local/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 430, in prompt_for_code
    reset_current_buffer=True)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 408, in run
    self._pre_run(pre_run)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 383, in _pre_run
    pre_run()
  File "/usr/local/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 464, in pre_prompt
    b.text = cast_unicode_py2(self.next_input)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 372, in text
    assert self.cursor_position <= len(value)
AssertionError
```
with [ipython 6.1.0/ python3.6.1/ prompt-toolkit 1.0.14/OSX].

So The help magic open the docs as expected but after closing it an assertion error is raised (as above). Console (owned kernel) is also killed (as expected).

Solution: Fall back to old version of prompt-toolkit (1.0.9 my case).

**Comment by takluyver** [comment] 2017-07-27 09:51
That's in jupyter_console rather than IPython. I think jupyter/jupyter_console#123 should fix it.
