### ISSUE TITLE
Many Keybindings don't work on international keyboards.

### ISSUE THREAD

**Issue by AKuederle** [ipython/ipython#8586] opened 2015-06-27 12:17 UTC
Many keybindings will only work on a US-keyboard layout.
Therefore, it would be nice to be able to change the shortcuts.

**Comment by Carreau** [comment] 2015-06-27 12:21
Hi, 

Duplicate of many issues, we are aware, it is possible to change shortcut, though we are cornerd by some technicality web browser implementation that do not allow to distinguish keyboard layout, and even distinguish keys on keyboard layout. 

Example of remap :
```
IPython.keyboard_manager.command_shortcuts.remove_shortcut('Shift-k')
IPython.keyboard_manager.command_shortcuts.add_shortcut('Cmd-minus','ipython.move-selected-cell-up')
```

Problem is on some layout in browser you will get the same event for `minus` and `star`, so there is sometime nothing we can do.

**Closed by Carreau** 2015-06-27 12:21 UTC

**Comment by AKuederle** [comment] 2015-06-27 12:27
Thanks for the fast reply. Sorry for the duplication. Couldn't find a solution during my quick research. Are these options documented somewhere?

**Comment by Carreau** [comment] 2015-06-27 13:24
> Thanks for the fast reply. Sorry for the duplication

No problem, that what we are here for, even if don't always do a good job. 

> Couldn't find a solution during my quick research. Are these options documented somewhere?

Not well, we haven't (yet) found a nice way to get docs. I'm trying on my own to write some [narrative docs](http://carreau.gitbooks.io/jupyter-book/content/keyboardshortcut.html) on how to do theses things, but right now it's still mostly [read the source](https://github.com/jupyter/notebook/blob/master/notebook/static/base/js/keyboard.js#L343-L364). 

We are looking for people that would like to help with that, and will hopefully will find someone. 

We will be also [giving a tutorial, with online material](https://github.com/jupyter/scipy-advanced-tutorial) at scipy in a couple of weeks, which deals, in part, with that. 

You can also have a look at https://github.com/ipython-contrib/IPython-notebook-extensions that provide some custom keybindings for german keyboard.

**Comment by AKuederle** [comment] 2015-06-28 00:30
Thanks again! You pointed me in the write direction. I manged to customize my keybindings as desired and even to write down some kind of "documentation" about what I did: http://akuederle.com/customize-ipython-keymap/

**Comment by Carreau** [comment] 2015-06-28 09:05
Great ! Is the raw file public, I might send a few precision. Like the handler should not refer to the `IPython` global, but is passed an `env` that have references to things.

```
 handler : function (env) {
        var cm=env.notebook.get_selected_cell().code_mirror;
        ...
    }
```

The global *will** go away. I'll read with more care and comment.

**Comment by AKuederle** [comment] 2015-06-28 09:48
The raw file is public (https://github.com/AKuederle/AKuederle.github.io/blob/master/quicktips/_posts/27-06-2015-Change-IPython-keyboard-shortcuts.md). You can create a pull-request or just comment somewhere. What ever works best for you! Looking forward to your comments
