### ISSUE TITLE
ReST static file --> IPython notebook feature request

### ISSUE THREAD

**Issue by scottsievert** [ipython/ipython#8319] opened 2015-04-14 04:18 UTC
#### Idea
Have nbconvert not only go from IPython notebook to HTML/PDF/LaTeX/markdown/ReST but also the other way: ReST/markdown/etc to IPython notebook.

#### Motivation
@nthiery suggested to me that I implement a feature that convert other static files into IPython notebooks at a PyCon sprint, mentioning something about teaching and providing students with live examples in IPython's notebook instead of static examples as .rst files. He suggested that I start with his specific use case: ReST files to IPython notebooks.

#### Implementation
I have implemented the basics of this function with [rst-to-ipynb]. It takes a ReST file and transforms it to an IPython notebook at the most basic level (i.e., no unicode support). I will put more work into this project if it will be integrated into IPython; is there any interest in that? I would like to gauge interest before I make a decision about integrating this into IPython or making a PyPI package.

(my intuition tells me no, this feature will not be welcome in IPython as it seems like a fairly large feature request that should be managed by a third party project. However, it doesn't hurt to ask!)

[rst-to-ipynb]:https://github.com/scottsievert/rst-to-ipynb

**Comment by nthiery** [comment] 2015-04-14 11:09
Thanks Scott for opening this ticket! Let me elaborate a bit on the
two main use cases:

- Like many other Python projects, SageMath is using Sphinx as
  documentation system, and ReST as documentation format
  (with a few specific roles like: :trac:`2334` :wikipedia:`Jupyter`).

  A very nice feature of the Sage notebook is that all the Sage
  documentation can be browsed "live", as notebooks that the user can
  interact with. Having a ReST to Jupyter notebook converter would go
  a long way toward the addition of such a feature to Jupyter.

- A lot of people in the Sage community that write tutorials,
  educational material, experimental log books, etc for distribution
  as notebooks actually write them as ReST document. The rationale for
  this includes:

  - Many such documents are likely to eventually become part of the
    Sage documentation anyway.

  - It's text based, and therefore plays well with version control and
    collaborative editing.

  - It's simple to make such documents "reproducible": just include
    the output, and run tests as we do for our usual documentation (in
    our case with `sage -t foo.rst`).

  Personally that's the last remaining bit in my workflow for
  switching to the Jupyter notebook for my teaching, and I'd love to
  be able to do it next fall.

PS: this is one of the features planned in the OpenDreamKit[3]
proposal. Taking some lead advance does not hurt :-)


[1] http://nicolas.thiery.name/Enseignement/Agregation/
[2] http://nicolas.thiery.name/Enseignement/Agregation/Notes-rst/
[3] https://github.com/sagemath/grant-europe/blob/master/H2020/OpenDreamKit.rst

**Comment by minrk** [comment] 2015-04-14 16:53
I think we do want this to exist, but some pieces aren't quite clear about how to do it:

Does it go in nbconvert, so it's a pandoc-esque conversion to *and* from notebooks?

My guess is that the answer is: "probably, but not initially."

Do we implement it with docutils/sphinx via custom NodeVisitors, etc.?

That would bind it to rst, which might be a useful first step, but would *not* be appropriate for something we would integrate into nbconvert. I'm sure lots of people would find it useful, so I think it's a worthwhile project, even if we end up going in a more generic direction in an official Jupyter project.

Do we use something like [dexy](http://www.dexy.it/), which has the building blocks for almost everything asked for here, and we can provide plugins and/or wrappers to make particular patterns easier, and fill in any existing holes?

This is most attractive to me, currently, since it seems like the most amount of functionality relative to work we have to do and maintain.

**Comment by Carreau** [comment] 2015-04-14 16:54
This will be mostly personal opinion, but I think yes, wee are interested. There used to be a `.rst` importer in nbconvert, but it was not used enough, so we removed it. 

We are also currently splitting the repository in many sub-repository, and I suppose this would be better suited for https://github.com/jupyter/jupyter_nbconvert , and while `.ipynb -> *` seem to be the goal of nbconvert, a `* -> .ipynb` could be, for the beginning a separate repo. This would allow much more freedom for the new code to be pushed directly on master, no PR, lazy review while you iterate quickly. 

There si definitively  an interest with sphinx integration though.

**Comment by Carreau** [comment] 2015-04-14 16:54
And min beat me by responding quicker.

**Comment by scottsievert** [comment] 2015-04-14 23:23
Cool -- good to know there's interest. I can do whatever you guys think is best. Should I polish/publish this package on PyPI or integrate with IPython? (or both?)

**Comment by tacaswell** [comment] 2015-04-15 16:03
@Carreau I may be able to throw some bandwidth at (better?) integration with sphinx (either direction).

**Comment by Carreau** [comment] 2015-04-15 16:04
> Cool -- good to know there's interest. I can do whatever you guys think is best. Should I polish/publish this package on PyPI or integrate with IPython? (or both?)

I would make it as standalone repo for now. If you really feel the pressure to integrate for some reason tell us and we can easily revisit.

**Comment by Carreau** [comment] 2015-04-15 16:06
> @Carreau I may be able to throw some bandwidth at (better?) integration with sphinx (either direction).

Great, we still want also to gather some people (YT, nathan goldbaum) that are interesting in merging their notebook-to-sphinx I think their was a discussion on ML this year, but don't find it.

**Comment by scottsievert** [comment] 2015-04-15 16:31
Making it a standalone repo was my thought as well. I'll publish it on PyPI in the next couple weeks.

**Comment by Carreau** [comment] 2015-04-15 17:54
You don't need tu publish it on Pypi to have it installable and have feedback. Just ping us on https://github.com/scottsievert/rst-to-ipynb when you want advice.

**Comment by takluyver** [comment] 2016-01-26 17:23
Closing as it doesn't look like we're going to fix this. Feel free to keep using the comments to discuss this.

**Closed by takluyver** 2016-01-26 17:23 UTC
Labels: nbconvert
