### ISSUE TITLE
 IPython 7.19.0 bug

### ISSUE THREAD

**Issue by jumploop** [ipython/ipython#12811] opened 2021-02-05 06:33 UTC
λ ipython
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sys
Traceback (most recent call last):
  File "d:\program files\python37\lib\site-packages\IPython\terminal\ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "d:\program files\python37\lib\site-packages\IPython\terminal\ptutils.py", line 129, in _get_completions
    for c in completions:
  File "d:\program files\python37\lib\site-packages\IPython\core\completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "d:\program files\python37\lib\site-packages\IPython\core\completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "d:\program files\python37\lib\site-packages\IPython\core\completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "d:\program files\python37\lib\site-packages\IPython\core\completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "d:\program files\python37\lib\site-packages\IPython\core\completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "d:\program files\python37\lib\site-packages\jedi\api\__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python37\Scripts\ipython.exe\__main__.py", line 7, in <module>
    sys.exit(start_ipython())
  File "d:\program files\python37\lib\site-packages\IPython\__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "d:\program files\python37\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "d:\program files\python37\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
    self.shell.mainloop()
  File "d:\program files\python37\lib\site-packages\IPython\terminal\interactiveshell.py", line 564, in mainloop
    self.interact()
  File "d:\program files\python37\lib\site-packages\IPython\terminal\interactiveshell.py", line 547, in interact
    code = self.prompt_for_code()
  File "d:\program files\python37\lib\site-packages\IPython\terminal\interactiveshell.py", line 475, in prompt_for_code
    **self._extra_prompt_options())
  File "d:\program files\python37\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "d:\program files\python37\lib\site-packages\prompt_toolkit\application\application.py", line 826, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "d:\program files\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "d:\program files\python37\lib\site-packages\prompt_toolkit\application\application.py", line 792, in run_async
    return await _run_async2()
  File "d:\program files\python37\lib\site-packages\prompt_toolkit\application\application.py", line 780, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "d:\program files\python37\lib\site-packages\prompt_toolkit\application\application.py", line 881, in cancel_and_wait_for_background_tasks
    await task
  File "d:\program files\python37\lib\site-packages\prompt_toolkit\buffer.py", line 1909, in new_coroutine
    await coroutine(*a, **kw)
  File "d:\program files\python37\lib\site-packages\prompt_toolkit\buffer.py", line 1739, in async_completer
    document, complete_event
  File "d:\program files\python37\lib\site-packages\prompt_toolkit\completion\base.py", line 270, in get_completions_async
    document, complete_event
  File "d:\program files\python37\lib\site-packages\prompt_toolkit\completion\base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "d:\program files\python37\lib\site-packages\IPython\terminal\ptutils.py", line 116, in get_completions
    exc_type, exc_value, exc_tb = sys.exc_info()
NameError: name 'sys' is not defined

If you suspect this is an IPython 7.19.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by MrMino** [comment] 2021-02-05 13:28
Duplicate of #12797.

**Comment by MrMino** [comment] 2021-04-01 04:47
Fixed in IPython 7.20, see #12793. Fix for older versions is to downgrade Jedi to `==0.17.2`. If this does not fix your problem - please ping me here, I'll reopen.

**Closed by MrMino** 2021-04-01 04:47 UTC
