### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:598)

### ISSUE THREAD

**Issue by sglyon** [ipython/ipython#7649] opened 2015-01-31 21:33 UTC
I have a remote server set up and running the notebook so I can access it remotely. I can connect to the notebook server, enter the password, and see the directory/notebooks. If I try to open a notebook, the kernel never connects and the remote terminal (where ipython notebook is running) says:

```
[E 16:29:51.940 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/home/sgl290/anaconda/envs/py3/lib/python3.4/site-packages/tornado/http1connection.py", line 674, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/home/sgl290/anaconda/envs/py3/lib/python3.4/site-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/home/sgl290/anaconda/envs/py3/lib/python3.4/site-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/sgl290/anaconda/envs/py3/lib/python3.4/site-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/home/sgl290/anaconda/envs/py3/lib/python3.4/site-packages/tornado/http1connection.py", line 165, in _read_message
        io_loop=self.stream.io_loop)
      File "/home/sgl290/anaconda/envs/py3/lib/python3.4/site-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/home/sgl290/anaconda/envs/py3/lib/python3.4/site-packages/tornado/concurrent.py", line 111, in result
        raise self._exception
      File "/home/sgl290/anaconda/envs/py3/lib/python3.4/site-packages/tornado/iostream.py", line 1167, in _do_ssl_handshake
        self.socket.do_handshake()
      File "/home/sgl290/anaconda/envs/py3/lib/python3.4/ssl.py", line 805, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:598)
```

This used to work (not sure how long ago, it has been a while), but it doesn't anymore. Any suggestions?

I have tried this from python 2 and 3 with current master. Same result with either python version.

**Comment by takluyver** [comment] 2015-02-10 01:20
Is it possible that openssl got upgraded as well, like in #7702? Otherwise, no idea about SSL errors.

**Comment by minrk** [comment] 2015-02-13 00:48
@spencerlyon2 can you test the tornado websocket demo with ssl, and see if it comes up with the same issue?

**Comment by spencerlyon2** [comment] 2015-02-13 00:59
@minrk, sure I'd be happy to. How do I run that?

**Comment by minrk** [comment] 2015-02-13 01:10
Download [the example](https://github.com/tornadoweb/tornado/tree/master/demos/websocket), edit chatdemo.py to use your ssl files, then try to run the demo.

**Comment by fonnesbeck** [comment] 2015-03-03 00:28
I'm getting this error as well when trying to connect to a server running on Digital Ocean. Its not clear to me where to put my ssl info in chatdemo.py, but I'd be happy to test it.

**Comment by fonnesbeck** [comment] 2015-03-03 20:02
I've tried installing Anaconda on my server and using the latest IPython, Tornado and openssl, but the same issue crops up.

**Comment by fonnesbeck** [comment] 2015-03-03 20:12
This turns out to be a Safari issue. Accessing with Chrome does not cause the exception.

**Comment by spencerlyon2** [comment] 2015-03-03 21:06
Yep, confirmed. This works for me when I use a different browser. Thanks for commenting. As this is not an IPython issue, perhaps we should close the issue here?

**Comment by hannorein** [comment] 2015-05-19 21:39
Indeed a Safari issue. Chrome works fine for me too.

**Comment by nathanielatom** [comment] 2015-07-01 05:25
This is also an issue on iOS devices. I don't know much about SSL, but this may be a similar problem http://stackoverflow.com/questions/14102416/python-requests-requests-exceptions-sslerror-errno-8-ssl-c504-eof-occurred

**Comment by saurav111** [comment] 2015-07-10 08:42
I had the same issue with Firefox.

**Comment by Carreau** [comment] 2017-07-19 20:00
Hi, 

This issue has been quiet for almost 2 years, and I don't think there is anything we can do. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

Thanks.

**Closed by Carreau** 2017-07-19 20:00 UTC
