### ISSUE TITLE
Errors were randomly raised while using Ipython in CMD.

### ISSUE THREAD

**Issue by GasinAn** [ipython/ipython#12737] opened 2020-12-21 14:51 UTC
When I used Ipython in CMD, randomly it showed this:

Unhandled exception in event loop:
  File "C:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)

Exception [WinError 995] 由于线程退出或应用程序请求，已中止 I/O 操作。
Press ENTER to continue...

("由于线程退出或应用程序请求，已中止 I/O 操作。" means "The I/O operation was aborted due to thread exit or application request.")

However, I still could continue using Ipython. An example:

Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: print('Hello, world!')
Hello, world!

In [2]: print('Hello, world!')
Hello, world!

In [3]: print('Hello, world!')
Hello, world!

In [4]: print('Hello, world!')
Hello, world!

Unhandled exception in event loop:
  File "C:\ProgramData\Anaconda3\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\ProgramData\Anaconda3\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)

Exception [WinError 995] 由于线程退出或应用程序请求，已中止 I/O 操作。
Press ENTER to continue...
In [5]: print('Hello, world!')
Hello, world!

I am really unwilling to see these :(.

**Comment by GasinAn** [comment] 2020-12-21 14:57
These errors were never raised until I reinstall Anaconda in December.

**Comment by MrMino** [comment] 2021-04-20 20:36
@GasinAn is this still an issue for you? Have you tried with an updated IPython version? I remember seeing these errors while working on Windows, but I thought it's due to the particularities of my setup.

**Comment by MrMino** [comment] 2021-04-21 01:26
Duplicate of #12722. @GasinAn let's continue there.

**Closed by MrMino** 2021-04-21 01:26 UTC

**Comment by GasinAn** [comment] 2021-04-23 21:50
@MrMino Thank you, now everything is well.

**Comment by GasinAn** [comment] 2021-04-23 21:56
@MrMino But I don't know when it was fixed :). When I faced that problem, I commented the line which raised exceptions, and also one day I uninstalled Anaconda and installed Miniconda, all in all now everything goes well.

**Comment by MrMino** [comment] 2021-04-23 22:12
@GasinAn Me neither :) Probably I just wasn't around when the fix happened. In any case, if you happen to trigger the error again in the future, please put the logs into #12722
