### ISSUE TITLE
%run notebook.ipynb is anymore not possible because magic command adds .py extensions automatically

### ISSUE THREAD

**Issue by Latvala** [ipython/ipython#13542] opened 2022-02-24 11:55 UTC
In older versions of ipython I was able to run ipynb notebooks from jupyter like this: 
%run mynotebook.ipynb

Now at least in the version of 7.22.0 I got exception that file not found. Thats because it tries to find file "mynotebook.ipynb.py". 

I did not found to way to prevent that automatic addition of .py extension. In 7.2.0 this does not happened.

**Comment by Carreau** [comment] 2022-02-25 11:02
I'll need a tad bit more info, as it work here with 7.22 and above:

```
ipython
Python 3.10.0 | packaged by conda-forge | (default, Oct 12 2021, 21:22:54) [Clang 11.1.0 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %run Untitled.ipynb
Ran

````

Are you sure the path to `mynotebook.ipynb` is correct, it maybe just the error message that is wrong ?

**Comment by MrMino** [comment] 2022-02-27 18:43
I cannot reproduce this on `master`.

```
Python 3.8.10 (default, Nov 26 2021, 20:14:08)                         
Type 'copyright', 'credits' or 'license' for more information          
IPython 8.2.0.dev -- An enhanced Interactive Python. Type '?' for help.
                                                                       
In [1]: %run "./Untitled.ipynb"                                        
hello world                                                            
                                                                       
In [2]: %run ./Untitled.ipynb                                          
hello world                                                                
```

**Comment by MrMino** [comment] 2022-03-03 22:41
I'm going to close this as not reproducible. Feel free to reopen / ping me if this issue is still affecting you.

**Closed by MrMino** 2022-03-03 22:41 UTC
Labels: needs-info

**Comment by Latvala** [comment] 2022-03-04 06:55
Thank you for responses! To confirm/uncormin this issue I made a fresh new install of python to my work computer and the problem disappeared. Before that it really tried to look the mynotebook.ipynb.py file based on the error message. So it was propably something strange with my install to cause this. Thanks!

**Comment by philipkd** [comment] 2022-06-16 18:22
This is still an issue. Visit [JupyterLite](https://jupyter.org/try-jupyter/lab/) and run `%run Lorentz.ipynb`

**Comment by MrMino** [comment] 2022-06-16 19:08
@philipkd I see what happened here.

IPython didn't found the file in question, then proceeded to try to speculatively run the same file with `.py` added.

Since the paths are relative to the place Jupyter run the kernel from (_the CWD of the kernel_), it's easy to mistake this as an issue with "IPython adding extension to a valid path and then failing".

See #13700.

**Comment by Peteresis** [comment] 2022-11-11 01:14
Hello,

Today, I had the same problem, and it turned out that the ipynb had become corrupted in some way. So, all I had to do to resolve the problem was to create a new ipynb file (Jupyter notebook) and copy the code from the corrupted file onto the new file. As a precaution, I have to say that I changed a bit the name of the new file so that I would not accidentally use the name of the corrupted file.
