### ISSUE TITLE
(500) Internal Server Error while converting IPython Notebook to Python

### ISSUE THREAD

**Issue by sahilshekhawat** [ipython/ipython#7369] opened 2015-01-04 16:29 UTC
For reference here is the Traceback:
![ipython_bug](https://cloud.githubusercontent.com/assets/5890452/5606597/196b74d0-945c-11e4-9b7a-4175bd405e61.png)
Here is the notebook for which the Traceback is attached, although I have tried many different notebooks. https://gist.github.com/sahilshekhawat/b6a506e051b909e6131a

**Comment by minrk** [comment] 2015-01-04 19:12
Make sure both IPython and mistune are up to date:

    pip install --upgrade mistune

closing as duplicate of #7135.

**Closed by minrk** 2015-01-04 19:12 UTC
