### ISSUE TITLE
[Completions] Enabling greedy completion breaks filename completion

### ISSUE THREAD

**Issue by JeremySikes73** [ipython/ipython#10925] opened 2017-11-28 16:05 UTC
The line below does what you expect when `c.Completer.greedy = False` and does nothing 
when it is on.

```python
In [1]: open('./<TAB>
```

I've worked around by modifying [GREEDY_DELIMS](https://github.com/ipython/ipython/blob/474d48d9541e3efd3b8d4a6ea6a5276f7751e977/IPython/core/completer.py#L512) to include single/quotes, but haven't delved into things sufficiently to discount unintended consequences.

**Comment by krassowski** [comment] 2022-11-19 21:34
This looks like a duplicate of https://github.com/ipython/ipython/issues/5646. I will close this issue but please reopen if I misunderstood.

**Closed by krassowski** 2022-11-19 21:34 UTC
Labels: tab-completion
