### ISSUE TITLE
Code blocks being executed prematurely

### ISSUE THREAD

**Issue by max-l-weaver** [ipython/ipython#11433] opened 2018-10-22 15:21 UTC
system info (some info redacted):
```
{'commit_hash': '3772d25df',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/maxweaver/**/python_projects/**/venv/lib/python3.7/site-packages/IPython',
 'ipython_version': '7.0.1',
 'os_name': 'posix',
 'platform': 'Darwin-16.7.0-x86_64-i386-64bit',
 'sys_executable': '/Users/maxweaver/**/python_projects/**/venv/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) \n'
                '[Clang 6.0 (clang-600.0.57)]'}
```

I am currently experiencing an issue with iPython installed in a 3.7 venv whereby multiline blocks of code are getting executed prematurely.

It used to be that if I was writing an if/else statement or similar, hitting return would give me a new line and hitting return twice would execute the code.

Now it seems iPython 7.0.1 is preventing me from doing this, so if I wanted to write a simple if/else statement in a function like below:
```
In [1]: def test_foo(foo):
   ...:     if isinstance(foo, str):
   ...:         print("foo is a string")
   ...:     elif isinstance(foo, list):
   ...:             print("foo is a list")
```
it would allow me to write the first condition and then execute:
```
In [1]: def test_foo(foo):
   ...:     if isinstance(foo, str):
   ...:         print("foo is a string")
in[2]:
```

Things I've tried:

- Holding down shift and enter
- trying in another venv
- trying a different version of Python3
- trying in another terminal emulator (I use iterm as my main emulator)

I have also tried replicating on iPython 6.5.0 which works perfectly:
```
In [1]: if 1 < 2:
   ...:     print("")
   ...: elif i > 2:
   ...:     print("")
   ...:
```

System info of working 6.5.0 env:
```
{'commit_hash': 'dd83a2163',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/maxweaver/**/venv3.7/lib/python3.7/site-packages/IPython',
 'ipython_version': '6.5.0',
 'os_name': 'posix',
 'platform': 'Darwin-16.7.0-x86_64-i386-64bit',
 'sys_executable': '/Users/maxweaver/**/venv3.7/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) \n'
                '[Clang 6.0 (clang-600.0.57)]'}
```

**Comment by Carreau** [comment] 2018-10-22 16:02
duplicate of #11334, #11385. Fixed on master.

**Closed by Carreau** 2018-10-22 16:02 UTC
