### ISSUE TITLE
IPython in Interactive Mode quits when it hits an assert.

### ISSUE THREAD

**Issue by Redoubts** [ipython/ipython#9326] opened 2016-03-14 23:31 UTC
OS X 10.11, Python 2.7.10, IPython 4.1.2

Suppose I have a file with just one line
```
# test.py
assert False
```

if I run this in ipython with interactive mode, I would expect the shell to stick around after it hits the assert. Instead, it quits immediately.

```
redoubts@aloxiprin:~/Desktop 2016-03-14 16:27:19 (479690839)
% ipython -i test.py
Python 2.7.10 (default, Mar 13 2016, 08:45:09) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/Users/redoubts/Desktop/test.py in <module>()
----> 1 assert False

AssertionError: 
redoubts@aloxiprin:~/Desktop 2016-03-14 16:27:59 (479690879)
% 
```

The standard python shell handles this as I would expect, by hanging around after the assert:

```
redoubts@aloxiprin:~/Desktop 2016-03-14 16:27:00 (479690820)
% python -i test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    assert False
AssertionError
>>> 
>>> 
```

**Comment by minrk** [comment] 2016-03-15 12:47
Duplicate of #9223, fixed by #9225.

**Closed by minrk** 2016-03-15 12:47 UTC
