### ISSUE TITLE
Notebook not working if websocket is on different port

### ISSUE THREAD

**Issue by fnkr** [ipython/ipython#7178] opened 2014-12-11 17:14 UTC
**Start script**

```
cd data
exec ../env/bin/ipython notebook \
                        --no-browser \
                        --port 65170 \
                        --ip=127.0.0.1 \
                        --NotebookApp.websocket_url="wss://ipy.example.com:65180" \
                        --ipython-dir="../profile" \
                        --NotebookApp.password="$HASH"
```

**Directory structure**
- data (notebooks should be here later)
- env (virtualenv with ipython installed from git/master branch)
- profile (folder with ipy profile (default profile, no changes by me))

**Ports**
- Port 443: HTTPS, Apache, Reverse Proxy to localhost:65170 (iPy Notebook), reverse proxy **doesn't** support sockets
- Port 65180: HTTPS, Nginx, Reverse Proxy to localhost:65170 (iPy Notebook), reverse proxy **does** support sockets, should be used only for websockets (invisible)
- Port 65170: HTTP, iPython Notebook, not accessible from outside

**Problem**

Websockets not working, Status Code 403

**Server log**

```
[W 15:49:02.428 NotebookApp] Couldn't authenticate WebSocket connection
[W 15:49:02.430 NotebookApp] 403 GET /api/kernels/41f30668-8147-47dd-84f0-4e7b19b5e320/shell?session_id=4A64BD2B6516499ABDFE1AFF7813C941 (127.0.0.1) 4.98ms referer=None
```

**Comment by ellisonbg** [comment] 2015-01-11 23:07
Any progress on this one?

**Comment by fnkr** [comment] 2015-01-14 19:14
I dont think so.

**Comment by chizou** [comment] 2016-07-07 15:24
I'm also experiencing this using Cloud Foundry because CF's default behaviour is to have WebSockets go to port 4443. Any tips on how to go about pinpointing the root cause of this?

**Comment by chizou** [comment] 2016-07-07 17:11
So I've got it figured out now. I removed the `--NotebookApp.password` directive and I now see this extra line in the log files:

```
ERR [W 15:36:36.773 NotebookApp] Blocking Cross Origin WebSocket Attempt.  
Origin: https://jupyter-notebook-unblissful-nondancer.somedomain.com, Host: 
jupyter-notebook-unblissful-nondancer.somedomain.com:4443
```

I had to add the following startup option to get it to work `--NotebookApp.allow_origin=https://jupyter-notebook-unblissful-nondancer.somedomain.com`

**Comment by Carreau** [comment] 2017-07-20 17:08
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.

**Closed by Carreau** 2017-07-20 17:08 UTC
Labels: needs-info, notebook
