### ISSUE TITLE
Documentation needed for JavaScript Notebook Extensions

### ISSUE THREAD

**Issue by dsblank** [ipython/ipython#6229] opened 2014-07-28 23:12 UTC
Need some documentation for JavaScript Notebook Extensions. 

Please review http://mail.scipy.org/pipermail/ipython-dev/2014-July/014509.html and see if that could form the basis for some documentation. 

There is a question in that post, too, about how JavaScript in a Notebook behaves on re-open that I don't quite understand.

**Comment by ellisonbg** [comment] 2015-01-12 19:22
I think we have another duplicate of this, but can't find it.

**Comment by damianavila** [comment] 2015-01-12 22:23
Are you referring to #7392?

**Comment by ellisonbg** [comment] 2015-01-12 22:40
Yep that is it, thanks.

**Comment by jdfreder** [comment] 2015-01-27 23:58
*Thinking out loud:*  It's unfortunate that `ipython install-nbextension URL` doesn't have a flag that allows you to automagically add a line to the profile of choice (default if unspecified) to load the installed extension.

**Comment by ellisonbg** [comment] 2015-01-27 23:59
Nice out loud thought! Or even just prompt using raw_input...

On Tue, Jan 27, 2015 at 3:58 PM, Jonathan Frederic <notifications@github.com
> wrote:

> *Thinking out loud:* It's unfortunate that ipython install-nbextension URL
> doesn't have a flag that allows you to automagically add a line to the
> profile of choice (default if unspecified) to load the installed extension.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/6229#issuecomment-71755011>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by takluyver** [comment] 2015-01-28 00:06
My approach to this is to have an install script with my extension that uses IPython's functionality to install and enable it - see cite2c's [install.py](https://github.com/takluyver/cite2c/blob/master/install.py).

I'd be wary of providing too much functionality directly from `install-nbextension` because of the risk that we end up building a package manager in addition to everything else.

**Comment by jdfreder** [comment] 2015-01-28 00:17
@takluyver your solution is nice.  Maybe this yet to be written documentation should mention it.

**Comment by ellisonbg** [comment] 2015-01-28 00:18
+1 on not inventing another packaging system....pretty easy call on that
one...

On Tue, Jan 27, 2015 at 4:17 PM, Jonathan Frederic <notifications@github.com
> wrote:

> @takluyver <https://github.com/takluyver> your solution is nice. Maybe
> this yet to be written documentation should mention it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/6229#issuecomment-71757225>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by damianavila** [comment] 2015-01-28 01:42
Same idea as @takluyver, it probably needs some update but you get the idea: https://github.com/damianavila/live_reveal/blob/master/setup.py

**Comment by Carreau** [comment] 2017-07-20 17:05
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.

**Closed by Carreau** 2017-07-20 17:05 UTC
Labels: Docathon, documentation, notebook
