### ISSUE TITLE
new notebook command: "Reset & Run All"

### ISSUE THREAD

**Issue by n1ywb** [ipython/ipython#4468] opened 2013-10-31 18:08 UTC
It would be awesome if ipython notebook had a command to reset the interpreter and run all cells. It's a two step process which I find myself having to often enough that the time savings would be significant.

**Comment by hugadams** [comment] 2015-01-22 21:02
I noticed this was closed, and wondered what the final decision was?

**Comment by Carreau** [comment] 2015-01-22 21:14
> I noticed this was closed, and wondered what the final decision was?

No, 6199 was closed as duplicate. This is still open. Github UI can be confusing.

**Comment by hugadams** [comment] 2015-01-22 21:18
Doh!

Well I'm still +1 for this.  When developing widgets, the process is change some python code, setup.py, kernel restart, run all.  Anyone else in this pattern, here's a tiny snippet to reinstall python from within the notebook environment:

```
%%capture
olddir = os.getcwd()
%cd /home/glue/Desktop/fibersim
%run setup.py develop
os.chdir(olddir)
```

Even a magic method like %restart-rerun would be a great solution.  @Carreau The javascript you pasted early on, could I run that in a notebook cell instead of in a separate .js file?

**Comment by Carreau** [comment] 2015-01-22 21:21
We are woking on having custom actions (done), menu (in progress) , menubar (done) and keyboard shortcut (done). So adding the action yourself should be easy. See #6668 et #6700 (not docs yet and API not stable)

**Comment by Carreau** [comment] 2015-01-22 21:22
> Even a magic method like %restart-rerun would be a great solution. @Carreau The javascript you pasted early on, could I run that in a notebook cell instead of in a separate .js file?

Yes, use `%%javascript` at the beginning of cell. Though you might not want to wrap in the event thing,

**Comment by hugadams** [comment] 2015-01-22 21:24
Ok, thank you!

**Comment by hugadams** [comment] 2015-01-22 21:29
This is the code I used:

```
%%javascript

$([IPython.events]).on('notebook_loaded.Notebook', function(){
    IPython.toolbar.add_buttons_group([
        {
             'label'   : 'kill and run-all',
             'icon'    : 'ui-icon-calculator',
             'callback': function(){
                 IPython.notebook.kernel.restart();
                 IPython.notebook.run_all_cells(); // or whatever
             }
        }
        ]);
});
```

When you say the "event thing", do you mean the on('notebook_loaded.Notebook'...) part?  I will just try to throw this into my .js file, sorry to be a pain

**Comment by Carreau** [comment] 2015-01-22 21:33
yep, just:

```
%javascript
IPython.toolbar.add_buttons_group([
        {
             'label'   : 'kill and run-all',
             'icon'    : 'fa fa-icon-calculator',
             'callback': function(){
                 IPython.notebook.kernel.restart();
                 IPython.notebook.run_all_cells(); // or whatever
             }
        }
    ]);

```

**Comment by hugadams** [comment] 2015-01-22 21:44
So this adds the button (i had to  use `%%javascript` not `%javascript`) and restarts the kernel when clicked, but doesn't seem to run the cells.  If I put it in a blank notebook, generate the new button, then make some cells below like:

     [ ] print 'test'

When I push the button, the print statement is not called and the cell does not show it has been run (ie [ ] turns to [1]).  

This works on yours, yes?  I'm using master branch.

**Comment by Carreau** [comment] 2015-01-22 22:02
Ah, details, details... `run_all...`, has been renamed to `execute_all...` apparently. I guess that what the `// or whatever` in the code was implying.

```
%%javascript
IPython.toolbar.add_buttons_group([
        {
             'label'   : 'kill and run-all',
             'icon'    : 'fa fa-angle-double-down',
             'callback': function(){
                 IPython.notebook.kernel.restart();
                 IPython.notebook.execute_all_cells(); // or whatever
             }
        }
    ]);
```
(and you will get a nice icon too)

**Comment by Carreau** [comment] 2015-01-22 22:02
Note : this works (for 3.0) but is not the canonical way of doing it, it is the shortest.

**Comment by hugadams** [comment] 2015-01-22 22:15
Thanks.  I see the icon, but it still isn't running the cells.  Don't worry about it though, I'll try to figure it out.

**Comment by jakevdp** [comment] 2015-09-05 18:57
I think the issue is that there needs to be a pause between "restart kernel" and "run al cells". This works for me:
```
%%javascript
IPython.toolbar.add_buttons_group([
        {
             'label'   : 'kill and run-all',
             'icon'    : 'fa fa-angle-double-down',
             'callback': function(){
                 IPython.notebook.kernel.restart();
                 setTimeout(function(){
                     IPython.notebook.execute_all_cells();
                 }, 1000);
             }
        }
    ]);
```

**Comment by minrk** [comment] 2015-09-05 19:46
A delay will be sensitive to slow-starting kernels (Julia), but setting a `.once` callback on the kernel_ready event should work.

**Comment by jakevdp** [comment] 2015-09-05 21:24
Got it – so this is a better route:
```
%%javascript
IPython.toolbar.add_buttons_group([
        {
             'label'   : 'kill and run-all',
             'icon'    : 'fa fa-angle-double-down',
             'callback': function(){
                 IPython.notebook.kernel.restart();
                 $(IPython.events).one('kernel_ready.Kernel',
                                       function(){IPython.notebook.execute_all_cells();});
             }
        }
    ]);
```

**Comment by minrk** [comment] 2015-09-06 16:02
@jakevdp yup, that's about it. I made jupyter/notebook#400 with the action. The only difference from yours is it takes the confirmation dialog route.

**Comment by hugadams** [comment] 2015-09-07 15:32
Thanks guys

**Closed** 2015-09-11 23:04 UTC
