### ISSUE TITLE
Error on django

### ISSUE THREAD

**Issue by night-fury-web** [ipython/ipython#12741] opened 2020-12-25 18:39 UTC
When I installed ipython along with packages in https://github.com/mirumee/saleor/blob/2.11/requirements_dev.txt and ran `python manage.py shell`, I got 
`ctypes.ArgumentError: argument 1: <class 'TypeError'>: expected LP_c_ulong instance instead of LP_SECURITY_ATTRIBUTES` error.

I tried different python versions(3.7, 3.8) and ipython versions, but nothing worked.

**Comment by illagrenan** [comment] 2021-02-08 11:57
I have the same problem. In my case, this error was caused by this package: `pywatchman`.

**Comment by MrMino** [comment] 2021-04-20 20:39
@sandguardian could you please give the full log? It's difficult to go by just a last line of traceback. Why do you think its an issue with IPython?

**Comment by MrMino** [comment] 2022-03-27 18:12
I'm going to close this in the interest of having a cleaner issue backlog. Should you encounter this again, please ping us here, and add the full traceback.

**Closed by MrMino** 2022-03-27 18:12 UTC
Labels: needs-info
