### ISSUE TITLE
Ctrl-c not working?

### ISSUE THREAD

**Issue by pikeas** [ipython/ipython#10096] opened 2016-12-19 20:12 UTC
macOS Sierra 10.2.1, multiple versions of Python (2.7.12/3.5.2), iPython 5.1.0.

Expected: ctrl-c creates a new line.
Actual: nothing happens.

Other control commands, for example ctrl-d to exit, are working, only ctrl-c appears to be broken.

**Comment by takluyver** [comment] 2016-12-20 11:59
Ctrl-C while code is running should interrupt it. While you're typing code, it should clear the input. If the input is already empty, you won't see anything change. Is this what you mean? This is a change from earlier versions of IPython, but it is intentional.

**Comment by willingc** [comment] 2016-12-20 16:27
On Sierra 10.2.2, Ctrl-C works as described by @takluyver. Question for @takluyver: is there a key combination to create a new line?

**Comment by takluyver** [comment] 2016-12-20 17:34
If your input is incomplete (e.g. `def f():`), pressing enter will get you a new line. We don't currently have a shortcut to force adding a new line. The obvious ones are with enter, but the only one we can detect is `esc, enter` (also `alt+enter` on some systems), which is in use for the opposite case: force execution where it would otherwise try to add a new line.

**Comment by willingc** [comment] 2016-12-21 00:58
@takluyver Thanks for the additional detail.

**Comment by takluyver** [comment] 2017-01-13 13:45
Closing as no further details turned up, and Carol couldn't reproduce any problem.

**Closed by takluyver** 2017-01-13 13:45 UTC
