### ISSUE TITLE
setting figsize with inline backend

### ISSUE THREAD

**Issue by akhmerov** [ipython/ipython#9676] opened 2016-06-28 22:22 UTC
#### Short issue description

Trying to set the figure size when using inline backend kills the kernel
#### Reproducing

Execute in a notebook the following:

``` python
%matplotlib inline
from matplotlib import pyplot
import numpy as np

fig = pyplot.figure(figsize=(300, 1000))
ax = fig.add_subplot(1, 1, 1)
ax.imshow(np.random.randn(100, 100))
```
#### Observed behavior

Kernel dies.
#### Version information

Tested on notebook 4.2.0, ipython 4.2.0, matplotlib 1.5.1, verified on tmpnb.

Let me know if the issue doesn't belong to this repo.

**Comment by takluyver** [comment] 2016-06-29 09:32
Pinging @tacaswell and @jenshnielsen.

The crash reporting thing on my system indicates that it segfaults in `RendererAgg::RendererAgg`. I can confirm that commenting out `figsize=...` makes it work OK.

It might be something we're doing wrong, but we'll probably need the matplotlib developers' help to work out what.

**Comment by akhmerov** [comment] 2016-06-29 12:55
Whoops, I think I realize what I did wrong. I'm not requesting an image of 300x1000 pixels, but rather 300x1000 inches (so a rather large figure). Don't think it should cause a segfault though.

**Comment by jenshnielsen** [comment] 2016-06-29 12:59
Yes that sounds likely, I agree that it should not segfault. This is probably a duplicate of / related to https://github.com/matplotlib/matplotlib/issues/6661

**Comment by akhmerov** [comment] 2016-06-29 13:02
Possible, although at 80dpi it's not a gigantic figure (nothing close to 2**16).

**Comment by tacaswell** [comment] 2016-06-29 13:34
2**16 is 'only' 65k so you are over running in the y-direction.

attn @mdboom I suspect we lost a validation step someplace in removing CXX?

**Comment by Carreau** [comment] 2016-06-29 23:33
Issue `#6666` . Sounds about right.

**Comment by MrMino** [comment] 2022-06-16 15:48
Instead of dying kernel, this now results in the following exception:

```
ValueError: Image size of 21600x72000 pixels is too large. It must be less than 2^16 in each direction.
```

...which looks about correct.

**Closed by MrMino** 2022-06-16 15:48 UTC
