### ISSUE TITLE
In the notebook interface the auto-parentheses doesn't work

### ISSUE THREAD

**Issue by drorata** [ipython/ipython#7920] opened 2015-03-02 10:59 UTC
I'm not sure whether this is only a local problem or something I missed, but since upgrading to 3.0 the parentheses do not autocomplete. Any idea?

**Comment by mathieu1** [comment] 2015-03-02 11:25
This is discussed in #7896

**Comment by minrk** [comment] 2015-03-02 17:31
closing as duplicate of #7919

**Closed by minrk** 2015-03-02 17:31 UTC
