### ISSUE TITLE
Browser chokes when the output comes too quickly

### ISSUE THREAD

**Issue by peter-ch** [ipython/ipython#8490] opened 2015-05-30 17:55 UTC
This may have been reported already, but here is something I noticed with IPython 3.1, Python 3.4, Firefox 38.0 on Ubuntu 14.04 x64. I have a notebook that very quickly calls clear_output(wait=True) and print() in succession. It just prints a loop counter, but if I forget to put delays, the output comes so quickly that no updates can be seen (it just stays the same number), the entire browser stops responding (I can't stop the notebook once this starts), and the browser starts taking GBs of RAM. Sometimes I don't know in advance how much time a loop iteration will take and every time it is too fast it crashes like this and the only way out is to kill the browser process.

**Comment by minrk** [comment] 2015-10-12 11:50
closing as dupe of #6516

**Closed by minrk** 2015-10-12 11:50 UTC
