### ISSUE TITLE
need to add to the docs: additionaly dependency: functools32   (via pip install)

### ISSUE THREAD

**Issue by shula** [ipython/ipython#8619] opened 2015-07-09 14:03 UTC
the docs says "pip install pyzmq jinja2 tornado mistune jsonschema pygments terminado"

but i had to install also functools32  --- it didn't come by default

(linux mint 17 / python2.7)

**Comment by Carreau** [comment] 2015-07-09 14:09
Seem to be duplicate of https://github.com/ipython/ipython/issues/8509 and/or https://github.com/ipython/ipython/issues/5979 , we don't  depends on functools23 directly, so there is no reason to describe that's it's needed.

**Comment by jenshnielsen** [comment] 2015-07-09 14:09
I think the relevant bug in JSONSchema is  https://github.com/Julian/jsonschema/issues/233

**Closed** 2015-07-09 14:17 UTC
