### ISSUE TITLE
LaTeX in Jupyter notebook

### ISSUE THREAD

**Issue by jsiah** [ipython/ipython#9241] opened 2016-02-18 03:10 UTC
Why do I get along vertical line at the end of any equation/set of equations whenever I use LaTeX in Jupyter markdown cell. See below:

<img width="648" alt="screen shot 2016-02-17 at 9 48 03 pm" src="https://cloud.githubusercontent.com/assets/7934884/13132670/d092654e-d5c2-11e5-84b3-060bcd164ff5.png">

I appreciate any help. Thanks

**Comment by minrk** [comment] 2016-02-18 08:53
This is a bug in MathJax 2.5 + Chrome, and is fixed in the next release of the notebook (4.2). We may consider shipping a backport of the fix for notebook-4.1.1.

**Comment by takluyver** [comment] 2016-02-18 11:44
Closing as dupe of jupyter/notebook#1010

**Closed by takluyver** 2016-02-18 11:44 UTC
