### ISSUE TITLE
Python 3.6 Format Strings break text coloring in Jupyter Notebook

### ISSUE THREAD

**Issue by DaveGavin** [ipython/ipython#10394] opened 2017-03-12 21:47 UTC
All code from the initial f of the new python format strings turns red.  The notebook does not seem to recognize the end of the string.

An example from my current studies:

    hidden_size = 4
    np.random.seed(1)

    weights_input_hidden_0 = np.random.random((3, hidden_size)) 
    weights_input_hidden_1 = 2 * weights_input_hidden_0
    weights_input_hidden_2 = 2 * weights_input_hidden_0 - 1

    print(f'Test 0:\n{weights_input_hidden_0}')
    print(f'Test 1:\n{weights_input_hidden_1}')
    print(f'Test 2:\n{weights_input_hidden_2}')

Everything between the first f' and the end of the cell is displayed in a red font.  

The code executes without issue.  It seems to just be a problem with the notebook not recognizing the end of the string for display purposes.

**Comment by Carreau** [comment] 2017-03-13 15:28
Duplicate of jupyter/notebook#2218 it should be fixed by the soon to be release notebook 5.0

**Closed by Carreau** 2017-03-13 15:28 UTC
