### ISSUE TITLE
Issue with colors on Windows since IPython 5

### ISSUE THREAD

**Issue by segevfiner** [ipython/ipython#10238] opened 2017-02-03 11:31 UTC
I'm having some issues with colors in IPython 5 on Windows that I'm currently working around using configuration.

## Prompt Numbers
The prompt numbers are not using a bright color like they used to in IPython versions before 5. They use the same color as the In/Out text, I'm currently using this to override this: (Copied and modified from [IPython/terminal/interactiveshell.py:275-286](https://github.com/ipython/ipython/blob/e8341164d5f525a3bb3bf440cb042cc8145a5642/IPython/terminal/interactiveshell.py#L275-L286)
```py
c.TerminalInteractiveShell.highlighting_style_overrides = {
    Token.Number: '#007700',
    Token.Operator: 'noinherit',
    Token.String: '#BB6622',
    Token.Name.Function: '#2080D0',
    Token.Name.Class: 'bold #2080D0',
    Token.Name.Namespace: 'bold #2080D0',
    Token.Prompt: '#ansidarkgreen',
    Token.PromptNum: '#ansigreen bold',
    Token.OutPrompt: '#ansidarkred',
    Token.OutPromptNum: '#ansired bold',
}
```

### Before
![ipython5-prompt-before](https://cloud.githubusercontent.com/assets/24731903/22589629/e3932136-ea13-11e6-8a8c-bb16540225c9.PNG)

### After
![ipython5-prompt-after](https://cloud.githubusercontent.com/assets/24731903/22589637/e9c7d5a6-ea13-11e6-8e8b-869454a8ba4f.PNG)

## Tracebacks highlighting
The highlighting used for tracebacks is weird, the code is highlighted like it used to before IPython 5 (I guess it's because of this: https://github.com/ipython/ipython/commit/7b7d560822d4e9b6ab486393e22e305c502ff6d1), But the text that decorates the traceback is using dark colors that are a bit hard on the eyes. I'm using this to override this:
```python
c.InteractiveShell.colors = 'Linux'  # Use Linux colors instead of Neutral
c.TerminalInteractiveShell.highlighting_style = 'default'  # Use default instead of monokai
```

The traceback coloring is defined here: [IPython/core/excolors.py](https://github.com/ipython/ipython/blob/master/IPython/core/excolors.py)

### Before
![ipython5-tb-before](https://cloud.githubusercontent.com/assets/24731903/22589787/c761f0ea-ea14-11e6-8219-49bc0f88ec7f.PNG)

### After
![ipython5-tb-after](https://cloud.githubusercontent.com/assets/24731903/22589793/cb02efba-ea14-11e6-9c02-02d93baae883.PNG)

## Live highlighting is different from tracebacks
(Not Windows related, but I want to mention this since it appears in the screenshots) 
The highlighting used for code in prompts is different from the one used in tracebacks (It's even a different library 😛 ), but I think this bit is known already. It shouldn't be too difficult to create a Pygments style which would make them the same but I haven't bothered with this.

## System Info
```python
{'commit_hash': u'be4827b',
 'commit_source': 'installation',
 'default_encoding': 'cp862',
 'ipython_path': 'C:\\Python27\\lib\\site-packages\\IPython',
 'ipython_version': '5.2.1',
 'os_name': 'nt',
 'platform': 'Windows-10-10.0.14393',
 'sys_executable': 'C:\\Python27\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]'}
```

prompt-toolkit 1.0.13

**Comment by Carreau** [comment] 2017-02-07 19:05
Yes we are kinda aware of this. 
This is because there are a slow effort to highlight things using Pygments. Unfortunately:
Old version of pygments do not really support short escape sequences that map your terminal setting. 
And even if Pygments support it, most coloring themes do not use these short escape sequences.

The problem is in these case we can't get the "Correct" color as it depends on the system

![colors](https://cloud.githubusercontent.com/assets/335567/22706745/4afe0692-ed25-11e6-8937-05d10a2105e1.gif)


Marking as "wishlist" as it requires a lot of refactoring to be able to get short escape sequences everywhere.

**Closed** 2017-02-09 19:10 UTC
