### ISSUE TITLE
ipython in terminal freezes on OS X El Capitan

### ISSUE THREAD

**Issue by jtravs** [ipython/ipython#9128] opened 2016-01-12 11:16 UTC
I installed ipython 4.0.1 from macports on OS X El Capitan. The interactive ipython terminal regularly freezes for a while in a way that is reminiscent of what I remember from a few years ago, that I thought was fixed with #6325. It eventually recovers, usually if I focus on another window for a while.

Any ideas? Any more info I can provide to help?

I have matplotlib loaded with the MacOSX backend.

Version info:
```
In [3]: print(IPython.sys_info())
{'commit_hash': u'03b6385',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython',
 'ipython_version': '4.0.1',
 'os_name': 'posix',
 'platform': 'Darwin-15.2.0-x86_64-i386-64bit',
 'sys_executable': '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python',
 'sys_platform': 'darwin',
 'sys_version': '2.7.11 (default, Dec 31 2015, 13:28:45) \n[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]'}
```

**Comment by jtravs** [comment] 2016-01-14 13:45
This seems (but I'm not totally sure) to only occur when I use the left/right cursor keys to edit a line.

**Comment by Carreau** [comment] 2016-01-16 21:20
Hum... the left/right things is purely handled by readline. I'm not sure there is much we can do.

**Comment by jtravs** [comment] 2016-01-16 21:30
I understand, but it is weird that it didn't occur previously.

I tested a few more things: it only occurs when I press and hold left or right cursor (not when I repeatedly hit it), and I can free it by doing Ctrl-e or Ctrl-a etc or repeatedly clicking in and out of the terminal (though this latter way is variably successful).

**Comment by Carreau** [comment] 2016-01-18 01:25
hum... could it be a repetition thing on OS X? or the emoji-pop-up-dialog ?
Terminal.app or iTerm ?

**Comment by mseppa** [comment] 2016-01-26 08:19
I have the same problem after upgrading to El Capitan, both in Terminal.app and in xterm. If I run ipython without --pylab (no OSX backend), the python command line freezes every now and then, but Ctrl+C causes keyboard interrupt and it recovers. With --pylab and matplotlib OSX backend enabled, Ctrl+C does nothing, only killing the process works (or I haven't had the patience to wait long enough).

For me it doesn't require any arrow keys, just normal writing (typically fast) does the trick.

So, for me it seems that there's a problem with the ipython command line (readline?) and it would somehow clash with some other event loop if OSX backend is active ... just guessing ...

**Comment by rrbarbosa** [comment] 2016-02-25 12:00
I might have the same problem. If I press and hold any key (arrows or letters) the input freezes. Although if I hit CTRL+C the input unfreezes, I and can continue to type. The problem only happens if matplotlib is loaded (invoke with `$> ipython --matplotlib` or `%matplotlib` after loading). 

The problem seems related to the Keyboard -> Key Repeat setting in the System Preferences. I only experience the keyboard freeze using the two fastest settings. By setting to the third fastest, the problem goes way (see figure).

![key repeat](https://cloud.githubusercontent.com/assets/807640/13319042/26df4e06-dbbf-11e5-9151-63048949eedd.png)

I running:
Python 3.5.1
IPython 4.0.1
Matplotlib 1.5.1
MacOS 10.11.3

**Comment by mseppa** [comment] 2016-02-25 13:49
Changing the repeat setting didn't help for me.

But meanwhile I have noticed that even with --pylab when the command line freezes, hitting Ctrl-C followed by Enter works. So, now I don't need to kill the whole ipython session anymore and can actually work somehow (although it is still really annoying).

**Comment by leewalsh** [comment] 2016-03-08 21:14
I've been having the same issue for a couple weeks now. I am always able to unlock it by hitting `<CTRL-C>` then `<enter>`. Whatever had been displayed before is in the history, so I can get back to where I was with `<up>`, but my session is littered with:

    In [56]: xy =

    KeyboardInterrupt

    In [56]: xy = vor.points

    In [57]: from scipy.spa
    scipy.spacing  scipy.sparse   scipy.spatial

    In [57]: from scipy.spatial import

    KeyboardInterrupt

    In [57]: from scipy.spatial import Co

    KeyboardInterrupt

    In [57]: from scipy.spatial import ConvexHull

So far, this is all I can gather:

 1. Problem occurs if I run `ipython --pylab` or if I run `ipython` then later run `%matplotlib`, but so far I think not otherwise.

 2. It seems to only happen when I'm typing the start of something defined.  That is, if I jam keys randomly, it is fine, but if I type `np` it can freeze.  This is not so certain, and hard to test since the freezing is inconsistent.  It can happen when hitting `<Tab>` as well, which is especially annoying, since I first think `<Tab>` is doing nothing because I've misspelled something so no completion exists, but it turns out it's frozen, so I have to hit `<CTRL-C><enter><up>`, then `<Tab>` works.

 3. My keyboard repeat rate and delay are both set to the fastest setting. However, holding any keys down or typing randomly really fast do not induce the problem. I also have the problem happen at the settings shown in @rrbarbosa 's image.

Here's all the information that I can think of to provide:

    OS X El Capitan 10.11.3
    iTerm2 Build 2.9.20160206
    IPython 4.0.3
    python 2.7.11
    matplotlib 1.5.1 (backend 'MacOSX')

    IPython.sys_info()
    {'commit_hash': u'8ff8693',
     'commit_source': 'installation',
     'default_encoding': 'UTF-8',
     'ipython_path': '/usr/local/lib/python2.7/site-packages/IPython',
     'ipython_version': '4.0.3',
     'os_name': 'posix',
     'platform': 'Darwin-15.3.0-x86_64-i386-64bit',
     'sys_executable': '/usr/local/opt/python/bin/python2.7',
     'sys_platform': 'darwin',
     'sys_version': '2.7.11 (default, Dec  8 2015, 17:52:46) \n[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)]'}

    os.environ
    {'DISPLAY': '/private/tmp/com.apple.launchd.wh7e6piUqu/org.macosforge.xquartz:0',
     'TERM_PROGRAM': 'iTerm.app',
     'LANG': 'en_US.UTF-8',
     'TERM': 'xterm-256color',
     'XPC_FLAGS': '0x0',
     'XPC_SERVICE_NAME': '0',
     'SHELL': '/usr/local/bin/fish',
     '__CF_USER_TEXT_ENCODING': '0x1F7:0x0:0x0'}

**Comment by dannguyen** [comment] 2016-03-19 01:49
Just wanted to add my input as a OS X 10.11...I thought it was just me. I've been using Anaconda 2.4.0 Python 3.x for more than a year without ever seeing this problem. This week was the first time I started getting back into matplotlib, and every time I startup ipython, I run into it. Like @leewalsh, I'm only able to get out with Ctrl-C.

I'm running ipython without any flags. The hiccups happen as soon as I run the magic command, `%matplotlib`...the freezing will just hit as I'm in the middle of typing out a line of code.

~~~sh
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.3
BuildVersion:	15D21
~~~

~~~py
>>> sys.version
# 3.5.1 |Anaconda 2.4.0 (x86_64)| (default, Dec  7 2015, 11:24:55) 
# [GCC 4.2.1 (Apple Inc. build 5577)]


>>> platform.platform()
'Darwin-15.3.0-x86_64-i386-64bit'

>>> os.uname()
# posix.uname_result(sysname='Darwin', nodename='DN.Net', release='15.3.0', 
# version='Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; 
# root:xnu-3248.30.4~1/RELEASE_X86_64', machine='x86_64')
~~~

**Comment by leewalsh** [comment] 2016-03-24 14:16
I can add another data point. On my laptop running Yosemite I have never encountered this problem. Here are the config for that:

    OS X Yosemite 10.10.5
    iTerm2 Build 2.9.20160206
    IPython 4.1.2
    python 2.7.11
    matplotlib 1.5.1 (backend 'MacOSX')

    IPython.sys_info()
    {'commit_hash': u'b573435',
     'commit_source': 'installation',
     'default_encoding': 'UTF-8',
     'ipython_path': '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython',
     'ipython_version': '4.1.2',
     'os_name': 'posix',
     'platform': 'Darwin-14.5.0-x86_64-i386-64bit',
     'sys_executable': '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python',
     'sys_platform': 'darwin',
     'sys_version': '2.7.11 (default, Mar  4 2016, 21:52:10) \n[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]'}

    os.environ
    {'DISPLAY': '/private/tmp/com.apple.launchd.tLeRVzzJhh/org.macosforge.xquartz:0',
     'TERM_PROGRAM': 'iTerm.app',
     'LANG': 'en_US.UTF-8',
     'TERM': 'xterm-256color',
     'XPC_FLAGS': '0x0',
     'XPC_SERVICE_NAME': '0',
     'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.6adRrWYHww/Listeners',
     'SHELL': '/opt/local/bin/fish',
     '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0'}

**Comment by leewalsh** [comment] 2016-03-24 14:17
@Carreau, lots of information has been provided since you tagged this as `needs-info`. I understand if nobody has had time to look into this, but can you clarify whether we still need more info? If so, what kind of info would be helpful? I am happy to dig further but I don't know where to look. Or maybe do you think it's a matplotlib problem, not ipython?

**Comment by Carreau** [comment] 2016-03-24 16:21
I can remove the `need-info`, but yes, here we really need to figure out why it does that. 
It might be a matplotlib event loop integration issue, but I'm not sure why. 

Has @tacaswell or @minrk seen that and have an idea ? I'm unfamiliar with the event loop code, so the answer might be obvious to one of them, but not for me.

**Comment by tacaswell** [comment] 2016-03-24 16:23
The thing @leewalsh reports with strange inputs may be related to a bug in readline.  Try hitting `ctrl-g` to see if that helps?

**Comment by tacaswell** [comment] 2016-03-24 16:30
And I have been seeing some lockups like this on linux but I do strange things (run IPython terminal inside of emacs) and have not spent any time to track it down further.

**Comment by rhdtownsend** [comment] 2016-04-19 17:53
I experience the same problem on El Cap. It does seem to be an event loop issue; whenever the hang occurs, if I bring the Matplotlib plotting window into focus, that frees up the hang.

**Comment by mseppa** [comment] 2016-04-21 08:03
What @leewalsh listed above describes my experiences pretty accurately too. Just to add, I don't seem to have the freeze if I'm writing a string, i.e. have the quote (") open. So this might be some kind to lookup / auto-complete related thing. Second, it happens only with matplotlib, but I don't need to have a plot window open, or ever opened during the session (yet). Third, taking a long command line from history (up arrow) and then trying to traverse that left/right by holding down the arrow key freezes pretty constanty, but if I hit the key repeatedly if doesn't (typically) freeze.

**Comment by slnovak** [comment] 2016-04-28 18:19
I have the same problem in El Capitan. I found by:

  + running `ctrl-Z` when IPython is unresponsive
  + followed by `fg` to bring the process back to the foreground
  + running `ctrl-C` followed by Enter to generate a `KeyboardInterrupt` exception

is the fastest way to getting back to the interactive prompt. However, IPython becomes unresponsive after a few minutes.

**Comment by tacaswell** [comment] 2016-04-28 20:14
what matplotlib backends is everyone using?  This is starting to sound like issues with `PyOS_InputHook`

**Comment by leewalsh** [comment] 2016-04-28 22:54
Using matplotlib backend: MacOSX

**Comment by tacaswell** [comment] 2016-04-28 22:56
Can you reproduce this with qtagg?

**Comment by rhdtownsend** [comment] 2016-04-28 23:25
Yep, me too…

**Comment by mseppa** [comment] 2016-05-02 07:15
I've been running ipython with Qt4Agg for a while now and there have been no freezes. So, for me it seems to be MacOSX specific problem.

**Comment by carhartl** [comment] 2016-05-02 09:15
I've been seeing that with using matplotlib backend Qt4Agg (running inside a docker container on OSX).

**Comment by leewalsh** [comment] 2016-07-23 02:00
For what it's worth, this issue seems to have disappeared with the magnificent and glorioius `IPython 5.0`. I vote to close.

**Comment by dannguyen** [comment] 2016-07-23 03:04
@leewalsh I won't have time in the next week to properly confirm this but given how abruptly this issue popped up for a specific group of users, I won't at all be surprised if it is obsoleted in 5.0. Thanks for checking it out!

**Comment by takluyver** [comment] 2016-07-23 12:43
Closing - we can reopen it if it turns out it wasn't completely fixed.

**Closed by takluyver** 2016-07-23 12:43 UTC
Labels: needs-info, osx

**Comment by iskandr** [comment] 2017-05-29 17:19
I'm having this problem after upgrading to IPython 6.0 on Yosemite. Since readline got upgraded I'm guessing the problem is there.

**Comment by takluyver** [comment] 2017-05-30 13:51
As we moved away from readline, I'd guess that you're seeing a similar but different problem.

**Comment by iskandr** [comment] 2017-05-30 14:53
Problem goes away with --pylab and with simple prompt. Does that help
narrow down the underlying problem?
