### ISSUE TITLE
crash after attempting tab autocompletion

### ISSUE THREAD

**Issue by biblicabeebli** [ipython/ipython#12753] opened 2021-01-01 19:40 UTC
I've had issues with tab completion in this project.  It uses django and the django_extensions ipython shell integration, but this looks to me like an ipython shell issue.

The pasted blob below includes the input, but what cannot be displayed is that on the second instance of typing out "FileToProcess" the terminal pauses briefly, then continues to allow input, provides no autocompletion, and then crashes when I hit enter.  It does not matter which character in the word "FileToProcess" I am at when I hit tab.

For reference, the codebase I am getting this in is for github.com/onnela-lab/beiwe-backend.  (setup is pretty complex, not expecting anyone to get it working.  I'm happy to help out or run some checks.)  ipython version is 7.16.1, python version Python 3.6.12, Kubuntu linux 20.10, ipython installed through 100% up-to-date pip.

[ipython_crash.txt](https://github.com/ipython/ipython/files/5759350/ipython_crash.txt)

Edit:
I've identified that the last version of ipython that did not cause this issue was ipython 7.1.1.  7.2.0+ exhibit either exactly the reported behavior, or a minor variant involving slightly different allowed typing input to the shell that I'm not really sure how to describe.  (Less laggy?)

**Comment by SerpentByte** [comment] 2021-01-03 02:16
Facing the same issue. I do not use django, but tab auto complete suggestions are not working. While in ipython, using tab does not do anything till I press enter, after which  ipython console crashes saying:
=================================================================================
Traceback (most recent call last):
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 129, in _get_completions
    for c in completions:
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wasim/miniconda3/bin/ipython3", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 564, in mainloop
    self.interact()
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 547, in interact
    code = self.prompt_for_code()
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 473, in prompt_for_code
    text = self.pt_app.prompt(
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 816, in run
    return loop.run_until_complete(
  File "/home/wasim/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 783, in run_async
    return await _run_async2()
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 771, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 872, in cancel_and_wait_for_background_tasks
    await task
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1854, in new_coroutine
    await coroutine(*a, **kw)
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1683, in async_completer
    async for completion in self.completer.get_completions_async(
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 269, in get_completions_async
    async for completion in completer.get_completions_async(
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/home/wasim/miniconda3/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    exc_type, exc_value, exc_tb = sys.exc_info()
NameError: name 'sys' is not defined
=================================================================================

**Comment by nbCloud91** [comment] 2021-01-03 05:12
I am facing the same issue with Ipython version 7.19.0, attaching the detailed trace-back. I do not have this problem with version 7.16.0 though.
[Crash_report_ipython.txt](https://github.com/ipython/ipython/files/5761236/Crash_report_ipython.txt)

**Comment by nbraud** [comment] 2021-01-03 13:25
Same here; the crash only occurs if I import a pure-Python library I'm currently developing, and try to tab-complete anything. Installed versions are:
```
Python 3.9.1 (default, Dec  8 2020, 07:51:42) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.
```

Here is a [testcase] that reproduces the issue with minimal user interaction, an [asciinema] recording of it, and the backtrace:
```
Traceback (most recent call last):
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/IPython/terminal/ptutils.py", line 129, in _get_completions
    for c in completions:
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/IPython/__main__.py", line 14, in <module>
    start_ipython()
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 564, in mainloop
    self.interact()
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 547, in interact
    code = self.prompt_for_code()
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 473, in prompt_for_code
    text = self.pt_app.prompt(
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 816, in run
    return loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 783, in run_async
    return await _run_async2()
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 771, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 872, in cancel_and_wait_for_background_tasks
    await task
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/prompt_toolkit/buffer.py", line 1854, in new_coroutine
    await coroutine(*a, **kw)
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/prompt_toolkit/buffer.py", line 1683, in async_completer
    async for completion in self.completer.get_completions_async(
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/prompt_toolkit/completion/base.py", line 269, in get_completions_async
    async for completion in completer.get_completions_async(
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/tmp/tmp.6pNnhhkjA2/py-nines/.venv/lib/python3.9/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    exc_type, exc_value, exc_tb = sys.exc_info()
NameError: name 'sys' is not defined
```

[testcase]: https://gist.github.com/nbraud/7c7374e2ab266397037c86c4133778be
[asciinema]: https://asciinema.org/a/ZHApL4MoPY9KLu7cl8rfpwm15

**Comment by nbraud** [comment] 2021-01-03 13:29
PS: The issue seems to be resolved on the current `master` branch (as of commit 3587f5bb6c8570e7bbb06cf5f7e3bc9b9467355a)

**Comment by biblicabeebli** [comment] 2021-01-03 17:50
Question 1:
Does the ipython project maintain backported bug fixes for the last supported version of ipython on still-in-support versions of python?

Python 3.6.x is maintained (security patches) "through 2021," according to the 2016 release notes.

I guess I'm a little surprised that 3.6 support was dropped, and with the statement "PR #12410 finally remove support for 3.6," in the ipython 7.17 release notes.  The PR is dated 6 months ago, which is 18 months of 3.6 support remaining.  There could be excellent reasons for this, but to an outsider that seems ... aggressive?

Question 2:
What is the underlying issue here.  ipython is _The Tool_ that I and every python developer I know and work with relies on.  I want to track down whatever it is in my project that is causing this and fix it.

(thanks!)

**Comment by pbregener** [comment] 2021-01-04 10:38
Looks a lot like #12740. Are you running jedi 0.18.0? If so, downgrade to 0.17.2, as a good workaround

**Comment by ksajjan** [comment] 2021-01-04 13:27
Facing same kind of issue. Downgrading `jedi` from `0.18.0` t`o 0.17.2` worked for me.

**Comment by hollyclergyman** [comment] 2021-01-08 11:00
I still get the error in IPython version 7.16.1 while running os and numpy. Is there any hope, there will be a bug fix release in the near future, which will make it to pypy?
Kind regards

**Comment by minrk** [comment] 2021-01-12 10:21
closing as duplicate

**Closed by minrk** 2021-01-12 10:21 UTC

**Comment by shandou** [comment] 2021-06-15 23:57
> Facing same kind of issue. Downgrading `jedi` from `0.18.0` t`o 0.17.2` worked for me.

You saved me a lot of grief!

**Comment by MetRonnie** [comment] 2021-09-07 10:45
I was on ipython 7.19.0 facing this issue. Upgraded to ipython 7.27.0 fixed it
