### ISSUE TITLE
`AsyncResult._ready` is never set when lview.retries > 1

### ISSUE THREAD

**Issue by dhirschfeld** [ipython/ipython#7846] opened 2015-02-24 12:52 UTC
After starting a local cluster it appears that the `AsyncResult._ready` attribute is never set if the `LoadBalancedView.retries` attribute is > 1
```python
In [23]: from IPython.parallel import Client
    ...: rc = Client()
    ...: lview = rc.load_balanced_view()
    ...: 

In [16]: def die():
    ...:    raise Exception("Goodbye cruel world")
    ...:

In [24]: res = lview.apply_async(die)

In [25]: res.r
---------------------------------------------------------------------------Exception                                 Traceback (most recent call last)<string> in <module>()
<ipython-input-16-301b89076dfa> in die()
Exception: Goodbye cruel world

In [26]: lview.retries = 2

In [27]: res = lview.apply_async(die)

In [28]: res.r   # <------------------------------------------------- Hangs Indefinitely!
```

**Comment by dhirschfeld** [comment] 2015-02-24 13:03
```python
In [17]: from IPython import sys_info

In [18]: print sys_info()
{'commit_hash': u'02da130',
 'commit_source': 'installation',
 'default_encoding': 'cp1252',
 'ipython_path': 'C:\\dev\\bin\\Anaconda\\lib\\site-packages\\IPython',
 'ipython_version': '3.0.0-dev',
 'os_name': 'nt',
 'platform': 'Windows-7-6.1.7601-SP1',
 'sys_executable': 'C:\\dev\\bin\\Anaconda\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.5 |Continuum Analytics, Inc.| (default, Jul  1 2013, 12:37:52) [MSC v.1500 64 bit (AMD64)]'}
```

**Comment by minrk** [comment] 2015-02-24 16:56
How many engines do you have? If it's less than the number of retries, the task may be waiting in the scheduler to be assigned to an engine. Engines that fail to run a task are blacklisted for retries of that task, so this will always hang if `retries ≥ n_engines`. If you set a timeout (`lview.timeout = 5`), you should see the result raise an exception that it couldn't find an appropriate engine within the time limit.

There's an open feature request to disable the blacklist behavior, since there are certain kinds of tasks that may fail due to intermittent problems, and it should be fine for one engine to retry the same task.

**Comment by dhirschfeld** [comment] 2015-02-24 17:23
In all cases tested there were only 1 or 2 engines so it sounds like that's what is happening. Thanks for the quick reply - now that I know it's easy enough to work around.

**Comment by dhirschfeld** [comment] 2015-02-24 17:30
Dup of #7368

**Comment by minrk** [comment] 2015-02-24 20:45
Thanks, closing as duplicate of #7368

**Closed by minrk** 2015-02-24 20:45 UTC
Labels: parallel
