### ISSUE TITLE
Adding a matplotlib patch to inline axis twice in a notebook causes offset

### ISSUE THREAD

**Issue by jdugge** [ipython/ipython#8507] opened 2015-06-04 09:50 UTC
(I originally posted this as [a question on Stackoverflow](http://stackoverflow.com/questions/30639284/adding-a-matplotlib-patch-to-inline-axis-twice-in-an-ipython-notebook-causes-off))

I have a matplotlib `patch` that I want to add to two different axis objects. Calling `ax1.add_patch(my_patch)` the first time leads to the correct result, but when I call `ax2.add_patch(my_patch)`, the patch is offset horizontally. Calling `add_patch` again after that does not change the offset.

This only seems to happen when using `%matplotlib inline`. Generating the figures in separate windows does not lead to the offset.

Minimal example:

    import numpy as np
    from matplotlib.patches import Circle
    import matplotlib.pyplot as plt

    %matplotlib inline

    grid = np.ones([10,10])
    circle = Circle((5,5), 2)

    fig1, ax1 = plt.subplots()
    ax1.imshow(grid, interpolation='None')
    ax1.add_patch(circle)

    fig2, ax2 = plt.subplots()
    ax2.imshow(grid, interpolation='None')
    ax2.add_patch(circle)

![image](https://cloud.githubusercontent.com/assets/2399255/7981454/4428cde8-0aaf-11e5-84dd-a1ac1f3f3392.png)

____

System information:

```
'commit_hash': u'cbccb68',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python2.7/dist-packages/IPython',
 'ipython_version': '3.1.0',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-24-generic-x86_64-with-LinuxMint-17-qiana',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.6 (default, Mar 22 2014, 22:59:56) \n[GCC 4.8.2]'
```

`'matplotlib.__version__': '1.4.3'`

**Comment by takluyver** [comment] 2015-06-04 16:44
@tacaswell , your thoughts would be welcome

**Comment by jenshnielsen** [comment] 2015-06-04 16:53
I don't think this relates to the in line backend. You can't reuse an artist in another axis see https://github.com/matplotlib/matplotlib/issues/3776 and it only works by accident. 

The changes by @tacaswell in https://github.com/matplotlib/matplotlib/pull/3835 should make that more obvious that that is not supported. But it is not yet in a release.

**Comment by takluyver** [comment] 2015-06-04 17:35
Thanks. It sounds like this is not a bug, then, so I'll close the issue. We can reopen later if it turns out there is something to fix.

**Closed by takluyver** 2015-06-04 17:35 UTC

**Comment by jdugge** [comment] 2015-06-04 17:47
Ah, that makes sense! Thanks for the clarification

**Comment by tacaswell** [comment] 2015-06-04 17:50
What @jenshnielsen said.
