### ISSUE TITLE
UltraTB Exceptions

### ISSUE THREAD

**Issue by jdtsmith** [ipython/ipython#13615] opened 2022-03-30 16:58 UTC
With the new iPython 3.10.2, I get occasional unexpected Exceptions formatting the tracebacks via `ultratb`, which results in "Falling back to standard exception".

```
Traceback (most recent call last):
  File "/Users/jdsmith/Library/Python/3.10/lib/python/site-packages/IPython/core/interactiveshell.py", line 1982, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/Users/jdsmith/Library/Python/3.10/lib/python/site-packages/IPython/core/ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/jdsmith/Library/Python/3.10/lib/python/site-packages/IPython/core/ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/jdsmith/Library/Python/3.10/lib/python/site-packages/IPython/core/ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/Users/jdsmith/Library/Python/3.10/lib/python/site-packages/IPython/core/ultratb.py", line 818, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "/Users/jdsmith/Library/Python/3.10/lib/python/site-packages/IPython/core/ultratb.py", line 736, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "/Users/jdsmith/Library/Python/3.10/lib/python/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/jdsmith/Library/Python/3.10/lib/python/site-packages/stack_data/core.py", line 698, in lines
    pieces = self.included_pieces
  File "/Users/jdsmith/Library/Python/3.10/lib/python/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/jdsmith/Library/Python/3.10/lib/python/site-packages/stack_data/core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "/Users/jdsmith/Library/Python/3.10/lib/python/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/jdsmith/Library/Python/3.10/lib/python/site-packages/stack_data/core.py", line 628, in executing_piece
    return only(
  File "/Users/jdsmith/Library/Python/3.10/lib/python/site-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0
```

**Comment by Carreau** [comment] 2022-03-31 11:46
Duplicate of #13598

Still trying to figure it out.

**Closed by Carreau** 2022-03-31 11:46 UTC

**Comment by ahcaautoreh** [comment] 2022-05-10 19:03
This also happened to me when I run

```python
import requests

url = 'https://us-street.api.smartystreets.com'
cpath = r"\\networkDrive\path\to\cert.txt"
r = requests.get(url, cert=cpath)
```

Which results in:

```
Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\urllib3\util\ssl_.py", line 418, in ssl_wrap_socket
    context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:4046)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='us-street.api.smartystreets.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(9, '[SSL] PEM lib (_ssl.c:4046)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\IPython\core\interactiveshell.py", line 2737, in safe_execfile
    py3compat.execfile(
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\IPython\utils\py3compat.py", line 55, in execfile
    exec(compiler(f.read(), fname, "exec"), glob, loc)
  File "\\hq3hfsvip01\myusername\Assignments\Standardize Addresses\auxil.py", line 5, in <module>
    r = requests.get(url, cert=cpath)
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='us-street.api.smartystreets.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(9, '[SSL] PEM lib (_ssl.c:4046)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\IPython\core\interactiveshell.py", line 1992, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\IPython\core\ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\IPython\core\ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\IPython\core\ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\IPython\core\ultratb.py", line 818, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\IPython\core\ultratb.py", line 736, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\stack_data\core.py", line 698, in lines
    pieces = self.included_pieces
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\stack_data\core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\stack_data\core.py", line 628, in executing_piece
    return only(
  File "C:\Users\myusername\Anaconda3\envs\myEnvName\lib\site-packages\executing\executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0
```

**Comment by TheMatt2** [comment] 2023-04-20 16:45
This also happens in my code from an assertion in my code.

Relevant code snippet
```
# In module named "utils.py"
# rows = 2
# cols = 4
# len(imgs) = 10
assert max((rows - 1) * cols, rows * (cols - 1)) < len(imgs) <= rows * cols
```

```
Traceback (most recent call last):
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\username\AppData\Local\Temp\ipykernel_15884\1201990211.py", line 1, in <module>
    image_grid(images, 2, 4)
  File "C:\Users\username\path\to\utils.py", line 16, in image_grid
    assert max((rows - 1) * cols, rows * (cols - 1)) < len(imgs) <= rows * cols
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\IPython\core\interactiveshell.py", line 2102, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\IPython\core\ultratb.py", line 1310, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\IPython\core\ultratb.py", line 1199, in structured_traceback
    return VerboseTB.structured_traceback(
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\IPython\core\ultratb.py", line 1052, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\IPython\core\ultratb.py", line 978, in format_exception_as_a_whole
    frames.append(self.format_record(record))
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\IPython\core\ultratb.py", line 878, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\IPython\core\ultratb.py", line 712, in lines
    return self._sd.lines
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\stack_data\core.py", line 698, in lines
    pieces = self.included_pieces
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\stack_data\core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\stack_data\utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\stack_data\core.py", line 628, in executing_piece
    return only(
  File "C:\Users\username\anaconda3\envs\conda-torch\lib\site-packages\executing\executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0
```
