### ISSUE TITLE
SIGWINCH signal not passed to iPython shell

### ISSUE THREAD

**Issue by tkessler45** [ipython/ipython#8469] opened 2015-05-24 19:17 UTC
Apparently the SIGWINCH signal is not handled by iPython, at least when running in the OS X Terminal. This results in odd problems when resizing the Terminal window. For instance, if you run !nano in ipython to launch the nano editor, initially it will load and look appropriate, but if you then resize the window, the nano interface will wrap and stretch, garbling it and preventing it from being usable. This happens for other programs as well when run from within iPython. I'm not too familiar with the underpinnings responsible for this, but in talks with some devs about this, it appears its some mishandling (or lack of handling) of the SIGWINCH signal being sent to ipython from the OS X Terminal. I have not tried this bug in other operating systems, so can only report it happening in OS X, with version 3.1.0 of iPython and running OS X 10.10.3.

**Comment by Carreau** [comment] 2015-05-24 19:38
This is a terminal emulator issue IMHO, OS X "Termianl.app" is relatively bad (and I can reproduce with it). It works (almost) flawlessly in "iTerm.app".

**Comment by takluyver** [comment] 2015-05-24 21:29
From my incomplete understanding of terminal mechanics, SIGWINCH should be sent to the foreground process when you resize the window. While you're running nano, that is the foreground process. Possibly the bug is that Terminal.app is sending the signal to the wrong process.

For lots of details about terminals, see [this article](http://www.linusakesson.net/programming/tty/).

**Comment by minrk** [comment] 2015-05-25 00:32
IPython registers no handlers for SIGWINCH, so the default process behavior of passing signals to children should be happening. When I test it with a different process, I can see that the subprocess is indeed receiving `SIGWINCH`:

```python
# tstwinch.py
import time
import signal

def winch(*a):
    print("\nwinch!")

signal.signal(signal.SIGWINCH, winch)


while True:
    time.sleep(1)
```

IPython:

```python
In [1]: !python tstwinch.py
```


However, I do see that the `COLUMNS` env is set in the subprocess, which could be the cause of the confusion.

@takluyver could this be in pexpect or how we call pexpect?

**Comment by takluyver** [comment] 2015-05-25 04:14
I think the `$COLUMNS` env variable is something bash updates; since you can't change another process' environment variables after starting it, it will be unreliable for long running programs, so I think anything which handles SIGWINCH should use ioctls to check the current size from the terminal itself.

Assuming this is in plain terminal IPython (which is the only way you can use nano, I think), pexpect isn't involved when you do `!nano`. We just call `os.system("nano")`. So I don't see how this could be something we do.

**Comment by minrk** [comment] 2015-05-25 19:45
Right, I forgot about that. Since SIGWINCH is being properly handled as far as I can tell, I'm not sure what the cause could be.

**Comment by tkessler45** [comment] 2015-06-04 21:30
I've been looking at the issue more, and when a terminal session starts up, the iPython shell size is fixed to the current terminal's column number, but then does not resize. If the terminal starts at 80x24, then iPython launches at a fixed 80-column width. It works just fine provided the window remains at 80. If the window is expanded larger than 80, then iPython is still displayed correctly, but its contents still only occupy 80 columns in the upper-left of the window. When in this view, if !nano is run then it only fills out this upper-left view, and not the full view of the resized shell.

Even in these views, when nano is run, the content is rendered correctly (albeit limited to the upper left); however, the problems come when the window is then resized to be smaller, where iPython shows the odd wrapping issues. This happens both when the Terminal window is left at 80-columns, iPython is run, and then the window is resized smaller, and also if iPython is running and you expand the window, then run nano, and then try to make the window smaller again when nano is still running. In both of these cases, the nano window elements get garbles.

This only happens when using iPython.

This issue also affects iPython's line wrapping. When you are at the standard iPython prompt, lines usually wrap to the next line, but if the window is resized to be smaller than the bounds it was when iPython was launched (ie, narrowed from 80 columns to something smaller), then the word wrapping is broken and long entries overlap on same line. This issue seems to be fixed by running !clear, but that should not be needed.

This issue only happens in iPython, and happens regardless of the Terminal emulator being used. I've used three so far: OS X Terminal, iTerm versions 1 and 2, and xterm in XQuartz, and the behavior is consistent among all three.

**Comment by tkessler45** [comment] 2015-06-04 21:35
It may not be SIGWINCH, per se, but something with ipython is causing this issue. If I only run python3 to get to the basic python prompt, and then run os.system("nano"), then nano opens properly and resizing works as expected.

I've not changed anything about iPython, besides creating a startup script to automatically import pandas, os, and some other common libraries.

**Comment by takluyver** [comment] 2015-06-05 00:33
It might be something to do with readline. Do you see a warning about libedit when you start IPython? Do you have [gnureadline](https://pypi.python.org/pypi/gnureadline) installed, and is it up to date.

We really don't do anything special with the terminal ourselves - we're just calling `print()` and `input()`. All the terminal handling is done by readline, so if there's a problem, there's a good chance that's where it is.

**Comment by tkessler45** [comment] 2015-06-05 03:00
I dont see any errors. This is all I see:

------------------------------
Tophers-Retina-MBP:~ tkessler$ ipython
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) 
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: 
------------------------------

Running "pip3 list" shows that gnureadline 6.3.3 is already installed. The problem may be with that package, but I can't tell. Are there other programs that are built in a similar way using this package? If so, I'd like to test them to see if the problem is there.

Otherwise, I'd be happy to send in screencasts, screenshots, and other details if it will help.

**Comment by mvduin** [comment] 2015-06-08 04:43
COLUMNS and LINES should never be in your environment!  Bash provides those shell variables for scripting convenience (and backwards compatibility) but they are normally *not* exported.

Nowadays, programs that care about the terminal size will simply query the kernel (TIOCGWINSZ) after installing a SIGWINCH handler to be notified of changes (if they care). However, for historical reasons, if the terminal size is passed via environment variables, ncurses apps use those values instead of querying the kernel. (Try running `COLUMNS=30 nano` for fun).

> IPython registers no handlers for SIGWINCH, so the default process behavior of passing signals to children should be happening

Signals are never "passed down to children", nor otherwise dependent on handlers installed by the parent (except that SIG_IGN is inherited by child processes). SIGWINCH is delivered to all processes belonging to the foreground process group of the controlling terminal (same as for the SIGINT produced by ctrl-c, etc).

**Comment by minrk** [comment] 2015-06-08 05:37
> COLUMNS and LINES should never be in your environment

I'm not sure what is setting them. It does not appear to be IPython. I guess the shell is setting them itself?

> Signals are never "passed down to children"

Forgive my imprecise language. The fact remains that the process is receiving SIGNWICH without any interference.

**Comment by mvduin** [comment] 2015-06-13 12:44
> I'm not sure what is setting them. It does not appear to be IPython. I guess the shell is setting them itself?

The shell will set/update the variables, but not export them by default. That will most likely be due to some crufty bashrc/profile content left over from Ye Olden Days. The line you need to hunt for is probably
```sh
eval `resize`
```
since this was the customary way to set those environment variables back in the days when terminals did not spontaneously change size (except perhaps due to defenestration). If the offending line can't be easily found, a workaround would be to explicitly unexport the variables with
```sh
export -n LINES COLUMNS
```

**Comment by awelkie** [comment] 2015-12-03 01:23
It looks like this is an issue with `readline`. See this bug report for details:

https://bugs.python.org/issue23735

**Comment by takluyver** [comment] 2016-01-16 21:45
Closing for now as I don't think there's anything to be fixed in IPython. It will still be possible to add comments if anyone wants to investigate causes and solutions further.

**Closed by takluyver** 2016-01-16 21:45 UTC
Labels: needs-info

**Comment by brbsix** [comment] 2016-01-27 10:19
I've been dealing with this as well. The following fixed it:

    easy_install-2.7 --install-dir ~/.local/lib/python2.7/site-packages/ readline
    easy_install-3.4 --install-dir ~/.local/lib/python3.4/site-packages/ readline

Note I am on a Debian derivative. For whatever reason (I didn't look into it), installation via `pip` did not work, but `easy_install` did. This fixed the issue in both Python and IPython shells. Here is a link to the [readline](https://pypi.python.org/pypi/readline) package. It is deprecated v6.4.2.1, which AFAIK is the last working version before major changes were made.
