### ISSUE TITLE
Can ipython-notebook(jupyter) support "CMD" in windows?

### ISSUE THREAD

**Issue by Coldmooon** [ipython/ipython#8604] opened 2015-07-03 09:01 UTC
`Bash` in linux has been supported by `ipython-notebook`. I can run linux commands in a webpage. However, in Windows,  it seems that `CMD` is not supported by `ipython-notebook` yet. The `Terminals` button under `New` tag is grey.

Is there any way to run Windows commands in a notebook's webpage?

**Comment by Carreau** [comment] 2015-07-03 13:14
Duplicate of jupyter/notebook#172  (this is not really IPython specific).

No it's not possible as Windows does not support TTY. We "just" use an external lib called terminado . I suppose someone could implement a similar project to terminado for windows, but I have no idea how.
If you find such lib though, you can tell us, but we most likely won't implement such a thing.

**Closed by Carreau** 2015-07-03 13:14 UTC

**Comment by Coldmooon** [comment] 2015-07-03 13:22
Ah~ I see. Thank you very much~~

**Comment by jonrobinson2** [comment] 2015-07-07 17:21
Do you guys think the babun project offers any hope? I have it installed and it lets me run both bash and zsh commands in this shell that is basically souped up cygwin. I'm not super technically well versed in the building of the notebooks, etc but thought at least it would be worth garnering a response?

http://babun.github.io/

**Comment by takluyver** [comment] 2015-07-07 17:58
It looks like the terminal part of that is mintty. The man page for that says:

> mintty communicates with the child process through a pseudo terminal device, which Cygwin emulates using Windows pipes. This means that native Windows command line programs started in mintty see a pipe rather than a console device

That doesn't sound like it will work terribly well, and a solution that involves installing Cygwin isn't very satisfactory anyway.

I'm hoping that [midipix](http://www.midipix.org/) might eventually make things better on Windows, but I don't think it's an immediate solution.

**Comment by kiwirob** [comment] 2016-03-31 18:35
Presumably Microsoft's [recent announcement](http://www.theverge.com/2016/3/30/11331014/microsoft-windows-linux-ubuntu-bash) that it's bringing bash to Windows 10 will make this possible at some point in the near future.

**Comment by takluyver** [comment] 2016-03-31 21:51
I'm not exactly clear on how that will work - Microsoft is bringing an entire Linux userspace to Windows. If I had to guess, I'd imagine that terminals will work if you install Python and the notebook within the Linux environment, but not if you install them natively in Windows. I really don't know, though - we'll have to wait and see what is possible.

**Comment by Dev-python-etc** [comment] 2020-11-10 06:01
Yes. Example
# bash
cat mvideo_spider.py
# windows
!type mvideo_spider.py
