### ISSUE TITLE
notebook: os x matplotlib figure close button causes freeze

### ISSUE THREAD

**Issue by John-Colvin** [ipython/ipython#8666] opened 2015-07-27 16:32 UTC
This is with the matplotlib MacOSX backend on OS X 10.11 beta2. I am creating an issue here because this only happens from the notebook, not from the ipython shell or vanilla python shell

Steps to reproduce:
* plot using matplotlib by any method (e.g. pylab)
* close the figure window by clicking the x in the corner

the UI of that figure is then permanently frozen, won't resize and none of the buttons work, spinning beach ball of death constantly on mouse-over, but the content still changes if e.g. another call to plot is made.

If, instead of using the x button, the figure was closed programmatically by e.g. ```close('all')``` then it closes properly.

Once the UI is frozen, the only way out is to kill python (force-quit, or actual ```kill -9```), commands like ```close('all')``` have no effect.

**Comment by minrk** [comment] 2015-07-27 16:38
@John-Colvin have you done `%matplotlib`? That is typically necessary to avoid matplotlib blocking the eventloop.

**Comment by John-Colvin** [comment] 2015-07-27 16:45
If %matplotlib or %pylab are used then the event loop is not blocked, as usual (hence me being able to change content by plotting again). Without the magics the event loop is of course still blocked.

The problem is that the plot window itself has frozen, the notebook itself is unaffected.

**Comment by minrk** [comment] 2015-07-27 16:48
And what backend are you using?

**Comment by John-Colvin** [comment] 2015-07-27 16:50
as mentioned above, the MacOSX backend

**Comment by minrk** [comment] 2015-07-27 16:51
And matplotlib version?

**Comment by John-Colvin** [comment] 2015-07-27 16:53
Sorry, should have included that: matplotlib 1.4.3

**Comment by minrk** [comment] 2015-07-27 17:06
Do you have access to a machine with 10.10 stable? I've just run the above steps on:

- OS X 10.10.4
- Python 3.4.3
- matplotlib 1.4.3
- IPython 3.2.1 (all via conda)

and closing the figure with the x closed the figure as expected. This may be an issue with 10.11. What are your Python and IPython versions, and how are you installing packages?

**Comment by John-Colvin** [comment] 2015-07-27 18:06
Don't have access to a 10.10 box right now, sorry.

python 3.4.3 via homebrew
matplotlib 1.4.3 via homebrew
Ipython 3.2.1 via pip

**Comment by tacaswell** [comment] 2015-07-31 21:17
attn @mdehoon 

Does this happen with any other backend?

**Comment by ianlcassidy** [comment] 2015-11-09 21:38
Has any progress been made on this topic?  I just updated my os x version from 10.10 to 10.11 and this started happening to me.  Here is what I am using:

python 2.7.10 (virtual environment)
matplotlib 1.4.3 via pip
ipython 4.0.0 via pip

**Comment by ianlcassidy** [comment] 2015-11-25 03:05
not sure if anyone is still following this ticket, but i found a fix.  installing qt (and pyside) and then using the command "%matplotlib qt" opens a window that can now be closed.

**Comment by mdehoon** [comment] 2015-11-25 04:17
Does Tkinter work from the notebook? If you do
```python
>>> from Tkinter import *
>>> Tk()
```
does the Tk window appear and function correctly (e.g. resizing, closing)?

**Comment by ianlcassidy** [comment] 2015-11-25 14:20
@mdehoon as far as i can tell Tkinter is working in my ipython notebook environment (i've never used it before).  i ran through some of the examples in the link below and had not problem with resizing or closing the window.
https://wiki.python.org/moin/Intro%20to%20programming%20with%20Python%20and%20Tkinter

**Comment by mdehoon** [comment] 2015-11-26 02:25
@ianlcassidy  OK, thanks. Have you tried if this bug still appears with the latest version of matplotlib (1.5.0)?

**Comment by ianlcassidy** [comment] 2015-11-27 03:14
@mdehoon yes, the bug appears on v1.5.0 of matplotlib.

**Comment by mdehoon** [comment] 2015-11-27 14:08
@ianlcassidy  How did you get a framework build of Python? Did you follow the guidelines here: http://matplotlib.org/1.5.0/faq/virtualenv_faq.html#osx  ?

**Comment by ianlcassidy** [comment] 2015-11-29 01:29
@mdehoon no, i just built a virtual environment and then pip installed several packages (including numpy, scipy, ipython, etc.).  i can try to setup another virtual environment and follow some of the steps in the link above.  it's strange that everything was fine with os x 10.10, but then this issue started occurring with os x 10.11.

**Comment by mdehoon** [comment] 2015-11-29 07:11
@ianlcassidy  Thank you. Actually I have not been able to reproduce this bug with either 10.10 or 10.11. Also, if your python is not a framework build, then the backend will have other problems as well. For example, clicking the Save button to save the figure to a file will bring up the Save dialog window, but it won't let you edit the file name. With matplotlib 1.5.0, the backend should have warned you that Python is not built as a framework. It may be that the Python you are running is different from what you think it is, or that a different installation of matplotlib is being imported than the intended one. Are you able to compile matplotlib? Then we can check exactly what is going wrong.

**Comment by takluyver** [comment] 2016-01-26 16:11
Closing as it's probably not an IPython bug; feel free to keep using the comments for troubleshooting. We can reopen if it turns out there is something for us to do.

**Closed by takluyver** 2016-01-26 16:11 UTC
Labels: needs-info
