### ISSUE TITLE
Catch KeyboardInterrupt during startup

### ISSUE THREAD

**Issue by anntzer** [ipython/ipython#9730] opened 2016-07-09 23:50 UTC
Currently, `Ctrl-C` while IPython is starting leads to a huge traceback.
```
$ ipython
^CTraceback (most recent call last):
  File "/usr/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-109>", line 2, in initialize
  File "/usr/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 309, in initialize
    self.init_shell()
  File "/usr/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 325, in init_shell
    ipython_dir=self.ipython_dir, user_ns=self.user_ns)
  File "/usr/lib/python3.5/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 359, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 498, in __init__
    self.init_magics()
  File "/usr/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 342, in init_magics
    super(TerminalInteractiveShell, self).init_magics()
  File "/usr/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2011, in init_magics
    m.NamespaceMagics, m.OSMagics, m.PylabMagics, m.ScriptMagics,
  File "/usr/lib/python3.5/site-packages/IPython/core/magic.py", line 387, in register
    m = m(shell=self.shell)
  File "/usr/lib/python3.5/site-packages/IPython/core/magics/script.py", line 111, in __init__
    self._generate_script_magics()
  File "/usr/lib/python3.5/site-packages/IPython/core/magics/script.py", line 122, in _generate_script_magics
    cell_magics[name] = self._make_script_magic(name)
  File "/usr/lib/python3.5/site-packages/IPython/core/magics/script.py", line 130, in _make_script_magic
    @script_args
  File "/usr/lib/python3.5/site-packages/IPython/core/magic_arguments.py", line 209, in __call__
    func.parser = construct_parser(func)
  File "/usr/lib/python3.5/site-packages/IPython/core/magic_arguments.py", line 156, in construct_parser
    magic_func.__doc__ = parser.format_help()
  File "/usr/lib/python3.5/argparse.py", line 2342, in format_help
    return formatter.format_help()
  File "/usr/lib/python3.5/argparse.py", line 278, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.5/argparse.py", line 209, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.5/argparse.py", line 209, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.5/argparse.py", line 208, in format_help
    func(*args)
  File "/usr/lib/python3.5/argparse.py", line 516, in _format_action
    help_lines = self._split_lines(help_text, help_width)
  File "/usr/lib/python3.5/argparse.py", line 616, in _split_lines
    return _textwrap.wrap(text, width)
  File "/usr/lib/python3.5/textwrap.py", line 380, in wrap
    return w.wrap(text)
  File "/usr/lib/python3.5/textwrap.py", line 352, in wrap
    chunks = self._split_chunks(text)
  File "/usr/lib/python3.5/textwrap.py", line 338, in _split_chunks
    text = self._munge_whitespace(text)
  File "/usr/lib/python3.5/textwrap.py", line 155, in _munge_whitespace
    text = text.expandtabs(self.tabsize)
KeyboardInterrupt

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

Exception ignored in: <bound method ScriptMagics.__del__ of <IPython.core.magics.script.ScriptMagics object at 0x7f7f5722f400>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/IPython/core/magics/script.py", line 117, in __del__
  File "/usr/lib/python3.5/site-packages/IPython/core/magics/script.py", line 249, in kill_bg_processes
AttributeError: 'ScriptMagics' object has no attribute 'bg_processes'
```

It would be nice if IPython just exited cleanly (possibly with return code 1, I don't really care) when that happens.

**Comment by takluyver** [comment] 2016-07-10 10:40
Not convinced about that one - if something hangs, being able to get a traceback by interrupting it is really useful. I don't think we should hide tracebacks in general unless we're really sure they're not helpful.

**Comment by minrk** [comment] 2016-07-10 22:59
The same is true of Python itself - you can interrupt interpreter startup, and you will get KeyboardInterrupt tracebacks showing in weird spots.

Alternately, we could register the IPython crash handler only for non-interrupt exceptions, in which case you would see the regular traceback, but not the bing "IPython crashed" message in this case.

**Comment by anntzer** [comment] 2016-07-10 23:21
The difference is that CPython startup is essentially instantaneous (you *can* trigger a traceback if you ctrl-c at the right time but it's not so easy; and even then the traceback is relatively short).
Still, I don't feel very strongly either way, feel free to close this.

**Comment by Carreau** [comment] 2016-07-19 22:59
Let's ask for @fperez advice. We can close/refine depending on his advice.

**Comment by fperez** [comment] 2016-07-19 23:29
Wow, our startup times have really become gigantic...  I had a vague sense they were creeping up, but with systems getting faster and SSDs, it still felt OK.  But now the ratio with the Python startup time is pretty awful:

```
Kerbin[profile_default]> time ip -c "'None'"

real	0m1.175s
user	0m0.890s
sys	0m0.068s
Kerbin[profile_default]> time python -c None

real	0m0.035s
user	0m0.025s
sys	0m0.008s
```

But that aside, I wouldn't bother with this, making  our exception handling logic more complicated for a truly odd corner case.  Besides, even if you trigger the base exception handler before ours is in place, the TB isn't that tiny: our stack is just big, period... So I don't see the cost/benefit ratio here making it worthwhile...

Let's close this as-is, at least it documents the issue, and thanks @anntzer for reporting!

**Closed by fperez** 2016-07-19 23:29 UTC

**Comment by Carreau** [comment] 2016-07-19 23:41
No it's a `pygments.style` slowdown xonsh, and in general PKT suffer from too... and the root cause seem to be somewhere in setuptools `https://github.com/pypa/setuptools/issues/510`. 

Xonsh load pygments in [a thread](https://github.com/xonsh/xonsh/pull/1359) to avoid that which is 100x faster in some cases.

**Comment by takluyver** [comment] 2016-07-20 11:35
Yet another problem which turns out to be setuptools :angry:

**Comment by takluyver** [comment] 2016-07-20 11:48
OK, it looks like only ~0.15s is the setuptools issue. That's significant, but it's still over 1s on my system with Anthony Scopatz's `sys.modules['pkg_resources'] = None` trick.

I did some tests on startup time in switching from readline to PTK, as I was concerned that loading so many modules might impact startup time, and found that it was actually slightly quicker than loading the readline extension module.
