### ISSUE TITLE
Docs: "Edit on GitHub" button is broken

### ISSUE THREAD

**Issue by kolibril13** [ipython/ipython#12903] opened 2021-04-11 09:10 UTC
![image](https://user-images.githubusercontent.com/44469195/114298372-596d6900-9ab6-11eb-97b7-7298a26507e7.png)
https://ipython.readthedocs.io/en/latest/api/generated/IPython.display.html
When I click this button, I land here:
![image](https://user-images.githubusercontent.com/44469195/114298387-75710a80-9ab6-11eb-8c8d-1819efbb5c28.png)
This is also the case for other versions of the docs

**Comment by MrMino** [comment] 2021-04-11 11:13
Thanks for taking the time to report it. I'm going to close it, as it's a duplicate of #11919. If you have any questions / would like to work on it - please discuss it there.

**Closed by MrMino** 2021-04-11 11:13 UTC
