### ISSUE TITLE
Simplify colors configuration (was Ability to pass a pygments style class)

### ISSUE THREAD

**Issue by memeplex** [ipython/ipython#9749] opened 2016-07-13 10:10 UTC
Add the ability to set the highlighting style by class. Extending pygments is cumbersome: it requires modification of the installed package or installing a package in order to register an entrypoint. Both methods are too much for a user wanting to customize colors. For example, I would like to use the base16 pygments styles available on the web by just downloading one of them from github and dropping it into my ipython configuration folder. If highlighting_style could be either a name or a class, life would be simpler and the required change to ipython in order to do that is trivial. Currently I'm monkey patching get_style_by_name, which is ugly.

**Comment by memeplex** [comment] 2016-07-13 19:31
This is what I'm currently doing to get a nice custom base16 theme:

```
from base16 import Base16Style, GREEN, RED
from pygments import styles
from pygments.token import Token

def get_style_by_name(name, original=styles.get_style_by_name):
    return Base16Style() if name == 'base16' else original(name)
styles.get_style_by_name = get_style_by_name

c.TerminalInteractiveShell.highlighting_style = 'base16'
c.TerminalInteractiveShell.highlighting_style_overrides = {
    Token.Prompt: GREEN,
    Token.PromptNum: '%s bold' % GREEN,
    Token.OutPrompt: RED,
    Token.OutPromptNum: '%s bold' % RED
}
```

It's far from ideal:

1. I'm monkey patching `get_style_by_name` to avoid either modifying the pygments installation or going all the setuptools way just to register an entrypoint.
2. I need to define 4 overrides because ipython is being too liberal in defining its own colors.

Regarding 1 I proposed a simple solution: to allow `c.TerminalInteractiveShell.highlighting_style = Base16Style` or even `
c.TerminalInteractiveShell.highlighting_style = Base16Style()`.

The second issue is a bit more difficult but I think ipython should either:

a. strive to use the standard pygments token colors, or
b. at least honour the terminal emulator palette as before.

Currently ipython is being inconsistent both with my terminal color settings and with my highlighting settings (both base16 default). There is the `overrides` hook but a more consistent default behavior will simplify configuration a lot. Ideally I would like to reduce the above code to:

```
from base16 import Base16Style

c.TerminalInteractiveShell.highlighting_style = Base16Style()
```

and still expect a reasonably consistent appearance.

**Comment by memeplex** [comment] 2016-07-13 22:15
Recognizing that it's not that easy to fix point 2, since there are many prompt toolkit specific colors, I decided to implement a template for base16 that works out of the box for the combo ipython+pygments+prompt_toolkit and closely matches the vim base16 theme.

I have simplified, sorted and updated the template at https://github.com/idleberg/base16-pygments to match vim theme and added ipython specific styles (paren matching, completion menu, prompts, etc.). [Here](https://gist.github.com/memeplex/0088a470036786bea54b43a1f2db2b80) is the output for  base16-default together with the required ipython configuration (simpler but still needs the monkey patching :().

I will be testing and fixing this one for a couple of weeks and then I will add the template to the base16 suite. The beauty of this approach is that out-of-the-box ipython will get dozens of consistent, term-friendly themes.

Last but not least, here is an ![screenshot](https://gist.github.com/memeplex/0088a470036786bea54b43a1f2db2b80).

**Comment by Carreau** [comment] 2016-07-19 23:08
Hi there, Sorry we were at scipy last week. 

Simplifying color handling is definitely the kind  of things we'd like to do, but we likely want to uniformize how color are used across the IPython codebase. In particular in the debugger and UltraTB. 
I hope to make the coloring of the tracback simpler in a later version one we move our codebase to python3 only, as we will be able to `yield from` pais of (Token, types) instead of the decade old system that does string formatting manually. 

> The second issue is a bit more difficult but I think ipython should either:

> a. strive to use the standard pygments token colors, or
> b. at least honour the terminal emulator palette as before.

Yes we are aware of this one, and it is fix in pygments master, the issue is that pygments used to only emit extended ansi escape sequence, and was not allowing to create themes with short ansi names. 
The other issue is that pygments has no themes that use these short escape sequences. There is an common agreement among the xonsh/ipython/prompt_toolkit developers, that we should do something  about that an unify the stack. 

It is not too hard to do, but require quite a bit of cleanup work. 

If you want to submit a PR that does some of that, or are interested in this, we would be happy to help you.

**Comment by Carreau** [comment] 2016-07-19 23:08
Sidenote, marking as wishlist, as this is likely long term ground work, whic is not really bloking but woudl be nice to have.

**Comment by memeplex** [comment] 2016-07-26 17:00
@Carreau for the time being I would like to submit a PR that just allows `highlighting_style` to be a string or a class, to avoid the cumbersome procedures extending pygments requires, which I described in my first comment. Is that ok?

**Comment by Carreau** [comment] 2016-07-28 16:44
> @Carreau for the time being I would like to submit a PR that just allows highlighting_style to be a string or a class, in order to avoid the cumbersome procedures extending pygments requires, which I described in my first comment. Is that ok?

I think that would be ok. You would have to change the traitlets to be either Type, or DottedObjectName, I would have to verify that. We have to check how much complexity added there is.

**Comment by memeplex** [comment] 2016-08-07 17:29
@Carreau I've submitted a PR, there is not much added complexity IMO.

**Closed** 2016-08-23 23:59 UTC

**Comment by memeplex** [comment] 2018-03-13 18:04
How is the process to port this to jupyter console? Should I just create an issue there and reference this one? I'm afraid a number of potentially common improvements are being lost in the way. Is there any periodic merging process of both projects?

**Comment by memeplex** [comment] 2018-03-13 18:08
Well I'm still interested in the methodological approach but, for the time being, I already created a new issue: https://github.com/jupyter/jupyter_console/issues/154
