### ISSUE TITLE
ANSI escape sequence visible after first command

### ISSUE THREAD

**Issue by cbrnr** [ipython/ipython#11363] opened 2018-10-05 07:44 UTC
This seems to have been introduced with version 7. If I start IPython and type in a command (doesn't matter which one), the next prompt (`In [2]:` ) is prepended with the characters `^[[35;1R`. After that, all subsequent prompts look normal.

```
{'commit_hash': '3772d25df',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.7/site-packages/IPython',
 'ipython_version': '7.0.1',
 'os_name': 'posix',
 'platform': 'Darwin-18.0.0-x86_64-i386-64bit',
 'sys_executable': '/usr/local/opt/python/bin/python3.7',
 'sys_platform': 'darwin',
 'sys_version': '3.7.0 (default, Sep 18 2018, 18:47:08) \n'
                '[Clang 10.0.0 (clang-1000.10.43.1)]'}
```

**Comment by Carreau** [comment] 2018-10-08 15:11
Duplicate of #11336

**Closed by Carreau** 2018-10-08 15:11 UTC
