### ISSUE TITLE
%matplotlib tk broken

### ISSUE THREAD

**Issue by fariza** [ipython/ipython#9005] opened 2015-11-21 14:04 UTC
With a default installation of latest ipython (`sudo pip3 install ipython`), the magic command to activate tk in matplotlib fails as following

`gtk3` works fine

```
Python 3.5.0+ (default, Oct 11 2015, 09:05:38) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: %matplotlib tk
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-d21727ff1c11> in <module>()
----> 1 get_ipython().magic('matplotlib tk')

/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
   2334         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2335         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2336         return self.run_line_magic(magic_name, magic_arg_s)
   2337 
   2338     #-------------------------------------------------------------------------

/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
   2255                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2256             with self.builtin_trap:
-> 2257                 result = fn(*args,**kwargs)
   2258             return result
   2259 

/usr/local/lib/python3.5/dist-packages/IPython/core/magics/pylab.py in matplotlib(self, line)

/usr/local/lib/python3.5/dist-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):

/usr/local/lib/python3.5/dist-packages/IPython/core/magics/pylab.py in matplotlib(self, line)
     98             print("Available matplotlib backends: %s" % backends_list)
     99         else:
--> 100             gui, backend = self.shell.enable_matplotlib(args.gui)
    101             self._show_matplotlib_backend(args.gui, backend)
    102 

/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py in enable_matplotlib(self, gui)
   3118         """
   3119         from IPython.core import pylabtools as pt
-> 3120         gui, backend = pt.find_gui_and_backend(gui, self.pylab_gui_select)
   3121 
   3122         if gui != 'inline':

/usr/local/lib/python3.5/dist-packages/IPython/core/pylabtools.py in find_gui_and_backend(gui, gui_select)
    241     if gui and gui != 'auto':
    242         # select backend based on requested gui
--> 243         backend = backends[gui]
    244     else:
    245         # We need to read the backend from the original data structure, *not*

KeyError: 't'

In [2]: 

```

**Comment by Carreau** [comment] 2015-11-23 12:57
likely fixed by #8985, I suppose `cd ..` is broken too ?

**Comment by takluyver** [comment] 2016-01-26 12:05
Closing as we believe it's fixed (fix should be in 4.0.1). Reopen if it can be reproduced with more recent versions of IPython.

**Closed by takluyver** 2016-01-26 12:05 UTC

**Comment by schiravuri** [comment] 2017-04-25 11:18
Hi, I just started going through Brandon Rhodes tutorials from PyCon 2015. I'm running into the that @fariza brought up. 

My iPython notebook version is 

![image](https://cloud.githubusercontent.com/assets/5534738/25382833/4899f08e-2987-11e7-9ae8-1a07fc3e52f5.png)


Not sure what the issue is.

**Comment by Carreau** [comment] 2017-04-25 16:56
`import IPython` should be done as the python or IPython prompt, not at the command prompt. 
You can distinguish them easily: usually Python prompt stars with a `>>>`, IPython `In[n]:`, while command prompt start with a Single `>` on windows and usually a `$` on Mac/Linux
