### ISSUE TITLE
ipython MUST preserve order of keys while showing the contents of a dict

### ISSUE THREAD

**Issue by socketpair** [ipython/ipython#11013] opened 2018-02-17 21:36 UTC
```
In [1]: qwe = {1:2, 3:4}

In [2]: asd = {3:4, 1:2}

In [3]: qwe
Out[3]: {1: 2, 3: 4}

In [4]: asd
Out[4]: {1: 2, 3: 4}

In [5]: list(asd.items())
Out[5]: [(3, 4), (1, 2)]

In [6]: list(qwe.items())
Out[6]: [(1, 2), (3, 4)]
```

Since Python 3.6 order of dict items is always preserved.

**Comment by ivanov** [comment] 2018-02-23 01:51
Hi @socketpair - thanks for your report. @takluyver took care of this in #10958 and it will be released in the next version of IPython (both 6.3 and 5.6). I am closing this report as a duplicate of #10110.

Happy hacking! :bowtie:

**Closed by ivanov** 2018-02-23 01:51 UTC
