### ISSUE TITLE
Can’t enter newline, Enter always executes

### ISSUE THREAD

**Issue by rdaysky** [ipython/ipython#11448] opened 2018-10-25 16:00 UTC
I type: `def f():` **Enter** `x=1` **Enter**

I expect:
```
def f():
    x=1
    | <cursor here to continue defining the function>
```

Instead the second Enter executes the def statement, preventing me from defining a multi-line function. The same is true for if, for, while etc. Alt+Enter, Esc Enter, ^v ^j don’t help.

IPython 7.0.1
Ubuntu 16.04.5 LTS

**Comment by Carreau** [comment] 2018-10-25 17:15
Duplicate of #11428, #11443, #11395, #11413... and a few other.

**Closed by Carreau** 2018-10-25 17:15 UTC
