### ISSUE TITLE
Some matplotlib backends on MacOS significantly slow down jupyter

### ISSUE THREAD

**Issue by yluthu** [ipython/ipython#11602] opened 2019-02-11 12:21 UTC
On my MacOS Mojave system, enabling some matplotlib backends will significantly slow down the execution of subsequent cells (the slowdown starts to occur about half a minute after setting the backend). See the screenshot below for an example (notice the 10.0s execution time of the third cell):

![image](https://user-images.githubusercontent.com/3724995/52561258-d4cf2380-2e35-11e9-9585-4ea3abdcf42b.png)

In particular, I notice that the 10.0s consists of three "stages":
1. After I tell jupyter to run the cell, the kernel stays idle for a few seconds;
2. The kernel becomes busy, and the output immediately appear;
3. The kernel stays busy for another few seconds after the output appears.

I've tested with different matplotlib backends, and the issue happens when using some of the backends. Here is a summary:

- Backends that make this issue happen:
    - `osx`
    - `qt`
- Backends that do NOT make this issue happen:
    - `inline`
    - `agg`
    - `tk`
    - `nbagg`
    - `notebook`

I've also tested with different ipython/jupyter clients, and the issue happens when using some of the clients. Here is a summary:

- Clients where this issue happens:
    - `jupyter notebook`
    - `jupyter console`
    - `jupyter qtconsole`
    - `jupyter lab`
    - Nteract app
- Clients where this issue does NOT happen:
    - `ipython` console

When tested in `jupyter console`, an additional warning is cast when executing the third line in the screenshot above:

```
/usr/local/lib/python3.7/site-packages/jupyter_console/ptshell.py:661: UserWarning: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.
  warn('The kernel did not respond to an is_complete_request. '
```

I have tried to dig into the source code of `IPython.core.pylabtools.activate_matplotlib`, and here is a minimal (to my best) example:

```
$ jupyter console
Jupyter console 6.0.0

Python 3.7.2 (default, Jan 13 2019, 12:50:01)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.



In [1]: import matplotlib

In [2]: matplotlib.rcParams['backend'] = 'MacOSX'

In [3]: import matplotlib.pyplot

In [4]: import time

In [5]: time.sleep(35)

In [6]: 'test'    # this line will take a lot of time
/usr/local/lib/python3.7/site-packages/jupyter_console/ptshell.py:661: UserWarning: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.
  warn('The kernel did not respond to an is_complete_request. '
Out[6]: 'test'
```

My system information that might be relevant:

```
$ python3 -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '523ed2fe5',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.7/site-packages/IPython',
 'ipython_version': '7.2.0',
 'os_name': 'posix',
 'platform': 'Darwin-18.2.0-x86_64-i386-64bit',
 'sys_executable': '/usr/local/opt/python/bin/python3.7',
 'sys_platform': 'darwin',
 'sys_version': '3.7.2 (default, Jan 13 2019, 12:50:01) \n'
                '[Clang 10.0.0 (clang-1000.11.45.5)]'}

$ pip3 freeze | grep 'jupyter\|matplotlib'
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
matplotlib==3.0.2
```

Thanks!

**Comment by faultdiagnosistoolbox** [comment] 2019-05-12 10:21
I have exactly the same issue. It is annoying since the osx backend is the only one producing retina quality plots. With , e.g., TkAgg it all works but plots look blurry.

I really hope someone who knows what to do picks this up!

**Comment by yluthu** [comment] 2019-05-12 17:28
@faultdiagnosistoolbox My workaround is switching to the inline backend and setting the output format of matplotlib as SVG. This way we can get high-resolution plots without using the osx backend.

> I have exactly the same issue. It is annoying since the osx backend is the only one producing retina quality plots. With , e.g., TkAgg it all works but plots look blurry.
> 
> I really hope someone who knows what to do picks this up!

**Comment by faultdiagnosistoolbox** [comment] 2019-06-22 07:49
Thank you for your reply (and sorry for my late response). I'm not sure that I understand your work-around though. If I set the backend to inline, I still get blurry (but inline) figures. I hope there is a solution, I prefer interactive figures where I can zoom and pan.

When saving, I normally save my figures as PDF and they look good.

I am a little surprised about this, I find very little online on this topic (your excellent summary above is the notable exception). Does this not affect everyone with high resolution displays?

**Comment by tacaswell** [comment] 2019-06-22 15:50
@faultdiagnosistoolbox Qt5Agg will also produce hi-dpi windows.  The issue with Tk is that, to my knowledge, the toolkit does not support hi-dpi and can not opt out of OSX's "zooming" effect (which is in place to prevent things from being tiny instead).

The issue here is that the input hook is getting jammed.  For the GUI to be responsive, the GUI event loop needs to be run while IPython waits for input from the human.  Something is going wrong with that hand-off and (I suspect) the event loop is not yielding control back to let your code run.

**Comment by faultdiagnosistoolbox** [comment] 2019-06-22 18:20
Thank you! A quick (non-extensive) initial test seems promising for me. Not sure yet what you mean by the "zooming" effect; but I will try this backend out for a while.

**Comment by vishakadsg** [comment] 2019-08-23 21:25
I run Mac OS X Mojave and experience the exact same issue. The same workaround, i.e., changing backend to Agg fixes the delay. I've experienced the lag with the Qt back-end even with command auto-completions and in bringing up the documentation for functions.

**Comment by impact27** [comment] 2019-09-21 19:32
I think this is caused by AppNap: https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/AppNap.html
This can be desactivated by https://pypi.org/project/appnope/

**Comment by impact27** [comment] 2020-12-11 10:44
I think this issue can be closed as it was solved by https://github.com/ipython/ipykernel/pull/441

**Comment by ccordoba12** [comment] 2020-12-11 12:40
Ok, closing then.

**Closed by ccordoba12** 2020-12-11 12:40 UTC
