### ISSUE TITLE
testfailures in IPython.kernel

### ISSUE THREAD

**Issue by jstenar** [ipython/ipython#3721] opened 2013-07-22 07:43 UTC
I get three test failures in IPython.kernel on 200133d

	ERROR: IPython.embed_kernel() is basically functional
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
	    self.test(*self.arg)
	  File "c:\python27\lib\site-packages\ipython-1.0dev-py2.7.egg\IPython\kernel\zmq\tests\test_embed_kernel.py", line 111, in test_embed_kernel_basic
	    msg = client.get_shell_msg(block=True, timeout=2)
	  File "c:\python27\lib\site-packages\ipython-1.0dev-py2.7.egg\IPython\kernel\client.py", line 85, in get_shell_msg
	    return self.shell_channel.get_msg(*args, **kwargs)
	  File "c:\python27\lib\site-packages\ipython-1.0dev-py2.7.egg\IPython\kernel\blocking\channels.py", line 41, in get_msg
	    return self._in_queue.get(block, timeout)
	  File "c:\python27\lib\Queue.py", line 176, in get
	    raise Empty
	Empty

	======================================================================
	ERROR: IPython.embed_kernel() inherits calling namespace
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
	    self.test(*self.arg)
	  File "c:\python27\lib\site-packages\ipython-1.0dev-py2.7.egg\IPython\kernel\zmq\tests\test_embed_kernel.py", line 142, in test_embed_kernel_namespace
	    msg = client.get_shell_msg(block=True, timeout=2)
	  File "c:\python27\lib\site-packages\ipython-1.0dev-py2.7.egg\IPython\kernel\client.py", line 85, in get_shell_msg
	    return self.shell_channel.get_msg(*args, **kwargs)
	  File "c:\python27\lib\site-packages\ipython-1.0dev-py2.7.egg\IPython\kernel\blocking\channels.py", line 41, in get_msg
	    return self._in_queue.get(block, timeout)
	  File "c:\python27\lib\Queue.py", line 176, in get
	    raise Empty
	Empty

	======================================================================
	ERROR: IPython.embed_kernel() can be called multiple times
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
	    self.test(*self.arg)
	  File "c:\python27\lib\site-packages\ipython-1.0dev-py2.7.egg\IPython\kernel\zmq\tests\test_embed_kernel.py", line 178, in test_embed_kernel_reentrant
	    msg = client.get_shell_msg(block=True, timeout=2)
	  File "c:\python27\lib\site-packages\ipython-1.0dev-py2.7.egg\IPython\kernel\client.py", line 85, in get_shell_msg
	    return self.shell_channel.get_msg(*args, **kwargs)
	  File "c:\python27\lib\site-packages\ipython-1.0dev-py2.7.egg\IPython\kernel\blocking\channels.py", line 41, in get_msg
	    return self._in_queue.get(block, timeout)
	  File "c:\python27\lib\Queue.py", line 176, in get
	    raise Empty
	Empty

{'commit_hash': '200133d',
 'commit_source': 'installation',
 'default_encoding': 'cp1252',
 'ipython_path': 'c:\\python27\\lib\\site-packages\\ipython-1.0dev-py2.7.egg\\IPython',
 'ipython_version': '1.0dev',
 'os_name': 'nt',
 'platform': 'Windows-7-6.1.7601-SP1',
 'sys_executable': 'c:\\python27\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)]'}

**Comment by takluyver** [comment] 2016-01-26 18:35
From paulgb/runipy it looks like this couldn't reliably be reproduced as of 2.4.1. Closing here, we can reopen if it's still an issue for someone.

**Closed by takluyver** 2016-01-26 18:35 UTC
Labels: kernel, needs-info, windows
