### ISSUE TITLE
IPython (from Anaconda2-5.1.0-MacOSX-x86_64.pkg) does not start from the command line with Mac OS  X 12.12

### ISSUE THREAD

**Issue by KenMighell** [ipython/ipython#11084] opened 2018-04-09 21:52 UTC
I am trying to install the latest version of Anaconda on my Mac Pro (Mac OS X Sierra 10.12) using
Anaconda2-5.1.0-MacOSX-x86_64.pkg
and Ipython  (version 5.6.0) crashes when started from the command line.  The traceback ends 
with 

`File "/Users/mighell/anaconda2/lib/python2.7/site-packages/IPython/utils/colorable.py", line 25, in Colorable
    default_style=Unicode('lightbg').tag(config=True)
AttributeError: 'Unicode' object has no attribute 'tag'`

Now Python does work but spyder fails at startup with similar errors reported by IPython.

I have tried to do several clean installs with different installation directories and have
encountered the same problems.

**The IPython command with traceback:**

```
$ ~/anaconda2/bin/ipython
Traceback (most recent call last):
  File "/Users/mighell/anaconda2/bin/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/Users/mighell/anaconda2/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/Users/mighell/anaconda2/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/Users/mighell/anaconda2/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/Users/mighell/anaconda2/lib/python2.7/site-packages/IPython/core/ultratb.py", line 119, in <module>
    from IPython.core import debugger
  File "/Users/mighell/anaconda2/lib/python2.7/site-packages/IPython/core/debugger.py", line 37, in <module>
    from IPython.utils import PyColorize, ulinecache
  File "/Users/mighell/anaconda2/lib/python2.7/site-packages/IPython/utils/PyColorize.py", line 57, in <module>
    from .colorable import Colorable
  File "/Users/mighell/anaconda2/lib/python2.7/site-packages/IPython/utils/colorable.py", line 21, in <module>
    class Colorable(Configurable):
  File "/Users/mighell/anaconda2/lib/python2.7/site-packages/IPython/utils/colorable.py", line 25, in Colorable
    default_style=Unicode('lightbg').tag(config=True)
AttributeError: 'Unicode' object has no attribute 'tag'
```

Python example usage:

`$ ~/anaconda2/bin/python 
Python 2.7.14 |Anaconda custom (64-bit)| (default, Dec  7 2017, 11:07:58) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> print np.__version__
1.14.0
>>> 
`
So Python looks to be working.

**System information:**

`$ conda info

     active environment : None
       user config file : /Users/mighell/.condarc
 populated config files : /Users/mighell/.condarc
          conda version : 4.5.0
    conda-build version : 3.4.1
         python version : 2.7.14.final.0
       base environment : /Users/mighell/anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/mighell/anaconda2/pkgs
                          /Users/mighell/.conda/pkgs
       envs directories : /Users/mighell/anaconda2/envs
                          /Users/mighell/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/2.7.14 Darwin/16.0.0 OSX/10.12
                UID:GID : 501:20
             netrc file : /Users/mighell/.netrc
           offline mode : False
`
`# packages in environment at /Users/mighell/anaconda2:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py27h172cb35_0  
alabaster                 0.7.10           py27h9dd7d6e_0  
anaconda                  custom           py27h2cfa9e9_0  
anaconda-client           1.6.9                    py27_0  
anaconda-navigator        1.7.0                    py27_0  
anaconda-project          0.8.2            py27h2dc806c_0  
appnope                   0.1.0            py27hb466136_0  
appscript                 1.0.1            py27h451298e_1  
asn1crypto                0.24.0                   py27_0  
astroid                   1.6.1                    py27_0  
astropy                   2.0.3            py27h1de35cc_0  
attrs                     17.4.0                   py27_0  
babel                     2.5.3                    py27_0  
backports                 1.0              py27hb4f9756_1  
backports.functools_lru_cache 1.4              py27h2aca819_1  
backports.shutil_get_terminal_size 1.0.0            py27hc9115de_2  
backports_abc             0.5              py27h6972548_0  
beautifulsoup4            4.6.0            py27h9416283_1  
bitarray                  0.8.1            py27h1de35cc_1  
bkcharts                  0.2              py27haafc882_0  
blaze                     0.11.3           py27hb49378a_0  
bleach                    2.1.2                    py27_0  
bokeh                     0.12.13          py27h5233db4_0  
boto                      2.48.0           py27hacdd0fd_1  
bottleneck                1.2.1            py27h71f98a3_0  
bzip2                     1.0.6                hd86a083_4  
ca-certificates           2018.03.07                    0  
cdecimal                  2.3              py27h1de35cc_3  
certifi                   2018.1.18                py27_0  
cffi                      1.11.4           py27h342bebf_0  
chardet                   3.0.4            py27h2842e91_1  
click                     6.7              py27h2b86a94_0  
cloudpickle               0.5.2                    py27_1  
clyent                    1.2.2            py27hc0ae608_0  
colorama                  0.3.9            py27hbbe92b6_0  
conda                     4.5.0                    py27_0  
conda-build               3.4.1                    py27_0  
conda-env                 2.6.0                h36134e3_0  
conda-verify              2.0.0            py27hbebe81d_0  
configparser              3.5.0            py27hc7edf1b_0  
contextlib2               0.5.5            py27h9cb85f4_0  
cryptography              2.1.4            py27hdbc5e8f_0  
curl                      7.58.0               ha441bb4_0  
cycler                    0.10.0           py27hfc73c78_0  
cython                    0.27.3           py27h6429b90_0  
cytoolz                   0.9.0            py27h1de35cc_0  
dask                      0.16.1                   py27_0  
dask-core                 0.16.1                   py27_0  
datashape                 0.5.4            py27hd6a1745_0  
dbus                      1.12.2               h5243cc1_1  
decorator                 4.2.1                    py27_0  
distributed               1.20.2                   py27_0  
docutils                  0.14             py27h0befae3_0  
entrypoints               0.2.3            py27hd680fb1_2  
enum34                    1.1.6            py27hf475452_1  
et_xmlfile                1.0.1            py27hc42f929_0  
expat                     2.2.5                hb8e80ba_0  
fastcache                 1.0.2            py27h1de35cc_2  
filelock                  2.0.13           py27h2c227fa_0  
flask                     0.12.2           py27h3ac5568_0  
flask-cors                3.0.3            py27h13db576_0  
freetype                  2.8                  h12048fb_1  
funcsigs                  1.0.2            py27hb9f6266_0  
functools32               3.2.3.2          py27h8ceab06_1  
futures                   3.2.0            py27h1b80678_0  
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
gevent                    1.2.2            py27hc02608c_0  
glib                      2.53.6               h33f6a65_2  
glob2                     0.6              py27h55c9705_0  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py27h4bc979a_2  
greenlet                  0.4.12           py27h081ed54_0  
grin                      1.2.1                    py27_4  
h5py                      2.7.1            py27h75626f5_0  
hdf5                      1.10.1               ha036c08_1  
heapdict                  1.0.0                    py27_2  
html5lib                  1.0.1            py27h5233db4_0  
icu                       58.2                 h4b95b61_1  
idna                      2.6              py27hedea723_1  
imageio                   2.2.0            py27h37746d9_0  
imagesize                 0.7.1            py27h4f7bcc8_0  
intel-openmp              2018.0.0             h8158457_8  
ipaddress                 1.0.19                   py27_0  
ipykernel                 4.8.0                    py27_0  
ipython                   5.6.0                    py27_0  
ipython-notebook          4.0.4                    py27_0  
ipython-qtconsole         4.0.1                    py27_0  
ipython_genutils          0.2.0            py27h8b9a179_0  
ipywidgets                7.1.1                    py27_0  
isort                     4.2.15           py27h5bf637f_0  
itsdangerous              0.24             py27h3948ded_1  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.3              py27hfeaf94f_0  
jedi                      0.11.1                   py27_0  
jinja2                    2.10             py27h70b8dc5_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py27hd9b497e_0  
jupyter                   1.0.0                    py27_4  
jupyter_client            5.2.2                    py27_0  
jupyter_console           5.2.0            py27h9702a86_1  
jupyter_core              4.4.0            py27h5ea6ba4_0  
jupyterlab                0.31.5                   py27_0  
jupyterlab_launcher       0.10.2                   py27_0  
lazy-object-proxy         1.3.1            py27h712ce3f_0  
libcurl                   7.58.0               hf30b1f0_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.34               he12f830_0  
libsodium                 1.0.15               hd9e47c5_0  
libssh2                   1.8.0                h322a93b_4  
libtiff                   4.0.9                h0dac147_0  
libxml2                   2.9.7                hab757c2_0  
libxslt                   1.1.32               hb819dd2_0  
llvmlite                  0.21.0           py27hac8ee23_0  
locket                    0.2.0            py27ha10513d_1  
lxml                      4.1.1            py27hef8c89e_1  
lzo                       2.10                 h362108e_2  
markupsafe                1.0              py27hd3c86fa_1  
matplotlib                2.1.2            py27h6d6146d_0  
mccabe                    0.6.1            py27h1f69e8d_0  
mistune                   0.8.3                    py27_0  
mkl                       2018.0.1             hfbd8650_4  
mkl-service               1.1.2            py27hcba3029_4  
mpc                       1.0.3                h7a72875_5  
mpfr                      3.1.5                h711e7fd_2  
mpmath                    1.0.0            py27h6b0eff6_2  
msgpack-python            0.5.1            py27h04f5b5a_0  
multipledispatch          0.4.9            py27h10993aa_0  
navigator-updater         0.1.0            py27ha63e0b4_0  
nbconvert                 5.3.1            py27h6455e4c_0  
nbformat                  4.4.0            py27hddc86d0_0  
ncurses                   6.0                  hd04f020_2  
networkx                  2.1                      py27_0  
nltk                      3.2.5            py27h2e86947_0  
nose                      1.3.7            py27h2ee3cb8_2  
notebook                  5.4.0                    py27_0  
numba                     0.36.2          np114py27he3a832a_0  
numexpr                   2.6.4            py27hf375000_0  
numpy                     1.14.0           py27h8a80b8c_1  
numpydoc                  0.7.0            py27h022f19e_0  
odo                       0.5.1            py27h992a9f7_0  
olefile                   0.45.1                   py27_0  
openpyxl                  2.4.10                   py27_0  
openssl                   1.0.2o               h26aff7b_0  
packaging                 16.8             py27h24b219a_0  
pandas                    0.22.0           py27h0a44026_0  
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2            py27hed78c4e_1  
parso                     0.1.1            py27he57c4c6_0  
partd                     0.3.8            py27h7560dbf_0  
path.py                   10.5             py27h0d68f8b_0  
pathlib2                  2.3.0            py27he09da1e_0  
patsy                     0.5.0                    py27_0  
pcre                      8.41                 hfb6ab37_1  
pep8                      1.7.1                    py27_0  
pexpect                   4.3.1                    py27_0  
pickleshare               0.7.4            py27h37e3d41_0  
pillow                    5.0.0            py27hfcce615_0  
pip                       9.0.1            py27h1567d89_4  
pkginfo                   1.4.1            py27ha9221e7_0  
pluggy                    0.6.0            py27had36429_0  
ply                       3.10             py27h6279b8a_0  
prompt_toolkit            1.0.15           py27h4a7b9c2_0  
psutil                    5.4.3            py27h1de35cc_0  
ptyprocess                0.5.2            py27h70f6364_0  
py                        1.5.2            py27he6783ac_0  
pyaudio                   0.2.7            py27h3777516_1  
pycodestyle               2.3.1            py27h5b634e0_0  
pycosat                   0.6.3            py27h6c51c7e_0  
pycparser                 2.18             py27h0d28d88_1  
pycrypto                  2.6.1            py27h1de35cc_7  
pycurl                    7.43.0.1         py27hdbc3d79_0  
pyflakes                  1.6.0            py27h4446e76_0  
pygments                  2.2.0            py27h1a556bb_0  
pylint                    1.8.2                    py27_0  
pyodbc                    4.0.22           py27h0a44026_0  
pyopenssl                 17.5.0           py27hfda213f_0  
pyparsing                 2.2.0            py27h5bb6aaf_0  
pyqt                      5.9.2            py27h11d3b92_0  
pysocks                   1.6.7            py27h1cff6a6_1  
pytables                  3.4.2            py27ha4551b8_2  
pytest                    3.3.2                    py27_0  
python                    2.7.14              hde5916a_29  
python-dateutil           2.6.1            py27hd56c96b_1  
python.app                2                py27hf2d5e94_7  
pytz                      2017.3           py27h803c07a_0  
pywavelets                0.5.2            py27hd99e88a_0  
pyyaml                    3.12             py27ha7932d0_1  
pyzmq                     16.0.3           py27h91ccc67_0  
qt                        5.9.4                h14e15a9_0  
qtawesome                 0.4.4            py27hdeb2f59_0  
qtconsole                 4.3.1            py27hdc90b4f_0  
qtpy                      1.3.1            py27h39159f8_0  
readline                  7.0                  hc1231fa_4  
requests                  2.18.4           py27h9b2b37c_1  
rope                      0.10.7           py27hffa1879_0  
ruamel_yaml               0.15.35          py27h1de35cc_1  
scandir                   1.6              py27h97aa1ee_0  
scikit-image              0.13.1           py27h1de35cc_1  
scikit-learn              0.19.1           py27h9788993_0  
scipy                     1.0.0            py27h793f721_0  
seaborn                   0.8.1            py27h6bd0ddc_0  
send2trash                1.4.2                    py27_0  
setuptools                38.4.0                   py27_0  
simplegeneric             0.8.1                    py27_2  
singledispatch            3.4.0.3          py27he22c18d_0  
sip                       4.19.8           py27h0a44026_0  
six                       1.11.0           py27h7252ba3_1  
snowballstemmer           1.2.1            py27h68ac032_0  
sortedcollections         0.5.3            py27h8094be4_0  
sortedcontainers          1.5.9                    py27_0  
sphinx                    1.6.6                    py27_0  
sphinxcontrib             1.0              py27hd2ed746_1  
sphinxcontrib-websupport  1.0.1            py27h857890b_1  
spyder                    3.2.6                    py27_0  
sqlalchemy                1.2.1            py27h1de35cc_0  
sqlite                    3.22.0               h3efe00b_0  
ssl_match_hostname        3.5.0.1          py27h8780752_2  
statsmodels               0.8.0            py27h6d68dbf_0  
subprocess32              3.2.7            py27h24b2887_0  
sympy                     1.1.1            py27hce55102_0  
tblib                     1.3.2            py27ha684fc4_0  
terminado                 0.8.1                    py27_1  
testpath                  0.3.1            py27h72d81a5_0  
tk                        8.6.7                h35a86e2_3  
toolz                     0.9.0                    py27_0  
tornado                   4.5.3                    py27_0  
traitlets                 4.3.2            py27hcf08151_0  
typing                    3.6.2            py27h646fea0_0  
unicodecsv                0.14.1           py27h170f95c_0  
unixodbc                  2.3.4                h4cb4dde_1  
urllib3                   1.22             py27hc3787e9_0  
wcwidth                   0.1.7            py27h817c265_0  
webencodings              0.5.1            py27h19a9f58_1  
werkzeug                  0.14.1                   py27_0  
wheel                     0.30.0           py27h677a027_1  
widgetsnbextension        3.1.0                    py27_0  
wrapt                     1.10.11          py27hd341262_0  
xlrd                      1.1.0            py27hbd41ed1_1  
xlsxwriter                1.0.2            py27h7f1064a_0  
xlwings                   0.11.5                   py27_0  
xlwt                      1.2.0            py27hbeec4ae_0  
xz                        5.2.3                h0278029_2  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.2                ha360ad0_2  
zict                      0.1.3            py27h5fff8b1_0  
zlib                      1.2.11               hf3cbc9b_2  
`

**Comment by takluyver** [comment] 2018-04-10 18:40
I think that means it's finding an older version of the traitlets package somewhere. The version conda lists is the latest, but there must be another version installed somewhere. Try doing `import traitlets; print(traitlets)` in Python to see where it's loading from.

**Comment by KenMighell** [comment] 2018-04-10 20:00
Hi Thomas,

> $ ~/anaconda2/bin/python
> Python 2.7.14 |Anaconda custom (64-bit)| (default, Dec  7 2017, 11:07:58) 
> [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import traitlets
> >>> print(traitlets)
> <module 'traitlets' from '/Users/mighell/.local/lib/python2.7/site-packages/traitlets/__init__.pyc'>
> >>> 

I renamed the directory 

/Users/mighell/.local/lib/python2.7

(which dates from 2016) as

/Users/mighell/.local/lib/python2.7_ancient

And now IPython works!

> $ ~/anaconda2/bin/ipython
> Python 2.7.14 |Anaconda custom (64-bit)| (default, Dec  7 2017, 11:07:58) 
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 5.6.0 -- An enhanced Interactive Python.
> ?         -> Introduction and overview of IPython's features.
> %quickref -> Quick reference.
> help      -> Python's own help system.
> object?   -> Details about 'object', use 'object??' for extra details.
> 
> In [1]: import numpy
> 
> In [2]: print numpy.__version__
> 1.14.0
> 
> In [3]: import traitlets
> 
> In [4]: print(traitlets)
> <module 'traitlets' from '/Users/mighell/anaconda2/lib/python2.7/site-packages/traitlets/__init__.pyc'>
> 
> In [5]: print traitlets.__version__
> 4.3.2
> 
> In [6]: 


Thank you very very much for your email!


My PATH environment variable has the base Anaconda2 directory (~/anaconda2/bin) 
as the first directory.


The directory

/Users/mighell/.local

is *not* anywhere in my PATH environment variable.


Do you know why IPython looked in the directory 

~/.local

instead of under

~/anaconda2

?


I would consider this IPython behavior to be a user-hostile bug.


Do you possibly know how I can report this bug to the IPython development community?


Thanks again for helping me!

Best regards,

Ken Mighell


P.S.  ~/anaconda2/spyder is now working correctly  :-)


P.P.S.  Just out of curiosity: How in the world did you know/suspect that the errors were 
related to the traitlets package? The phrase traitlets appears nowhere in the traceback 
errors.

**Comment by takluyver** [comment] 2018-04-10 20:14
Imports aren't affected by PATH - that's for finding commands. It's normal for Python to look in a user-specific location (`~/.local/lib/...` on Linux) first for imports, though it's debatable whether that's appropriate for Anaconda, which is often using a user-writable directory anyway.

If anyone was to change it, it would need to be Anaconda, not IPython - it wouldn't make sense for imports to work differently in IPython from all other Python tools. When they were asked about it a couple of years ago, they didn't seem keen on changing it, though: https://github.com/ContinuumIO/anaconda-issues/issues/473

> P.P.S. Just out of curiosity: How in the world did you know/suspect that the errors were related to the traitlets package? The phrase traitlets appears nowhere in the traceback errors.

I don't think there's any easy way unless you're familiar with traitlets. The line the error is coming from creates a `Unicode()` instance (capital U, not the native Python 2 `unicode` type), and then calls the `.tag()` method on it. When you see a lot of traitlets code, both of those things are clear signs of traitlets being involved. And I know that the `.tag()` method was added in a version some time ago, so if the error is that it's missing, that tells me it's probably an older version of traitlets. :-)

**Comment by takluyver** [comment] 2018-04-10 20:15
Closing because, while this is certainly confusing, it's not a bug in IPython. Feel free to keep using the comments to discuss it.

**Closed by takluyver** 2018-04-10 20:15 UTC

**Comment by KenMighell** [comment] 2018-04-10 21:33
Hi Thomas,

> On Apr 10, 2018, at 1:15 PM, Thomas Kluyver <notifications@github.com> wrote:
> 
> Imports aren't affected by PATH - that's for finding commands. It's normal for Python to look in a user-specific location (~/.local/lib/... on Linux) first for imports, though it's debatable whether that's appropriate for Anaconda, which is often using a user-writable directory anyway.
> 
> If anyone was to change it, it would need to be Anaconda, not IPython - it wouldn't make sense for imports to work differently in IPython from all other Python tools. When they were asked about it a couple of years ago, they didn't seem keen on changing it, though: ContinuumIO/anaconda-issues#473 <https://github.com/ContinuumIO/anaconda-issues/issues/473>
> 

Why not have a simple assertion within IPython to test that the version number of the imported 
traitlets package be be sufficiently high enough to support the .tag() method?

Alternatively, from ContinuumIO/anaconda-issues#473 <https://github.com/ContinuumIO/anaconda-issues/issues/473> discussion, it appears that the assertion 
test might be put in the Anaconda Python package’s site.py file. 
> P.P.S. Just out of curiosity: How in the world did you know/suspect that the errors were related to the traitlets package? The phrase traitlets appears nowhere in the traceback errors.
> 
> I don't think there's any easy way unless you're familiar with traitlets. The line the error is coming from creates a Unicode() instance (capital U, not the native Python 2 unicode type), and then calls the .tag() method on it. When you see a lot of traitlets code, both of those things are clear signs of traitlets being involved. And I know that the .tag() method was added in a version some time ago, so if the error is that it's missing, that tells me it's probably an older version of traitlets. :-)
> 

So high-level guru experience!  

Thanks again for your help!

-Ken

**Comment by takluyver** [comment] 2018-04-11 10:06
> Why not have a simple assertion within IPython to test that the version number of the imported traitlets package be be sufficiently high enough to support the .tag() method?

IPython has a dependency on traitlets, which is the standard way of specifying this kind of thing. It's up to packaging tools like conda or pip how to ensure that the necessary dependencies are available. I don't want to start duplicating our dependencies as assertions in the code. We'll just forget to update them.

**Comment by KenMighell** [comment] 2018-04-11 15:39
Hi Thomas,

> On Apr 11, 2018, at 3:06 AM, Thomas Kluyver <notifications@github.com> wrote:
> 
> Why not have a simple assertion within IPython to test that the version number of the imported traitlets package be be sufficiently high enough to support the .tag() method?
> 
> IPython has a dependency on traitlets, which is the standard way of specifying this kind of thing. It's up to packaging tools like conda or pip how to ensure that the necessary dependencies are available. I don't want to start duplicating our dependencies as assertions in the code. We'll just forget to update them.
> 

I have communicated with some of the Anaconda team and they say this is an IPython issue.

Sigh... 


Cheers,

-Ken

**Comment by takluyver** [comment] 2018-04-11 17:00
Sorry to hear that. It's not really anyone's issue per se - every piece is working as designed, it's just that the net effect is not what you're expecting. It's definitely not an IPython issue, though: you happen to have encountered the problem with IPython and traitlets, but the same underlying confusion about imports could affect any Python package at all.

The only plausible 'fix' I see for this general issue is for Anaconda to disable `ENABLE_USER_SITE`. I often modify Anaconda on my own computer to do this. But since they didn't do it straight away, changing it now would undoubtedly bring complaints from a different group of people who make use of the feature the way it is.

Feel free to point the Anaconda team to this issue if they want to understand the problem more.

**Comment by KenMighell** [comment] 2018-04-11 18:05
> On Apr 11, 2018, at 10:01 AM, Thomas Kluyver <notifications@github.com> wrote:
> 
> Sorry to hear that. It's not really anyone's issue per se - every piece is working as designed, it's just that the net effect is not what you're expecting. It's definitely not an IPython issue, though: you happen to have encountered the problem with IPython and traitlets, but the same underlying confusion about imports could affect any Python package at all.
> 
> The only plausible 'fix' I see for this general issue is for Anaconda to disable ENABLE_USER_SITE. I often modify Anaconda on my own computer to do this. But since they didn't do it straight away, changing it now would undoubtedly bring complaints from a different group of people who make use of the feature the way it is.
> 
That is a very good idea.  It would make Anaconda more robust while still allowing ~/.local to be
used by power users.

-Ken
