### ISSUE TITLE
Pressing "enter" for non-ambiguous prompt_toolkit completions doesn't activate the completion

### ISSUE THREAD

**Issue by ngoldbaum** [ipython/ipython#9602] opened 2016-06-10 15:36 UTC
Steps to reproduce:

1. Start IPython
2. type "import matplotli"
3. hit "tab"
4. type enter

Expected outcome:

"import matplotlib" is executed

Actual outcome:

Nothing happens, I need to use the arrow keys to select the matplotlib completion.

Here's an asciinema: https://asciinema.org/a/7oo8wvcc67xanmecusv6xgnv3

Note that in the above video I hit the enter key several times after tab-completing matplotlib, but nothing actually happens until I use the arrow keys to navigate to the appropriate completion.

**Comment by klonuo** [comment] 2016-06-10 16:33
Perhaps, when there is single completion option, besides auto-populating command line, IPython should actually select this one and only available choice in completion dropdown box. This would be consistent with current completion workflow, as command line gets completed only if user selects option from completion dropdown menu.

**Comment by Carreau** [comment] 2016-06-10 17:39
Cf What's new:

```
Known Issues:
-------------

...

 - Dialog completion pop up even with a single completion. Cf :gh:`9540`. This
   would automatically be resolved with the next minor revision of
   ``prompt_toolkit``

```

Duplicate of #9540.

**Closed by Carreau** 2016-06-10 17:39 UTC

**Comment by anntzer** [comment] 2016-06-13 07:58
Kindly requesting a reopen for a slightly different but related issue: pressing enter does not select a completion if the current completion is valid but also a prefix of another completion.
Example with `requests` and `requests_toolbelt` installed: `import req<TAB>` completes to `import requests` and also shows both `requests` and `requests_toolbelt` completion; one must be explicitly selected before pressing enter works.  I think this is actually rather confusing...
