### ISSUE TITLE
ipython 8.9 - crash on start

### ISSUE THREAD

**Issue by 2sn** [ipython/ipython#13922] opened 2023-02-03 04:30 UTC
When I start IPython 8.9 from the command line, I get the following crash
```
Traceback (most recent call last):
  File "/home/alex/Python/bin/ipython3", line 8, in <module>
    sys.exit(start_ipython())
             ^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/IPython/__init__.py", line 124, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/config/application.py", line 1042, in launch_instance
    app.initialize(argv)
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/IPython/terminal/ipapp.py", line 279, in initialize
    self.init_shell()
  File "/home/alex/Python/lib/python3.11/site-packages/IPython/terminal/ipapp.py", line 293, in init_shell
    self.shell = self.interactive_shell_class.instance(parent=self,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/config/configurable.py", line 551, in instance
    inst = cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py", line 687, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/home/alex/Python/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 560, in __init__
    super(InteractiveShell, self).__init__(**kwargs)
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/config/configurable.py", line 109, in __init__
    self.config = config
    ^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/traitlets.py", line 732, in __set__
    self.set(obj, value)
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/traitlets.py", line 721, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/traitlets.py", line 1505, in _notify_trait
    self.notify_change(
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/traitlets.py", line 1517, in notify_change
    return self._notify_observers(change)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/traitlets.py", line 1564, in _notify_observers
    c(event)
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/traitlets.py", line 1146, in compatible_observer
    return func(self, change)
           ^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/config/configurable.py", line 218, in _config_changed
    self._load_config(change.new, traits=traits, section_names=section_names)
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/config/configurable.py", line 167, in _load_config
    with self.hold_trait_notifications():
  File "/home/alex/Python/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/traitlets.py", line 1502, in hold_trait_notifications
    self.notify_change(change)
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/traitlets.py", line 1517, in notify_change
    return self._notify_observers(change)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Python/lib/python3.11/site-packages/traitlets/traitlets.py", line 1564, in _notify_observers
    c(event)
  File "/home/alex/Python/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py", line 417, in _autosuggestions_provider_changed
    self._set_autosuggestions(provider)
  File "/home/alex/Python/lib/python3.11/site-packages/IPython/terminal/interactiveshell.py", line 399, in _set_autosuggestions
    if self.auto_suggest and isinstance(
       ^^^^^^^^^^^^^^^^^
AttributeError: 'TerminalInteractiveShell' object has no attribute 'auto_suggest'

If you suspect this is an IPython 8.9.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```
and IPython terminates.  There is no issue with IPython 8.8.  I can't make sense of what is going wrong.  There must have been some backward-incompatible changes.

**Comment by 2sn** [comment] 2023-02-03 04:37
It seems to be related to my IPython config line
```
c.TerminalInteractiveShell.autosuggestions_provider = None
```

What has this been replaced with?

**Comment by 2sn** [comment] 2023-02-03 04:44
The current documentation, [https://ipython.readthedocs.io/en/stable/config/options/terminal.html](https://ipython.readthedocs.io/en/stable/config/options/terminal.html), however, suggests that this is a valid option.

**Comment by 2sn** [comment] 2023-02-03 04:56
I would appear the variable `auto_suggest` has been removed from `TerminalInteractiveShell` or its parent, or the `if` statement that beaks is new.

**Comment by krassowski** [comment] 2023-02-03 09:04
@2sn thank you for reporting. This is a bug which was fixed three days ago in https://github.com/ipython/ipython/pull/13914 but the fix was not yet released.

Closing this issue as a duplicate of https://github.com/ipython/ipython/issues/13913

**Closed by krassowski** 2023-02-03 09:04 UTC
Labels: bug, autosuggestions
