### ISSUE TITLE
Jupyter Notebook is not showing the output of any code executed on the cell

### ISSUE THREAD

**Issue by s13varun** [ipython/ipython#11027] opened 2018-03-01 10:34 UTC
Hello,
I am new to python. When I use Jupyter Notebook the code inside the cells won't execute and I get these empty brackets ([ ]).
![jn](https://user-images.githubusercontent.com/36952745/36840205-2dc2afbc-1d6a-11e8-8063-57b9e68e7043.jpg)

**Comment by takluyver** [comment] 2018-03-01 10:39
* Do you have any security software installed? We've seen similar problems with some internet security software blocking our connection.
* Does it work if you try in another browser (like Firefox)?

**Comment by s13varun** [comment] 2018-03-01 10:46
no security software.
It was working on chrome 1 week before

**Comment by takluyver** [comment] 2018-03-01 10:57
Any ideas what changed? Did you install any extensions or update anything? It's still worth trying with another browser.

**Comment by s13varun** [comment] 2018-03-01 10:59
Let me try with firefox

**Comment by s13varun** [comment] 2018-03-01 11:02
it launches with chrome default.
Is it possible to change browser

**Comment by takluyver** [comment] 2018-03-01 11:10
Yes. For testing temporarily, right click the Jupyter logo in Chrome and copy the link, then paste it into Firefox.

If you want to override the default, configure `NotebookApp.browser` (see [config docs](http://jupyter-notebook.readthedocs.io/en/stable/config_overview.html)).

**Comment by s13varun** [comment] 2018-03-02 04:53
Same issue in firefox.

**Comment by takluyver** [comment] 2018-03-02 18:21
How are you trying to execute the cells?

**Comment by s13varun** [comment] 2018-03-03 06:39
Using Shift + Enter.
Sir i installed anaconda on another system. Now it is working.

**Comment by kHimanshu1** [comment] 2018-06-15 06:33
Try restarting the kernel in kernel option

**Comment by ariansacct** [comment] 2018-07-20 20:03
Restarting the kernel solves it temporarily. What is the cause and the permanent fix?
It was working fine on my box a 2 days ago, and I have not changed anything.

**Comment by kHimanshu1** [comment] 2018-07-21 12:43
it can be caused by many reasons like:
1. your antivirus is blocking it.
2. your code it taking too long to execute(due to hardware limitations).
3. something is wrong with your python distribution package. (try reinstalling it)

**Comment by ariansacct** [comment] 2018-07-22 04:20
Like I said, it was working as recent as two days ago. Code is just a simple loop. There is no antivirus installed. I have not updated any package during this time.

**Comment by grantrob** [comment] 2018-08-09 22:26
One reproducible way to force Jupyter to stop showing new output (and make the kernel hang) is to run "cat" in a cell with no arguments (on Google Chrome / Ubuntu 16.04). If there is a way to solve this problem (send a Ctrl-D to the kernel?), it might also solve the other looping problems.

**Comment by husseinm-ml** [comment] 2018-09-30 21:42
Hi,
I have just installed juypeter and I have the same issue. I tried on both chrome and iexplorer

**Comment by malanglois** [comment] 2018-10-24 17:04
Did some one resolve the issue? I updated my notebook from version 5 to version 5.7 and now it stop working. Given I have to teach a class tomorrow, I'm stuck in a bad position.

**Comment by khamiruf** [comment] 2018-11-08 10:54
hi anyone has the answer? i have the same problem too

**Comment by Sophie-Germain** [comment] 2018-11-09 14:19
I have the same problem :(

**Comment by nmaiorana** [comment] 2018-11-18 16:43
Any answers here?

**Comment by fgtom** [comment] 2018-11-25 07:34
In my case, the below solution worked. (Downgrading tornado to 4.xx)

https://github.com/jupyter/notebook/issues/3202#issuecomment-357199274

**Comment by stmax82** [comment] 2018-12-02 20:11
@fgtom downgrading tornado didn't work for me :/

I occasionally run into this problem since a while... I already tried disabling Windows Defender and the Firewall and different browsers without success. I installed the Jupyter Notebook using conda. I also tried reinstalling it globally and in conda environments without success either. :( This is really annoying...

**Comment by RishabhVerma098** [comment] 2018-12-12 16:47
same thing happened to me ...but when I disabled my adaware antivirus ..it worked...!!!!

**Comment by Zitihskx** [comment] 2018-12-17 04:07
I am having problem of not compiling. It shows In[*] whenever i compile. I have tried all solutions above, disabling my defender, changing browser options, reinstalling python package , installing jupyter through pip install and anaconda but still problem stays. What can be the solution??

**Comment by JaceRyczak** [comment] 2018-12-20 10:20
Disabling Adaware antivirus solved this problem for me.

**Comment by brettbrocato** [comment] 2018-12-20 16:14
Why is there no one assigned to this?  This approaches being a dealbreaker for corporate people running jupyter behind mandated antivirus.

**Comment by stmax82** [comment] 2018-12-20 20:00
@takluyver I already spent several hours trying to find the cause, both at work and at home, but found that I lack experience with the code base / the architecture / how components are supposed to communicate. I'm sure if someone more experienced with the project could provide some hints on where to look / what to try everyone would be more than willing to work on a solution.

**Comment by darshanc99** [comment] 2018-12-23 09:15
Simply uninstall your adaware antivirus. It fixes the issue!

**Comment by MehrdadDS** [comment] 2019-01-27 17:12
First of all, let's check the state of any cell is the "Code" not in "Markdown"

**Comment by free-4-ever** [comment] 2019-02-03 02:01
I had the same problem and not any of the above mentioned solution worked.

Until I update  conda packages and  ... Voila!

     conda update conda
     conda update anaconda

It all works now!

**Comment by PhysicsForce** [comment] 2019-02-11 01:23
![image](https://user-images.githubusercontent.com/40555019/52542450-8d249b00-2d54-11e9-8b10-81b1abe3701a.png)
Same issue with not running - a weird asterisk appears within the brackets.

**Comment by stmax82** [comment] 2019-02-14 15:22
Maybe an error message might help in this case, like "For some reason I cannot connect to the kernel, could you please try disabling your antivirus, firewall and speed-limiting software? If it *still* doesn't work, please post an issue on github."

Also I seem to have found another cause for that problem - on my private PC the problem appears to have been caused by the software "NetLimiter". I use that to limit my PCs download speed when I'm on a slow shared internet connection.
I noticed that when I set a global speed limit (which seems to also include connections from/to localhost!) of <100kB/s, the kernel does start - but it can take several minutes! In the mean time the notebook / kernel appear to transfer a lot of data after the connection is established. If the connection is slow, that can take ages.
I haven't had this problem again since I disabled the speed limit in NetLimiter. yay.

**Comment by woodrujm** [comment] 2019-02-26 04:00
My jupyter notebook book outputs in python. I added an R cell at the end. It doesn't output things like print and head in the R cell, but does output graphs

![image](https://user-images.githubusercontent.com/25488611/53386682-15bd5100-397b-11e9-9370-31a2d3c2e87a.png)

**Comment by sonofagunn** [comment] 2019-03-04 19:54
Downgrading tornado to 5.1.1 fixed this issue for me.

**Comment by icoxfog417** [comment] 2019-03-05 06:05
It'll relate https://github.com/jupyter/notebook/issues/2664.

As @sonofagunn suggests, downgrading tornado may fix the problem.

**Comment by dpyzo0o** [comment] 2019-03-05 13:58
> Downgrading tornado to 5.1.1 fixed this issue for me.

Saved my life. Tornado recently upgraded to 6.0.1, which seems to cause the problem.

**Comment by Allianzcortex** [comment] 2019-03-05 19:45
> Downgrading tornado to 5.1.1 fixed this issue for me.

save my life . I have no anti-virus software installed and just try to reinstall jupyter notebook but encounter such an issue. use `python -m pip install tornado==5.1.1`

**Comment by softarmpl** [comment] 2019-03-06 10:35
Yeap, it was an issue with tornado. Downgrading to `5.1.1` fixed the issue.

**Comment by Claire-Kimbugwe** [comment] 2019-03-27 05:10
> This problem is also happening for me in a simple for loop. Using chrome browser.

It happens to everyone, I usually just switch to sublime text for a few and then return the next day, if am lucky my jupyter works if am not lucky, i go back to subline

**Comment by HritikKumarSharma** [comment] 2019-04-02 10:41
This bug comes due to multiple spaces in your system folder. In my case, I reinstalled the OS. Then, I installed Anaconda. It worked. :100:

**Comment by lvc0107** [comment] 2019-04-12 00:19
I fixed this interrupting the kernel and restarting it again 
Notice the * in the prompt [*]  instead produce an output [some number]. That means that the kernel is busy, maybe due to some operation with a lot of computation

![Screen Shot 2019-04-11 at 21 18 38](https://user-images.githubusercontent.com/6463937/56003906-6a086000-5c9f-11e9-87d1-955f0b5bbd32.png)


After that, you can execute shift + enter  over the cells in order to produce the outputs again (also try to identify and avoid the heavy operation)

**Comment by SKPriya** [comment] 2019-04-12 12:24
Jupyter notebook is a mess. Will not print anything. No errors, no messages.

frustrating

**Comment by Hazarmavi** [comment] 2019-04-29 21:05
I happened the same with me after I installed jupyterthemes, I fixed by upgrading kernel using the following command: python -m pip install --upgrade ipykernel

**Comment by michaelort33** [comment] 2019-05-01 16:29
This happened to me and I realized the issue was caused by a duplicate nbextensions directory this leads to duplicated .yaml files for the scratchpad extension. 

I fixed by simply typing jupyter --paths into the console. Looking where my jupyter nbextensions were stored. I had nbextensions stored in both myname/anaconda3/etc/jupyter and in myname/.local/share/jupyter

I deleted the nbextension from myname/.local/share/jupyter and I kept the one in anaconda3 folder. 

Problem solved!

**Comment by jdatin** [comment] 2019-07-03 04:23
As @Hazarmavi mentioned.  fixed it by upgrading kernel using the following command: python -m pip install --upgrade ipykernel

**Comment by yamasampo** [comment] 2019-07-08 07:18
I have the same problem. I tried downgrading tornado and upgrading ipykernel and confirmed that I do not have duplicated nbextensions, but my problem has not been solved yet. (This is pretty annoying and I cannot work on anything.)

In my environment, `conda list | grep "tornado"` gives
tornado                   5.1.1            py36h1de35cc_0

and `conda list | grep "ipykernel"` returns
ipykernel                 5.1.1            py36h39e3cac_0

Does any body have any other suggestions?

**Comment by Aref-cs** [comment] 2019-09-26 12:38
I have the same problem. 
1- Shouldn't the activation circle close to the Python be 'green' if the Python is working properly?
2- Moreover, what is that asterisks that appears after I run a line?

**Comment by fisadev** [comment] 2019-10-07 22:00
@Aref-cs

1. Thad circle isn't green. An empty circle means the kernel of the notebook isn't doing anything, and a full circle means it's running code.
2. The asterisks in the cells mean they are being executed, they change to the number when they finish executing the code.

**Comment by StevenRoland** [comment] 2019-10-27 09:37
I had the same issue. I just ran the prompt as administrator as I found a permission error displayed in Jupyter Notebook and disabled my firewall and it works fine.

**Comment by wajdan846** [comment] 2019-11-04 00:12
try reinstalling python as well e.g in my case python 3.5.2 worked fine and after reinstalling jupyter notebook things seem to run perfectly.

**Comment by ck3mp** [comment] 2019-11-05 15:26
I had the exact same issue. Downgrading to Tornado 5.1.1 fixed the issues
(Windows 7, Python 3.7.5, Spaces in the path name to the venv that Jupyter runs from)

**Comment by capitao014** [comment] 2019-11-15 09:37
> I have the same problem.
> 1- Shouldn't the activation circle close to the Python be 'green' if the Python is working properly?
> 2- Moreover, what is that asterisks that appears after I run a line?
> 
> ![jupyter_problem](https://user-images.githubusercontent.com/20786574/65688409-6d0cd680-e0ae-11e9-94ad-5b6a33542878.jpg)

Restart kernel solved the same problem for me.

**Comment by CharlieZhu** [comment] 2019-11-23 02:45
I found the missing output redirected to Jupyter Notebook console, after running `django.setup()`. Then, reset the stdout, solved. Don't know detail yet.

import os, sys
print 'django setup start.'
**stdout = sys.stdout**
import django
django.setup()
**sys.stdout = stdout**
print 'django setup done.'

**Comment by plammens** [comment] 2019-12-16 13:12
I have found that I encounter this issue every time an unhandled exception bubbles up to the notebook. In those cases I have to restart the kernel every time—which is very frustrating.

**Comment by maximelucas** [comment] 2019-12-18 13:31
I am having the same issue. It started happening yesterday after installing `numba` with 
`python3 -m pip install numba --user`

I tried downgrading to tornado 5.1.1 but it does not fix the issue.
In any case, I run Jupyter Notebook 6.0.1 (Python Python 3.6.9), which should not have any problem with the latest version of tornado (6.0.3).

I am on Ubuntu 18.04, so no antivirus. It is not because of the running time of the cell either, it happens with basic '2+2' cells.

Any clue?

**Comment by Saswatm123** [comment] 2019-12-19 06:01
I am having the same issue as @woodrujm , where my Python output works fine, but my R output doesn't work properly. The graphs for R work, but the regular output prints to my console rather than the cell output area. I am trying everything here and will report back if I find anything that doesn't involve settling for reading off my console.

**Comment by AtharvaKitkaru** [comment] 2020-01-18 16:46
> Hello,
> I am new to python. When I use Jupyter Notebook the code inside the cells won't execute and I get these empty brackets ([ ]).
> ![jn](https://user-images.githubusercontent.com/36952745/36840205-2dc2afbc-1d6a-11e8-8063-57b9e68e7043.jpg)

Uninstalling antivirus worked for me

**Comment by diwert-ai** [comment] 2020-01-23 13:24
I had the same issue. Solution was found here:
https://github.com/jupyter/notebook/issues/4613#issuecomment-548992047

**Comment by Raghu0210** [comment] 2020-02-11 16:43
`import sys`
Fixed the issue

**Comment by Aref-cs** [comment] 2020-02-12 01:45
Hi guys! 

I don't have a fix for this issue, since I stopped using my local system! I have a short-term (or maybe long-term) fix for this issue for those who just want to start coding instead of trouble shooting Jupyter and Python packages: use something like _Google Colab_!

I had an issue with Jupyter, then I switched to Anaconda and used JupyterLab, but both had the same issue of having problems with the server connections! I had removed and installed Jupyter, Anaconda and Python several times and changed settings too. 

But to me, it was so much hassle! especially, since I was using Windows and once something goes wrong in windows, it continues to go wrong! :)) Also, I don't get it! Almost whenever I started using a new technique, application or technology, I had to dedicate the first week (or two) of my work to trouble shooting for the thing to just start working on my system! :) So, I switched to online alternatives such as the one CoCalc provides. But for now, I am using _Google Colab_ and it works just fine!

**Comment by lukasbee1** [comment] 2020-03-25 23:23
![image](https://user-images.githubusercontent.com/36301536/77594805-90eb9080-6f08-11ea-8ced-90fbd9620862.png)
I don't know what this numbers mean, but without them I can't see any outbut.

I solved this problem by creating with new field, which was created with numbers.

**Comment by adilodha** [comment] 2020-04-07 09:50
i would like to add one observation:
when i run a loop goes into infinite execution, jupyter notebook stops showing output of executed code. restarting the kernel did resolve the issue.
I think this issue occurs in case of execution time out.

**Comment by Vikram-kotharu** [comment] 2020-04-18 05:40
hello in my jupyter notebook class function is not working
![Screenshot (11)](https://user-images.githubusercontent.com/57530934/79629207-17406e80-8165-11ea-9d41-8bcf4794207d.png)..pls help me

**Comment by Abisoyesam** [comment] 2020-04-23 08:47
> > This problem is also happening for me in a simple for loop. Using chrome browser.
> 
> It happens to everyone, I usually just switch to sublime text for a few and then return the next day, if am lucky my jupyter works if am not lucky, i go back to subline

But how did you use sublime to run the code?

**Comment by kaykayes** [comment] 2020-04-27 14:35
had the same issue , fixed it by closing all tabs, reopening the files in JupyterLab v1.2.6, rerunning the cells one after the other. - watiting for the first one to finish before running the next cell.....I am now getting all the output just fine.

**Comment by louiselumapas** [comment] 2020-04-30 07:20
I have the same problem. Currently following this tutorial here (i'm new to this): https://youtu.be/COlbP62-B-U and when i get to the part when he is the running the pre-defined model by running "Run Cells" image output won't show. I dont have adaware antivirus installed and i dont think i have tornado

**Comment by louiselumapas** [comment] 2020-05-01 01:48
Had the same issue turns out i was downloading all dependencies in my local not inside the tensorflow VM (tensorflow_cpu / tensorflow_gpu). So make sure you are inside the VM

**Comment by Carreau** [comment] 2020-05-04 15:40
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository if this is an actual bug or code proposal. For general help use [discourse](https://discourse.jupyter.org).  This will allow to keep the number of opened issue on the IPython repo under control and allow you to get faster response.

**Closed by Carreau** 2020-05-04 15:40 UTC

**Comment by TkRj** [comment] 2020-05-30 16:06
Hi

I could not solve this either but I am a beginner so I am not particular about IDEs at the moment. I just want to learn the important computing concepts quick and not waste my time troubleshooting this problem.
Solution: I switched to Visual Studio Code and it has not given me any problem. 
Click here: https://code.visualstudio.com/ to download it.

Hope this helps!

**Comment by aparajitad60** [comment] 2020-07-02 15:13
Downgrade tornado, this worked for me.

pip install tornado==4.5.3
