### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by Ashka1990** [ipython/ipython#12221] opened 2020-04-06 20:22 UTC
My code:
```
n=range(1,101)
n=input()
if (n % 2 != 0):
  print ("Weird")
```

User Input provided is 4

Below is error I am encountering:
```
ERROR! Session/line number was not unique in database. History logging moved to new session 66
4

TypeError                                 Traceback (most recent call last)
<ipython-input-30-b6f179e19a70> in <module>()
      2 n=range(1,101)
      3 n=input()
----> 4 if (n % 2 != 0):
      5   print ("Weird")

TypeError: not all arguments converted during string formatting
```

Can anyone please explain me what is meaning of this error and how to overcome it?

Thank You!

**Comment by Carreau** [comment] 2020-04-09 20:16
Hi there, thanks for your question, and is is most likely a question for a forum to learn about Python, but I can give you some hint to get started. 

You have to understand the difference between strings and numbers, look at he following: 


```
$ ipython
Python 3.8.1 | packaged by conda-forge | (default, Jan 29 2020, 15:06:10)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.0.dev -- An enhanced Interactive Python. Type '?' for help.

In [1]: "4"
Out[1]: '4'

In [2]: 4
Out[2]: 4
```

What `input()` gives you is a string.  So `n` in your example is a string. 

And you will realise that `%` is modulo on numbers, but formatting on strings: 

```
In [3]: "Hello %s nice to meet you" % "Ashka"
Out[3]: 'Hello Ashka nice to meet you'
```

What the above message is telling is "Hey you asked me to put 2 somewhere in the string `n`", but there is nowhere  for me to do so ! 

Try to search how to convert strings to numbers in Python, and good luck ! 

I'm going to close the issue as this is not a bug in IPython but you should still be able to comment. 

Thanks !

**Closed** 2020-04-09 20:16 UTC
