### ISSUE TITLE
AttributeError when trying to use ipython

### ISSUE THREAD

**Issue by MoranSimchi** [ipython/ipython#13917] opened 2023-01-31 14:07 UTC
Got the error: 
```
~ ❯ ipython
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/__init__.py", line 124, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/traitlets/config/application.py", line 975, in launch_instance
    app.initialize(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/traitlets/config/application.py", line 110, in inner
    return method(app, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 279, in initialize
    self.init_shell()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 293, in init_shell
    self.shell = self.interactive_shell_class.instance(parent=self,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/traitlets/config/configurable.py", line 551, in instance
    inst = cls(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 648, in __init__
    self.init_prompt_toolkit_cli()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 437, in init_prompt_toolkit_cli
    history = PtkHistoryAdapter(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 143, in __init__
    self._refresh()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 151, in _refresh
    if not self._loaded:
AttributeError: 'PtkHistoryAdapter' object has no attribute '_loaded'

If you suspect this is an IPython 8.4.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

**Comment by krassowski** [comment] 2023-02-02 01:14
@MoranSimchi thank you for reporting it; this is a duplicate of https://github.com/ipython/ipython/issues/13645 which was fixed in IPython 8.5. You are using IPython 8.4 - please upgrade to get the fix. If you absolutely cannot upgrade IPython you can try upgrading `prompt_toolkit` (which is the core problem here - you have too old version of prompt_toolkit installed).

**Closed by krassowski** 2023-02-02 01:14 UTC
