### ISSUE TITLE
Ipython directive creates corrupted output during building docs

### ISSUE THREAD

**Issue by Cheburusska** [ipython/ipython#11643] opened 2019-03-10 16:40 UTC
I want to build docs using sphinx and ipython directive.
I try on simple command:

```
.. ipython:: python

    import datatable as dt
    DT = dt.Frame(A=range(5))
    DT

```

In jupyter notebook results look well:

![Screen Shot 2019-03-10 at 19 48 43](https://user-images.githubusercontent.com/19714042/54088298-ab8ab000-436d-11e9-851f-269a51cfca91.png)

but during building results corrupted:

![Screen Shot 2019-03-10 at 19 39 20](https://user-images.githubusercontent.com/19714042/54088166-47b3b780-436c-11e9-8be1-04099cd059b3.png)

what could be the reason?

**Comment by Carreau** [comment] 2019-03-11 20:41
Duplicate of https://github.com/ipython/ipython/issues/11424 , 

This is not corruption, this is color codes for ansi rendering. Closing as duplicate.

**Closed by Carreau** 2019-03-11 20:41 UTC
