### ISSUE TITLE
Modal dialogs not reliably disabling keyboard manager

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython#8109] opened 2015-03-21 23:20 UTC
To reproduce: click the restart kernel button in the toolbar. With the dialog open, press `a`, and a new cell will be created in the notebook.

However, in e.g. the rename dialog, the keyboard manager is disabled correctly. I haven't yet found the difference. It's not getting disabled for the insert citation dialog in cite2c, which is a problem.

Marking as 3.1 with a degree of optimism.

**Comment by rsmith31415** [comment] 2015-03-22 00:38
Yes, I was able to reproduce this issue. I'm guessing the difference is that the rename dialog changes focus from the cells to the field. Therefore, makes sense that  `dd`, `j`, `k`, `a`, etc don't work. In the other modals, there is no such change of focus, so we are still able to modify the cells in command mode.

**Comment by takluyver** [comment] 2015-03-22 01:28
There's more to it than focus - dialog does explicitly call `keyboard_manager.disable()`:

https://github.com/ipython/ipython/blob/master/IPython/html/static/base/js/dialog.js#L119

**Comment by rsmith31415** [comment] 2015-03-22 02:38
Okay. I think I'm starting to understand. It seems there is no `keyboard_manager` instance being passed to `dialog.modal`. According to the documentation, modal can receive a `keyboard_manager` property, but look at the file `about.js` as an example:

abous.js:25

        dialog.modal({
            title: 'About IPython Notebook',
            body: body,
            buttons: { 'OK': {} }
        });

Now look at notebook.js:383

    /**
     * Display a dialog that allows the user to edit the Notebook's metadata.
     */
    Notebook.prototype.edit_metadata = function () {
        var that = this;
        dialog.edit_metadata({
            md: this.metadata, 
            callback: function (md) {
                that.metadata = md;
            },
            name: 'Notebook',
            notebook: this,
            keyboard_manager: this.keyboard_manager});
    };

I'm not sure why `edit_metadata` is created as a function in a prototype, but I assume it is being used somewhere else. If you test the "Edit Notebook Metadata" option in the notebook, it is the only modal that works correctly. The modal is dismissed after pressing enter and the keyboard is disabled. So maybe we need to add the instance of `keyboard_manager` as an option in `dialog.modal({})`

**Comment by rsmith31415** [comment] 2015-03-22 03:11
Well, there are some inconsistencies. "Edit Notebook Metadata" seems to work okay "always". "Keyboard Shortcuts"  works correctly the first time but after that, the `keyboard_manager` is enabled and the focus is on the cells. "About IPython Notebook" doesn't work correctly in any situation. Can you replicate this in those modals?

**Comment by rsmith31415** [comment] 2015-03-22 08:35
I was able to find the cause for a couple of modals.

In `about.js`, I added the keyboard manager to `dialog.model`:

    dialog.modal({
             title: 'About IPython Notebook',
             body: body,
             buttons: { 'OK': {} },
             notebook: IPython.notebook,
             keyboard_manager: IPython.keyboard_manager,
         });

I'm not sure if you prefer to use the IPython object in some other way, but since this is for testing purposes, I guess it is okay.

In `quickhelp.js`, there is an issue with this method:

     QuickHelp.prototype.show_keyboard_shortcuts = function () {
             /**
             * toggles display of keyboard shortcut dialog
             */
             var that = this;
             if ( this.force_rebuild ) {
                 this.shortcut_dialog.remove();
                 delete(this.shortcut_dialog);
                 this.force_rebuild = false;
             }

I don't think `this.force_build` is being defined, so that part never runs. That code is supposed to clean the previous modal and in this case, it refreshes the values for the keyboard manager. I changed it to:

    QuickHelp.prototype.show_keyboard_shortcuts = function () {
        /**
         * toggles display of keyboard shortcut dialog
         */

        var that = this;
        if ( this.active ) {
            this.shortcut_dialog.remove();
            delete(this.shortcut_dialog);
            this.active = false;
        }

and included the line `this.active = true;` at the end of the method. Futhermore, I included the property to the constructor:

    var QuickHelp = function (options) {
        /**
         * Constructor
         *
         * Parameters:
         *  options: dictionary
         *      Dictionary of keyword arguments.
         *          events: $(Events) instance
         *          keyboard_manager: KeyboardManager instance
         *          notebook: Notebook instance
         */
        this.keyboard_manager = options.keyboard_manager;
        this.notebook = options.notebook;
        this.keyboard_manager.quick_help = this;
        this.events = options.events;
        this.active = false;
    };


However, I haven't been able to find what is the problem with the restart button in the toolbar. Interestingly, restarting the kernel using `Kernel->Restart` disables the keyboard manager correctly.

**Comment by takluyver** [comment] 2015-03-22 19:26
Aha, the fact that the same dialog works when launched from the menu gives me a clue. The toolbar uses an action, and the callback for that action does:

```javascript
env.notebook.restart_kernel();
env.notebook.focus_cell();
```

I guess that the focus_cell() call re-enables the keyboard manager after the dialog is shown. @Carreau, is there a reason we're doing that?

Unfortunately, this doesn't tell me why I'm having focus problems in cite2c, where I don't call focus_cell().

**Comment by rsmith31415** [comment] 2015-03-22 21:08
Yes, commenting out `env-notebook.focus_cell();` maintains the keyboard manager disabled but then when the browser reaches this code (dialog.js:93):

        modal.on("shown.bs.modal", function() {
            setTimeout(function() {
                footer.find("button").last().focus();
                if (options.open) {
                    $.proxy(options.open, modal)();
                }
            }, 0);

The keyboard manager is enabled again. Commenting out `focus()` solves the issue but creates many bugs in the process.

**Comment by takluyver** [comment] 2015-03-22 21:32
Hmm, thanks for investigating that. I'm hoping @Carreau, @jdfreder or @minrk will chip in, as they're all more familiar with the JS stuff than I am.

**Comment by rsmith31415** [comment] 2015-03-23 05:38
I think I figured it out. The problem is in `keyboardmanager.js:190`:

    KeyboardManager.prototype.register_events = function (e) {
        var that = this;
        var handle_focus = function () {
            that.disable();
        };
        var handle_blur = function () {
            that.enable();
        };
        e.on('focusin', handle_focus);
        e.on('focusout', handle_blur);

After you click on the button to restart the kernel (or any other button of the toolbar), the `focusin` event is triggered followed by the `focus` event and finally `focusout` is activated. In this situation, we need to keep the property `enabled=false` of the keyboard manager until the modal is dismissed. However, after `focusout`, `handle_blur` sets `enabled=true` and then we are able to change the cells even when the modal is active. Here `register_events` is passing the element `div#maintoolbar-container`, so this applies to the buttons of the toolbar and that's the difference between restarting the kernel from the menu and using the toolbar.

How should we fix this? I suppose disabling keyboard interactions before focus and enabling them again after focus was needed in some special case. Does anyone remember what the issue was that required this behavior?

**Comment by takluyver** [comment] 2015-03-23 17:37
Aha, thanks for working that out.

Short term: @Carreau, should we really be calling `register_events` on the whole toolbar? The buttons don't need keyboard focus, and the fact that they get it has led to other bugs. Maybe we should be using `register_events` on the specific elements that need keyboard interaction instead.

Longer term: I've come across a similar issue before, when displaying one dialog immediately after another. The general pattern is that two things are disabling and enabling the keyboard manager in a pattern like this:

```
    ----interaction 1----
disable               enable
    |             |     |                    |
               disable                     enable
                  ---------interaction 2------
```

I think what we need is a mechanism for 're-enable the keyboard manager if I was the last thing to disable it'. One way to implement this would be something like a focus system - so in this case, focus would be transferred from the notebook to the toolbar to the dialog, and once the dialog is focussed the toolbar doesn't put the focus back on the notebook.

Ping @ellisonbg because I recall you worked on the complexities of the keyboard manager stuff.

**Comment by takluyver** [comment] 2015-03-23 18:36
I've put this on the agenda for tomorrow's dev meeting.

**Comment by Carreau** [comment] 2015-03-23 19:24
> I guess that the focus_cell() call re-enables the keyboard manager after the dialog is shown. @Carreau, is there a reason we're doing that?

Yes, we had complaint that clicking on button was loosing cell focus. 

So either we do allow button to have focus and tell user they have to click back in input area.
Or we try to fight browser focus in some cases.

> Short term: @Carreau, should we really be calling register_events on the whole toolbar? The buttons don't need keyboard focus, and the fact that they get it has led to other bugs. Maybe we should be using register_events on the specific elements that need keyboard interaction instead.

I'm fine with removing register_events on toolbar. I don't remember the reason. 
I think it might have been for more complex elements like Jon's filter.

**Comment by takluyver** [comment] 2015-03-23 19:29
> Yes, we had complaint that clicking on button was loosing cell focus. 

I remember that for the save button, but for e.g. restart kernel, where it brings up a dialog, we don't want the cell to be focussed again.

**Comment by jdfreder** [comment] 2015-03-23 20:30
@takluyver the easiest way is to just keep a count of disables, decrement it on enable, and at 0 actually enable.

**Comment by takluyver** [comment] 2015-03-23 21:16
I thought of that too, though we'd need a way to bypass the counter and force it enabled, because the disable/enable pairs are not completely reliable - see #7565.

**Comment by rsmith31415** [comment] 2015-03-24 04:52
@takluyver 

>Maybe we should be using register_events on the specific elements that need keyboard interaction instead.

I think that is the best option.

There is another very simple solution. In `toolbar.js:133`:

                button.attr('data-jupyter-action', action_name);
                var fun = el.callback|| function(){
                    button.blur();
                    that.actions.call(action_name)
                };

This is forcing `blur();` on the buttons before calling the action (in this case,  `restart_kernel`). The pattern is the following: enabling the keyboard (before modal), disabling the keyboard (when showing the modal), enabling the keyboard (after hiding the modal). Since this change applies to all the buttons of the toolbar, the pattern is the same.

By the way, when you say you have seen a similar issue with dialogs, maybe that is a different problem because modals are supposed to be removed after termination (or equivalently, destroyed after initializing another modal), right?

I don't think `focus_cell() ` is enabling the keyboard. It seems to be selecting the cell and applying focus:

notebook.js:712 

    function () {
        var cell = this.get_selected_cell();
        if (cell === null) {return;}  // No cell is selected
        cell.focus_cell();
     }

(`cell.focus_cell()` is simply `this.element.focus();`) That must be the reason why it didn't change anything associated to the keyboard manager when I removed that line (after forcing `.blur();`)

>I remember that for the save button, but for e.g. restart kernel, where it brings up a dialog, we don't want the cell to be focused again.

Uhm, but I believe that is the default behavior in master. I'm assuming `focus();` only selects a cell in command mode.

@Carreau Maybe `env.notebook.focus_cell();` is not needed anymore because I removed it in the restart_kernel action and didn't notice any difference. By the way, I haven't seen issues regarding focus after clicking on a button, but if we need to add `focus_cell()`, that shouldn't be a problem.

**Comment by ellisonbg** [comment] 2015-03-24 15:57
Ouch, this stuff is soo painful and difficult. <close eyes and pretend it
just goes away>

I will be at the dev meeting today to talk about this, but in general I
think:

* We should not focus elements. We might even want to remove the tabindex
from our cell divs to completely get rid of this issue. This would allow us
to add more intelligent animated scrolling.
* We should try to transition into registering our keyboard shortcuts on
the notebook div, rather than the whole page. We will have to do this
anyways when we enable the notebook to be embedded into a phosphor panel.


On Mon, Mar 23, 2015 at 9:52 PM, rsmith31415 <notifications@github.com>
wrote:

> @takluyver <https://github.com/takluyver>
>
> Maybe we should be using register_events on the specific elements that
> need keyboard interaction instead.
>
> I think that is the best option.
>
> There is another very simple solution. In toolbar.js:133:
>
>             button.attr('data-jupyter-action', action_name);
>             var fun = el.callback|| function(){
>                 button.blur();
>                 that.actions.call(action_name)
>             };
>
> This is forcing blur(); on the buttons before calling the action (in this
> case, restart_kernel). The pattern is the following: enabling the
> keyboard (before modal), disabling the keyboard (when showing the modal),
> enabling the keyboard (after hiding the modal). Since this change applies
> to all the buttons of the toolbar, the pattern is the same.
>
> By the way, when you say you have seen a similar issue with dialogs, maybe
> that is a different problem because modals are supposed to be removed after
> termination (or equivalently, destroyed after initializing another modal),
> right?
>
> I don't think focus_cell() is enabling the keyboard. It seems to be
> selecting the cell and applying focus:
>
> notebook.js:712
>
> function () {
>     var cell = this.get_selected_cell();
>     if (cell === null) {return;}  // No cell is selected
>     cell.focus_cell();
>  }
>
> (cell.focus_cell() is simply this.element.focus();) That must be the
> reason why it didn't change anything associated to the keyboard manager
> when I removed that line (after forcing .blur();)
>
> I remember that for the save button, but for e.g. restart kernel, where it
> brings up a dialog, we don't want the cell to be focused again.
>
> Uhm, but I believe that is the default behavior in master. I'm assuming
> focus(); only selects a cell in command mode.
>
> @Carreau <https://github.com/Carreau> Maybe env.notebook.focus_cell(); is
> not needed anymore because I removed it in the restart_kernel action and
> didn't notice any difference. By the way, I haven't seen issues regarding
> focus after clicking on a button, but if we need to add focus_cell(),
> that shouldn't be a problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/8109#issuecomment-85337873>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment] 2017-07-23 00:14
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.

**Closed by Carreau** 2017-07-23 00:14 UTC
Labels: notebook
