### ISSUE TITLE
IPython crashes copy-pasting multiline code

### ISSUE THREAD

**Issue by andreagrandi** [ipython/ipython#9877] opened 2016-08-15 14:06 UTC
Hi,

I was trying to paste this code into IPython:

```
r = requests.get(
    'http://httpbin.org/get', params=payload)
```

and it crashed with this error:

```
In [3]: r = requests.get(
Traceback (most recent call last):
  File "/Users/andrea/.virtualenvs/tmprequests/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 440, in mainloop
    self.interact()
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 423, in interact
    code = self.prompt_for_code()
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 333, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 389, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/eventloop/posix.py", line 153, in run
    t()
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 326, in redraw
    self._redraw()
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 346, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/renderer.py", line 436, in render
    extended_height=size.rows,
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 142, in write_to_screen
    sizes = self._divide_heigths(cli, write_position)
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 177, in _divide_heigths
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 175, in get_dimension_for_child
    return c.preferred_height(cli, write_position.width, write_position.extended_height)
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 395, in preferred_height
    return self.content.preferred_height(cli, width, max_available_height)
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 128, in preferred_height
    dimensions = [c.preferred_height(cli, width, max_available_height) for c in self.children]
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 1000, in preferred_height
    cli, width - total_margin_width, max_available_height, wrap_lines),
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/layout/controls.py", line 502, in preferred_height
    content = self.create_content(cli, width, None)
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/layout/controls.py", line 641, in create_content
    document.cursor_position_col),
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/layout/controls.py", line 623, in translate_rowcol
    return Point(y=row, x=get_processed_line(row).source_to_display(col))
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/layout/controls.py", line 583, in get_processed_line
    processed_line = transform(i, get_line(i))
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/layout/controls.py", line 559, in transform
    cli, document, lineno, source_to_display, tokens)
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/layout/processors.py", line 554, in apply_transformation
    cli, document, lineno, source_to_display, tokens)
  File "/Users/andrea/.virtualenvs/tmprequests/lib/python2.7/site-packages/prompt_toolkit/layout/processors.py", line 255, in apply_transformation
    token, text = tokens[col]
IndexError: list index out of range

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by willingc** [comment] 2016-08-15 14:40
Thanks for reporting @andreagrandi. 

@takluyver I can confirm the same behavior if two lines are pasted. If one line and then the next line are pasted, it works fine. Also fine if manually entered.

I enabled the detailed traceback and the output follows:

```
In [7]: r = requests.get(
Traceback (most recent call last):
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 581, in get_processed_line
    return cache[i]
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/carol/anaconda/bin/ipython", line 9, in <module>
    load_entry_point('ipython', 'console_scripts', 'ipython')()
  File "/Users/carol/code/jupyter-projects/ipython/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/carol/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/carol/code/jupyter-projects/ipython/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/Users/carol/code/jupyter-projects/ipython/IPython/terminal/interactiveshell.py", line 440, in mainloop
    self.interact()
  File "/Users/carol/code/jupyter-projects/ipython/IPython/terminal/interactiveshell.py", line 423, in interact
    code = self.prompt_for_code()
  File "/Users/carol/code/jupyter-projects/ipython/IPython/terminal/interactiveshell.py", line 333, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 389, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 153, in run
    t()
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 326, in redraw
    self._redraw()
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 346, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/renderer.py", line 436, in render
    extended_height=size.rows,
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 142, in write_to_screen
    sizes = self._divide_heigths(cli, write_position)
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 177, in _divide_heigths
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 177, in <listcomp>
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 175, in get_dimension_for_child
    return c.preferred_height(cli, write_position.width, write_position.extended_height)
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 395, in preferred_height
    return self.content.preferred_height(cli, width, max_available_height)
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 128, in preferred_height
    dimensions = [c.preferred_height(cli, width, max_available_height) for c in self.children]
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 128, in <listcomp>
    dimensions = [c.preferred_height(cli, width, max_available_height) for c in self.children]
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 1000, in preferred_height
    cli, width - total_margin_width, max_available_height, wrap_lines),
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 502, in preferred_height
    content = self.create_content(cli, width, None)
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 641, in create_content
    document.cursor_position_col),
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 623, in translate_rowcol
    return Point(y=row, x=get_processed_line(row).source_to_display(col))
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 583, in get_processed_line
    processed_line = transform(i, get_line(i))
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 559, in transform
    cli, document, lineno, source_to_display, tokens)
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/processors.py", line 554, in apply_transformation
    cli, document, lineno, source_to_display, tokens)
  File "/Users/carol/anaconda/lib/python3.5/site-packages/prompt_toolkit/layout/processors.py", line 255, in apply_transformation
    token, text = tokens[col]
IndexError: list index out of range
```

**Comment by willingc** [comment] 2016-08-15 14:43
@jonathanslenders fyi
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/layout/controls.py#L581

**Comment by jonathanslenders** [comment] 2016-08-15 14:48
This should be a duplicate of https://github.com/ipython/ipython/issues/9737 and https://github.com/ipython/ipython/issues/9846 

I'll try to push a new release today.

**Comment by willingc** [comment] 2016-08-15 14:50
Thanks @jonathanslenders.

**Comment by jonathanslenders** [comment] 2016-08-15 17:12
Hi @willingc,
prompt_toolkit 1.0.6 has been released. Can you try again after upgrading?

**Comment by willingc** [comment] 2016-08-15 21:25
@jonathanslenders Thanks. 1.0.6 working on my system using OS X 10.11.6 and iterm2. Multiline paste working fine for me now.

<img width="740" alt="screen shot 2016-08-15 at 2 22 56 pm" src="https://cloud.githubusercontent.com/assets/2680980/17680244/168a8fc2-62f4-11e6-9d14-97aa960d5cf4.png">

**Closed by willingc** 2016-08-15 21:25 UTC
Labels: bug

**Comment by andreagrandi** [comment] 2016-08-15 21:30
@willingc thanks to you Carol for triaging the bug so quickly and for anyone involved in fixing it! You all were so quick, kind and responsive! :) It's been a pleasure!
