### ISSUE TITLE
Scope issue only exists in console

### ISSUE THREAD

**Issue by theherk** [ipython/ipython#9140] opened 2016-01-18 23:16 UTC
Usually I correctly get the scope where I break to console in IPython with

```python
import IPython; IPython.embed()
```

However, I have discovered a condition where something appears not to work properly. Take the following code for example:

```python
class AClass(object):
    def do_thing(self, x):
        return True if 'ee' in x else False

def funky():
    obj = AClass()
    stuff = ['aye', 'bee', 'cee']
    ees = [item for item in stuff if obj.do_thing(item) is True]
    import IPython; IPython.embed()

if __name__ == '__main__':
    funky()
```

Once you get to the console here, ees is correctly set. However, if you attempt:

```python
ees2 = [item for item in stuff if obj.do_thing(x) == True]
```

you get

    NameError: name 'obj' is not defined

Of course it is defined. I just used it in the same scope. Am I missing something here?

**Comment by takluyver** [comment] 2016-01-18 23:34
See [this comment](https://github.com/ipython/ipython/issues/136#issuecomment-3084010) for an explanation, but in brief, your list comprehension creates a closure over `obj`, and closures don't play nicely with dynamic evaluation (which is what embed does).

This has been a bug in `embed()` for years, and we haven't managed to find a solution. It seems to be a limitation of Python itself. I'll have another think, but don't hold your breath.

Closing as a duplicate of #136, but feel free to keep using this thread if you want any more clarification.

**Closed by takluyver** 2016-01-18 23:34 UTC

**Comment by theherk** [comment] 2016-01-19 00:23
Oh, I see; fascinating. Thanks for looking into it.
