### ISSUE TITLE
random.random() skipping numbers when run in IPython

### ISSUE THREAD

**Issue by pgreenside** [ipython/ipython#10477] opened 2017-04-22 00:16 UTC
I have found that random.random(), after setting random.seed() in IPython will skip every other number compared to Python. Here are screenshots of the Python call to random.random() and the IPython version. 

**Python**
<img width="514" alt="screen shot 2017-04-21 at 5 00 26 pm" src="https://cloud.githubusercontent.com/assets/1001639/25299577/509886a8-26b5-11e7-985d-f756268ac402.png">
**IPython**
<img width="529" alt="screen shot 2017-04-21 at 5 10 25 pm" src="https://cloud.githubusercontent.com/assets/1001639/25299591/75c0452e-26b5-11e7-8e46-73932b4193db.png">

The 2nd, 4th and 6th numbers of the Python call are chosen as the first three in IPython. 

May be related to #10036.

I am on Mac OS 10.12.4. This does not seem to be an issue on Linux machines and have reproduced this on another laptop with the same Mac OS.

Output of python -c "import IPython; print(IPython.sys_info())":
{'commit_hash': u'5c9c918',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/pgreens/anaconda/lib/python2.7/site-packages/IPython',
 'ipython_version': '5.1.0',
 'os_name': 'posix',
 'platform': 'Darwin-16.5.0-x86_64-i386-64bit',
 'sys_executable': '/Users/pgreens/anaconda/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '2.7.13 |Anaconda 4.3.1 (x86_64)| (default, Dec 20 2016, 23:05:08) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]'}

**Comment by rkern** [comment] 2017-04-22 00:47
I'm guessing that there is a random number being pulled by IPython for some reason, possibly for some kind of unique ID per executed block. Or some other module that IPython calls once per executed block pulls a random number.

In general, this is a fine, typical use of the convenience functions in `random`, which implicitly use a shared global instance. You should only use those if you want *arbitrary* numbers. If you want *repeatable* numbers, you must instantiate `random.Random()` yourself and use the methods on that instance exclusively. Don't expect `random.seed()` to give you repeatability with the convenience functions.

**Comment by takluyver** [comment] 2017-04-24 10:17
Yup, as @rkern described, you should instantiate a `Random()` object yourself if you want a repeatable sequence of random numbers. (Thanks Robert)

Closing as I believe everything is working as intended.

**Closed by takluyver** 2017-04-24 10:17 UTC
