### ISSUE TITLE
ipython crash

### ISSUE THREAD

**Issue by thisgf** [ipython/ipython#10070] opened 2016-11-30 10:25 UTC
```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "c:\python27\lib\site-packages\IPython\__init__.py", line 119, in start_i
python
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\python27\lib\site-packages\traitlets\config\application.py", line 658
, in launch_instance
    app.start()
  File "c:\python27\lib\site-packages\IPython\terminal\ipapp.py", line 348, in s
tart
    self.shell.mainloop()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", lin
e 440, in mainloop
    self.interact()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", lin
e 423, in interact
    code = self.prompt_for_code()
  File "c:\python27\lib\site-packages\IPython\terminal\interactiveshell.py", lin
e 333, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "c:\python27\lib\site-packages\prompt_toolkit\interface.py", line 392, in
 run
    self._redraw()
  File "c:\python27\lib\site-packages\prompt_toolkit\interface.py", line 351, in
 _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "c:\python27\lib\site-packages\prompt_toolkit\renderer.py", line 398, in
render
    size = output.get_size()
  File "c:\python27\lib\site-packages\prompt_toolkit\terminal\win32_output.py",
line 103, in get_size
    info = self.get_win32_screen_buffer_info()
  File "c:\python27\lib\site-packages\prompt_toolkit\terminal\win32_output.py",
line 150, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?
```

os:win7 64bit
python version:2.7

**Comment by minrk** [comment] 2016-11-30 12:56
How did you start IPython?

**Comment by thisgf** [comment] 2016-12-03 08:51
1.window+r open run popup window and input ipython
2. cmd window input ipython
both will crash

**Comment by jonathanslenders** [comment] 2016-12-03 11:26
So, you type "ipython" in the run dialog? Does it work if you type "cmd" in the run dialog and then "ipython" in the window? I guess that in some situations this could start an IPython process without a console attached. The weird thing is that I'm unable to reproduce it.

@thisgf: Which Windows version are you using?

Related pull request: https://github.com/jonathanslenders/python-prompt-toolkit/pull/396  can allocate a windows console if none is available. I'm not sure however whether that would work in this case. Maybe calling AllocConsole (win32 api) could do the trick.

**Comment by takluyver** [comment] 2016-12-28 15:40
@jonathanslenders : Another instance of this has shown up, with @omri7 on #10109. They have Python 2.7.6 on Windows 10. Hopefully that helps work out the issue.

**Comment by jonathanslenders** [comment] 2016-12-28 21:33
This remains a mystery...
I have now Windows 10, and just installed Python 2.7.6 (32bit), IPython 5.1.0. Everything runs fine.

@thisgf @omri7: could you share a screenshot with the actual output? Maybe that could explain something. Further, can you give me the output of ``sys.maxsize``?

**Comment by omri7** [comment] 2016-12-28 21:43
Sure:
(Win10, 64bit)

In [1]: import sys

In [2]: sys.maxsize
Out[2]:
9223372036854775807L

![image](https://cloud.githubusercontent.com/assets/24791094/21532256/3539fa98-cd57-11e6-815f-e789449efeba.png)
![image](https://cloud.githubusercontent.com/assets/24791094/21532265/4de8bf16-cd57-11e6-8eee-89cb64ccf507.png)

**Comment by jonathanslenders** [comment] 2016-12-28 22:10
That's it, I can reproduce it! :-) Probably all 64bit builds of Python 2.7 on Windows have this issue. 32bit runs fine.
Now looking for a solution.

**Comment by omri7** [comment] 2016-12-28 23:08
Cool :)

**Comment by jonathanslenders** [comment] 2016-12-28 23:21
So, I have a possible solution, but it's super weird.

In the following file: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/terminal/win32_output.py

Replace the ``get_win32_screen_buffer_info`` function by this:
```python
    def get_win32_screen_buffer_info(self):
        sbinfo = CONSOLE_SCREEN_BUFFER_INFO()
        self.flush()
        success = windll.kernel32.GetConsoleScreenBufferInfo(
                               self.hconsole, byref(sbinfo))
        
        if success:
            return sbinfo
        else:
            raise NoConsoleScreenBufferError
```

That seems to work (at least for me.)

Now, on the other hand, if we do the following. Then the rendering is not correct,  the cursor doesn't appear on the right places, and some output is duplicated when accepting inputs.

```python
   def _test(self, func, console, sbinfo):
        " Additional method. "
        self.flush()
        success = func(console, sbinfo)
        return success
        
    def get_win32_screen_buffer_info(self):
        sbinfo = CONSOLE_SCREEN_BUFFER_INFO()
        success = self._test(windll.kernel32.GetConsoleScreenBufferInfo, self.hconsole, byref(sbinfo))
     
        if success:
            return sbinfo
        else:
            raise NoConsoleScreenBufferError
```

Further, with keyword arguments, it crashes with the ``NoConsoleScreenBufferError``:

```python
   def _test(self, func, *a):
        " Additional method. "
        self.flush()
        success = func(*a)
        return success
        
    def get_win32_screen_buffer_info(self):
        sbinfo = CONSOLE_SCREEN_BUFFER_INFO()
        success = self._test(windll.kernel32.GetConsoleScreenBufferInfo, self.hconsole, byref(sbinfo))
     
        if success:
            return sbinfo
        else:
            raise NoConsoleScreenBufferError
```
Try to understand that... I also had a variation where it crashed sometimes, but not always.

**Comment by jonathanslenders** [comment] 2016-12-29 21:29
I pushed a possible fix: https://github.com/jonathanslenders/python-prompt-toolkit/commit/d5d9e296cdd3e2b1e8126f6307a7c09d0bdcdd3a

Everyone: can you please upgrade to the latest prompt_toolkit master, and see whether it works?
So far, I really still don't understand what's going on. I'm far from confident, but for IPython it seems to work stable, where I got a crash before.

**Comment by omri7** [comment] 2016-12-30 09:28
Works for me after this change :)

**Comment by takluyver** [comment] 2017-01-12 14:25
OK, it sounds like Jonathan was able to fix this (thanks!), so I'm closing this issue.

**Closed by takluyver** 2017-01-12 14:25 UTC

**Comment by CallMeLaNN** [comment] 2017-09-29 10:19
FYI besides prompt_toolkit, this issue also related to python version. Somehow combination of it. I'm using latest ipython and the fixed prompt_toolkit but it is possible to produce this issue using python 2.7.5 64bit. I'm using Windows 8.1. I just update python to the latest version 2.7.5 --> 2.7.13 and it works.

**Comment by alphaCTzo7G** [comment] 2018-06-19 18:31
Just got this issue as well..

I have a relatively complicated `ipython` setup. Running `ipython` with `pytest` to capture output with `--capture=fd`, Also running `ipdb` to insert breakpoints, and logging output of `ipython/pytes` using the solution here: https://stackoverflow.com/a/14573397/4752883

OS version: Windows 10
Python versoin: 3.5.2
Ipython version: 6.2.1
ipdb version: 0.11
pytest version: 3.4.1

The statement that triggered this problem was the following cell. This has worked well before.. but something happened now which may be an interaction between a lot of elements:

```
In [1]: with redirect_output("C:/Users/username/Desktop/logging_file.log", "C:/Users/username/Desktop/logging_file.log"):
   ...:     %cd D:/path/to/pkg
   ...:     %reset -s -f
   ...:     %run -m pytest -- --capture=fd pkg/tests/test_module.py::TestClass

```

**Comment by alphaCTzo7G** [comment] 2018-06-19 18:38
@jonathanslenders I am using prompt-toolkit version 1.0.0.15.. it seems the bug is still there somewhere.. The previous bugfix seems to be incorporated in v.26..
