### ISSUE TITLE
IPython notebook raises 404 not found because Serving notebook from local directory `C:\Users\Administrator`

### ISSUE THREAD

**Issue by scls19fr** [ipython/ipython#8600] opened 2015-07-02 09:53 UTC
Hello,

I'd like to use IPython with my students.

I installed Anaconda Python (conda 3.14.1) with Python 3.4.3 with Administrator privilege
under Windows 7.

When I log as a student (low privilege) and run Anaconda / IPython (Py 3.4) Notebook it raises

    404 : Not Found
    You are requesting a page that does not exist!

Console display

    Serving notebook from local directory `C:\Users\Administrator`

The problem is that IPython should run inside `C:\Users\student_login`

IPython version is 3.2.0

Shortcut to run IPython notebook is 

    C:\Anaconda3\python.exe "C:\Anaconda3\Scripts/ipython-script.py" notebook

I don't know if that's an Anaconda issue or a IPython issue.

Any help is welcome.

Kind regards

**Comment by Carreau** [comment] 2015-07-02 13:28
@damianavila I'm not sure what Anaconda is doing on this one, do you know who to ask at Continuum ?

@scls19fr, can you run IPython from the command line to see if you have any error messages ?

**Comment by damianavila** [comment] 2015-07-02 14:50
pinging @asmeurer @ilanschnell, they probably can give some feedback on this...

**Comment by asmeurer** [comment] 2015-07-03 08:01
Did you install Anaconda as administrator?

**Comment by scls19fr** [comment] 2015-07-03 08:09
Yes as local administrator.

**Comment by scls19fr** [comment] 2015-07-06 10:32
I've found a workaround to fix this issue.

I changed icon property "Start in directory" for `C:\Users\Administrator` to `%HOMEPATH%`
it seems to fix this issue.

**Comment by fuzhouch** [comment] 2015-11-30 16:31
I hit the same problem once with Anaconda2.4 (Python 3.5) on my lab machine, which is also Windows box from my company.

Steps:
1. During installation I didn't check "Add Python to your system PATH environment variable" in wizard.
2. After installation, I directly start jupyter notebook from CMD window under c:\. I hit the same 404 issue.

An interesting finding is, when I switch to my home directory then start jupyter notebook again, I can see server correctly.

@scls19fr I think your work environment has some strictly designed access control. -- Actually, my lab machine is also similar with yours -- I logs on with my lab account, which is part of local administrators group. However, I still can't write to root folder without UAC prompt.

So I think this is caused by Windows permission settings, which prevents jupyter from creating some folders (.jupyter or .ipython).

**Comment by takluyver** [comment] 2016-01-26 16:27
This sounds like an issue with the Anaconda installer, so closing here. If there's something for us to do, please open a new issue on jupyter/notebook.

**Closed by takluyver** 2016-01-26 16:27 UTC

**Comment by codediner** [comment] 2017-02-16 10:47
In fact, I have the same problem when I want to run the jupyter notebook for menpo project, so I run the cmd as administrator, and I directly install the notebook  in C:/Windows/system 32, and it works!
