### ISSUE TITLE
Ipython Autocomplete not working

### ISSUE THREAD

**Issue by abhisheksachan** [ipython/ipython#13144] opened 2021-09-21 11:01 UTC
Autocomplete not working. Here are my python lib versions

`Requirement already satisfied: ipython in ./venv/lib/python3.6/site-packages (7.16.1)
Requirement already satisfied: appnope in ./venv/lib/python3.6/site-packages (from ipython) (0.1.2)
Requirement already satisfied: backcall in ./venv/lib/python3.6/site-packages (from ipython) (0.2.0)
Requirement already satisfied: jedi>=0.10 in ./venv/lib/python3.6/site-packages (from ipython) (0.18.0)
Requirement already satisfied: traitlets>=4.2 in ./venv/lib/python3.6/site-packages (from ipython) (4.3.3)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in ./venv/lib/python3.6/site-packages (from ipython) (3.0.18)
Requirement already satisfied: pickleshare in ./venv/lib/python3.6/site-packages (from ipython) (0.7.5)
Requirement already satisfied: pygments in ./venv/lib/python3.6/site-packages (from ipython) (2.9.0)
Requirement already satisfied: pexpect in ./venv/lib/python3.6/site-packages (from ipython) (4.8.0)
Requirement already satisfied: decorator in ./venv/lib/python3.6/site-packages (from ipython) (5.0.7)
Requirement already satisfied: setuptools>=18.5 in ./venv/lib/python3.6/site-packages (from ipython) (40.6.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in ./venv/lib/python3.6/site-packages (from jedi>=0.10->ipython) (0.8.2)
Requirement already satisfied: wcwidth in ./venv/lib/python3.6/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython) (0.2.5)
Requirement already satisfied: ipython-genutils in ./venv/lib/python3.6/site-packages (from traitlets>=4.2->ipython) (0.2.0)
Requirement already satisfied: six in ./venv/lib/python3.6/site-packages (from traitlets>=4.2->ipython) (1.15.0)
Requirement already satisfied: ptyprocess>=0.5 in ./venv/lib/python3.6/site-packages (from pexpect->ipython) (0.7.0)`

I cannot upgrade ipython as python 3.6.8 supports only till  ipython 7.16.1 version

**Comment by MrMino** [comment] 2021-09-21 16:03
Duplicate of... I honestly lost track how many different threads :smile:.

`pip install jedi<=17.2`

Fixed in #12793. We do not support 3.6 anymore, but the proposition to backport the fix is tracked under #13100.

**Closed by MrMino** 2021-09-21 16:03 UTC
