### ISSUE TITLE
cannot move cursor right

### ISSUE THREAD

**Issue by Firestar-Reimu** [ipython/ipython#14070] opened 2023-05-04 15:26 UTC
when I enter ipython and type something

I found that I cannot move cursor right using the `->` key unless I press `Esc`

but I need to press 1 `Esc` and move 1 letter right and so on...

and the function of pressing `->` and use the code completion is also broken.

**Comment by EliahKagan** [comment] 2023-05-04 16:39
I am experiencing what I think is the same bug as described here. This is with IPython 8.12.2 and IPython 8.13.2, running on Python 3.11.3 in GNU/Linux (though other systems that I haven't tested may also be affected). It seems to me that #14051 might be only *partially* fixed. Specifically:

- The right arrow key *does* work to move in text that I have already entered. #14052 (and #14068) *did* fix that, since this was not working on IPython 8.12.1 or IPython 8.13/8.13.1.
- The right arrow key, when the cursor is at the end of a line, *does not* perform any completion. **This is in contrast to the expected behavior of completing the entire line.**
- The combination of pressing Escape followed by the right arrow key still does complete one character, as expected.
- Pressing End when the cursor is at the end of the line still does complete the entire line, as expected.

**Comment by albireox** [comment] 2023-05-04 16:54
I'm seeing the same behaviour. The `ESC + ->` works, but obviously it's not usable. `ALT + ->` works as usual, completing one word at a time. The workaround for #14051 of using 

```python
c.TerminalInteractiveShell.shortcuts = [{"command": "IPython:auto_suggest.resume_hinting", " new_keys": []}]
```

still works.

**Comment by Firestar-Reimu** [comment] 2023-05-05 03:15
```
Python 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.13.1 -- An enhanced Interactive Python. Type '?' for help.
```

**Comment by Carreau** [comment] 2023-05-05 06:30
The right arrow not moving the cursor in the text  should be fixed in 8.13.2 and 8.12.2

I'll recheck the completion at end of line but we have many edge case with autocomplete so please have some patience. At end of line you can use the end key (or Ctrl-E on some system) to complete the line.

I think for shortcuts the best person to ask is @krassowski.

**Comment by j-bennet** [comment] 2023-05-05 22:32
The right arrow still won't accept autocomplete suggestion.

**Comment by theXYZT** [comment] 2023-05-06 06:17
I am having the same issue as @j-bennet, right arrow key won't complete autosuggestion in 8.13.2. [The other hotkeys](https://ipython.readthedocs.io/en/8.13.2/config/shortcuts/index.html) work as expected (such as CTRL+F or CTRL+E).

**Comment by albireox** [comment] 2023-05-15 19:40
Any planned action on this? At least for me this bug happens on any fresh installation of ipython on macOS or Linux. There's a workaround, but the base issue seems real to me.

**Comment by krassowski** [comment] 2023-05-15 19:41
Yes, I will submit another patch this weekend.

**Comment by krassowski** [comment] 2023-05-24 17:08
There is a patch in https://github.com/ipython/ipython/pull/14080 - if anyone is happy to test and confirm that it solves the issue it would expedite things :)

**Closed** 2023-06-02 08:35 UTC
