### ISSUE TITLE
7.2.0 completion does not work in emacs 

### ISSUE THREAD

**Issue by spacegoing** [ipython/ipython#11533] opened 2018-12-15 08:23 UTC
6.2.1 works but 7.2.0 not.

Happy to provide more info.

**Comment by memeplex** [comment] 2019-01-02 19:16
Probably a duplicate of https://github.com/ipython/ipython/issues/11541.

Yours was reported before but there is more information and a suggested fix in mine, so you might want to close this one.

**Closed** 2019-01-03 00:02 UTC
