### ISSUE TITLE
Temporarily disable auto-indent when pasting multi-line content

### ISSUE THREAD

**Issue by ddarfantasy** [ipython/ipython#13163] opened 2021-09-29 16:59 UTC
It's just annoying when I receive `IndentationError` everytime after I pasted some code snippets without modifying the indentation. Is it possible to detect the pasting action and disable auto-indent temporarily?

Also, I think the indent should be automatically shorter in the next line of a return statement.

**Comment by tiantian1645** [comment] 2021-11-10 07:19
<img width="545" alt="Snipaste_2021-11-10_15-19-07" src="https://user-images.githubusercontent.com/26370840/141067482-fb109c56-a534-4803-985d-0e9e49c49233.png">

**Comment by jamespreed** [comment] 2021-12-27 22:55
I have the same issue.  In version 7.27.0, pasting by right-clicking preserves the proper indentation.  Since version 7.28.0, the behavior is as seen above. 

Additionally, empty lines are being ignored.  
![image](https://user-images.githubusercontent.com/7841701/147512257-4a2011f1-2589-49a3-99f1-4ac8085bf6ad.png)


Windows 10, Build 19044.1415
Python 3.9.7

**Comment by jamespreed** [comment] 2022-02-01 09:07
Any update on this?

**Comment by jamespreed** [comment] 2022-02-02 21:32
This is an issue with `prompt-toolkit` versions 3.0.20 through 3.0.22.  I have tested it on Windows for Python 3.8, 3.9, and 3.10.  With IPython 7.27.0, 7.29.0, and 8.0.1.  It looks like the issue has been resolved in prompt-toolkit.

| Python | 3.8 | 3.9 | 3.10 |
| --- | --- | --- | ---|
| prompt-toolkit 3.0.5 | OK | OK | OK |
| 3.0.17 | OK | OK | OK |
| 3.0.18 | OK | OK | OK |
| 3.0.19 | OK | OK | OK |
| 3.0.20 | **Fail** | **Fail** | **Fail** |
| 3.0.21 | **Fail** | **Fail** | **Fail** |
| 3.0.22 | **Fail** | **Fail** | **Fail** |
| 3.0.23 | OK | OK | OK |
| 3.0.24 | OK | OK | OK |
| 3.0.25 | OK | OK | OK |
| 3.0.26 | OK | OK | OK |

**Comment by MrMino** [comment] 2022-03-03 22:37
I'm going to close this, basing my decision on @jamespreed research. I haven't checked this myself, but it seems like it's not a bug in IPython. If someone thinks otherwise - feel free to reopen / ping me.

**Closed by MrMino** 2022-03-03 22:37 UTC
Labels: needs-info
