### ISSUE TITLE
ipython qtconsole does not start with PyQt5

### ISSUE THREAD

**Issue by ismail** [ipython/ipython#7707] opened 2015-02-07 12:37 UTC
ipython 2.4.0
PyQt5 5.4
Python 3.4 

on Windows x64 installed, trying to start qtconsole results in 

```
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\ipython.exe\__main__.py", line 9, in <module>
    sys.exit(start_ipython())
  File "C:\Python34\lib\site-packages\IPython\__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Python34\lib\site-packages\IPython\config\application.py", line 563, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "C:\Python34\lib\site-packages\IPython\config\application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Python34\lib\site-packages\IPython\terminal\ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "C:\Python34\lib\site-packages\IPython\config\application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Python34\lib\site-packages\IPython\core\application.py", line 381, in initialize
    self.parse_command_line(argv)
  File "C:\Python34\lib\site-packages\IPython\terminal\ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "C:\Python34\lib\site-packages\IPython\config\application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Python34\lib\site-packages\IPython\config\application.py", line 475, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "C:\Python34\lib\site-packages\IPython\config\application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Python34\lib\site-packages\IPython\config\application.py", line 413, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "C:\Python34\lib\site-packages\IPython\config\application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Python34\lib\site-packages\IPython\qt\console\qtconsoleapp.py", line 351, in initialize
    IPythonConsoleApp.initialize(self,argv)
  File "C:\Python34\lib\site-packages\IPython\consoleapp.py", line 386, in initialize
    self.init_kernel_client()
  File "C:\Python34\lib\site-packages\IPython\consoleapp.py", line 373, in init_kernel_client
    self.kernel_client.start_channels()
  File "C:\Python34\lib\site-packages\IPython\qt\kernel_mixins.py", line 208, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "C:\Python34\lib\site-packages\IPython\kernel\client.py", line 109, in start_channels
    self.shell_channel.start()
  File "C:\Python34\lib\site-packages\IPython\kernel\client.py", line 153, in shell_channel
    self.context, self.session, url
  File "C:\Python34\lib\site-packages\IPython\qt\util.py", line 67, in __new__
    QtCore.QObject.__init__(inst)
TypeError: __init__() missing 3 required positional arguments: 'context', 'session', and 'address'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

**Comment by blink1073** [comment] 2015-02-07 18:28
Note to devs: this may come in handy:
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/qt_compat.py

**Comment by takluyver** [comment] 2015-02-09 19:17
I think we've already got equivalents for that mpl module in IPython.external.qt*. Will look into this issue.

**Comment by takluyver** [comment] 2015-02-09 22:34
I've started digging into this, but the changes it would require are fundamental enough that I don't feel comfortable making them in a bugfix release. On master, the Qt console does at least start, though I think the issue might recur in certain situations (inprocess Qt console with PyQt 5?).

Since we're about to release 3.0, there won't be much more work on 2.x, so I'm closing this. If you find failures with PyQt5 on master/3.x, please file new issues for those.

For my own future reference, the problem is caused by a change to how PyQt5 behaves with multiple inheritance, documented [here](http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html#cooperative-multi-inheritance). Annoyingly, that change would actually make things simpler, but so long as we need to support PyQt4 as well, it doesn't.

**Closed by takluyver** 2015-02-09 22:34 UTC
Labels: bug, qtconsole

**Comment by stonebig** [comment] 2015-04-04 12:55
I notice Support for Qt4 is dying end of 2015:
http://www.riverbankcomputing.co.uk/software/pyqt/intro

**Comment by stonebig** [comment] 2015-04-19 15:32
Excuse me to ask, is it supposed to work now on Windows ?
On my hacked installation (so not sure), I get this error with IPython 3.1 / Python 3.4

![qtconsole_pyqt5](https://cloud.githubusercontent.com/assets/4312421/7220021/dc703d6c-e6b9-11e4-8e52-fe567c89e8e8.GIF)

**Comment by takluyver** [comment] 2015-04-19 16:19
It's working for me on Linux with the development version. I don't have a Windows VM handy to test, but I'd be surprised if something like this was platform dependent.

**Comment by stonebig** [comment] 2015-04-19 16:58
@ismail  did you retry recently with Ipython3.1 / Python3.4? did it work better for you ?

**Comment by ismail** [comment] 2015-04-20 10:03
@stonebig for me it worked fine with ipython 3.1 + python 3.4 on windows (all 64bits).

**Comment by stonebig** [comment] 2015-04-20 10:38
ok. So I must have missed a step in my config. Do you have something more than this in the qt.config ?
````
[Paths]
Prefix = Lib/site-packages/PyQt5
Binaries = Lib/site-packages/PyQt5
````

**Comment by ismail** [comment] 2015-04-20 11:40
None at all, I used all the default configurations.

**Comment by stonebig** [comment] 2015-04-20 12:30
ok, thank you. This will greatly simplify my issue hunting.
