### ISSUE TITLE
Multiline editing broken

### ISSUE THREAD

**Issue by davidbrochart** [ipython/ipython#11337] opened 2018-09-27 21:17 UTC
In IPython 7.0.1, it is only possible to enter e.g. a one-line function:

```python
def foo():
    print('Hello')
    # cell is entered automatically here
```

**Comment by Carreau** [comment] 2018-09-27 22:31
Duplicate of #11334, you can use `ctrl-o` to force a new line.

**Comment by Carreau** [comment] 2018-09-28 05:02
Actually it might not be a duplicate, it may be more complicated than that.

**Comment by Carreau** [comment] 2018-10-20 18:51
closed by #11358

**Closed by Carreau** 2018-10-20 18:51 UTC
