### ISSUE TITLE
Notebook cell output state is not preserved by save

### ISSUE THREAD

**Issue by dpsanders** [ipython/ipython#3657] opened 2013-07-16 18:12 UTC
The output state (full, scroll, collapsed) of a cell in the notebook should be preserved by saving (and carried over to nbconvert output), but it currently opens to full output on upon close and halt followed by reloading.

Closely related to #3659

**Comment by Carreau** [comment] 2015-01-01 19:12
I think we could close this. Cell output should be persisted in metadata.

**Comment by damianavila** [comment] 2015-01-03 15:21
I agree...

**Comment by minrk** [comment] 2015-01-03 20:25
there are documented metadata fields in nbformat for this, but it's not implemented in the Javascript, so the issue persists.

**Comment by damianavila** [comment] 2015-01-03 21:24
but IIRC, the collapsed state is persisted... maybe the scrolling one don't, and this is the cause of my confusion... am I right?

**Comment by minrk** [comment] 2015-01-03 21:26
Yup, and they should both be persisted. Both are in the nbformat metadata spec, but persisting the scroll state is not implemented.

**Closed** 2015-01-25 12:33 UTC
Labels: bug, notebook
