### ISSUE TITLE
DeprecationWarning DisplayFormatter

### ISSUE THREAD

**Issue by cbrnr** [ipython/ipython#9288] opened 2016-03-02 09:43 UTC
The following example triggers a DeprecationWarning in IPython:

```
import numpy as np
import warnings
warnings.simplefilter("default")
y = np.random.randn(100)
y
```

On my system, the warning is:
```
/Users/xxx/anaconda/lib/python3.5/site-packages/IPython/core/formatters.py:90: DeprecationWarning: DisplayFormatter._ipython_display_formatter_default is deprecated: use @default decorator instead.
  def _ipython_display_formatter_default(self):
/Users/xxx/anaconda/lib/python3.5/site-packages/IPython/core/formatters.py:667: DeprecationWarning: PlainTextFormatter._singleton_printers_default is deprecated: use @default decorator instead.
  def _singleton_printers_default(self):
/Users/xxx/anaconda/lib/python3.5/site-packages/IPython/core/formatters.py:670: DeprecationWarning: PlainTextFormatter._type_printers_default is deprecated: use @default decorator instead.
  def _type_printers_default(self):
/Users/xxx/anaconda/lib/python3.5/site-packages/IPython/core/formatters.py:675: DeprecationWarning: PlainTextFormatter._deferred_printers_default is deprecated: use @default decorator instead.
  def _deferred_printers_default(self):
```

System info:
```
{'commit_hash': '8ff8693',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/xxx/anaconda/lib/python3.5/site-packages/IPython',
 'ipython_version': '4.0.3',
 'os_name': 'posix',
 'platform': 'Darwin-15.3.0-x86_64-i386-64bit',
 'sys_executable': '/Users/xxx/anaconda/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.5.1 |Anaconda 2.5.0 (x86_64)| (default, Dec  7 2015, '
                '11:24:55) \n'
                '[GCC 4.2.1 (Apple Inc. build 5577)]'}
```

**Comment by cle1109** [comment] 2016-03-02 10:07
Just found another warning. In a notebook, just activate the inline backend:

    %matplotlib inline

A host of DeprecationWarnings will pop up.

```
/Users/xxx/anaconda/lib/python3.5/site-packages/ipykernel/pylab/config.py:66: DeprecationWarning: metadata {'config': True} was set from the constructor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
  inline backend."""
/Users/xxx/anaconda/lib/python3.5/site-packages/ipykernel/pylab/config.py:71: DeprecationWarning: metadata {'config': True} was set from the constructor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
  'retina', 'jpeg', 'svg', 'pdf'.""")
/Users/xxx/anaconda/lib/python3.5/site-packages/ipykernel/pylab/config.py:85: DeprecationWarning: metadata {'config': True} was set from the constructor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
  use `figure_formats` instead)""")
/Users/xxx/anaconda/lib/python3.5/site-packages/ipykernel/pylab/config.py:95: DeprecationWarning: metadata {'config': True} was set from the constructor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
  """
/Users/xxx/anaconda/lib/python3.5/site-packages/ipykernel/pylab/config.py:114: DeprecationWarning: metadata {'config': True} was set from the constructor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
  """)
/Users/xxx/anaconda/lib/python3.5/site-packages/ipykernel/pylab/config.py:44: DeprecationWarning: InlineBackend._config_changed is deprecated: use @observe and @unobserve instead.
  def _config_changed(self, name, old, new):
/Users/xxx/anaconda/lib/python3.5/site-packages/traitlets/traitlets.py:770: DeprecationWarning: A parent of InlineBackend._config_changed has adopted the new @observe(change) API
  clsname, change_or_name), DeprecationWarning)
```

**Comment by minrk** [comment] 2016-03-02 10:17
Yup, these are because traitlets 4.1 introduced a new API that we will adopt before too long. There's nothing to worry about, and this is why deprecation warnings are off by default.

**Comment by cle1109** [comment] 2016-03-02 10:20
OK cool. I saw them because another package changed the warning state, which of course shouldn't happen. Anyway, I just wanted to give you a heads up in case this behavior was not intended. Thanks for the quick response.

**Comment by ssbarnea** [comment] 2016-05-01 10:15
Can can we get rid of these warnings? Some projects do want and need warnings but if they are unluckily to have something to do related to ipython they are doomed to see enjoy pages and pages of warnings. 

The problem is even worse because some projects do have very tight quality standards that do require to test for warnings during their unittesting and to treat them as errors. So, we do need a way to silence ipython ones. How?

**Comment by minrk** [comment] 2016-05-02 14:55
@ssbarnea this is a duplicate of #9242, which [has some examples](https://github.com/ipython/ipython/issues/9242#issuecomment-188145256) of filtering out warnings like these, for example ignoring all DeprecationWarnings caused by IPython code:

```python
warnings.filterwarnings('ignore', category=DeprecationWarning, module='.*/IPython/.*')
```

**Closed by minrk** 2016-05-02 14:55 UTC
