### ISSUE TITLE
Qtconsole does not start up

### ISSUE THREAD

**Issue by duytrung** [ipython/ipython#8900] opened 2015-10-12 10:50 UTC
I tried to start Ipython QtConsole, however failed...

```
dell@DELL-PC C:\Users\dell
> ipython qtconsole
Traceback (most recent call last):
  File "C:\MyPrograms\Anaconda3\Scripts\ipython-script.py", line 5, in <module>
    sys.exit(start_ipython())
  File "C:\MyPrograms\Anaconda3\lib\site-packages\IPython\__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\MyPrograms\Anaconda3\lib\site-packages\traitlets\config\application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-112>", line 2, in initialize
  File "C:\MyPrograms\Anaconda3\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\MyPrograms\Anaconda3\lib\site-packages\IPython\terminal\ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\MyPrograms\Anaconda3\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\MyPrograms\Anaconda3\lib\site-packages\IPython\core\application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "C:\MyPrograms\Anaconda3\lib\site-packages\IPython\terminal\ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "C:\MyPrograms\Anaconda3\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\MyPrograms\Anaconda3\lib\site-packages\traitlets\config\application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "C:\MyPrograms\Anaconda3\lib\site-packages\traitlets\config\application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\MyPrograms\Anaconda3\lib\site-packages\traitlets\config\application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "C:\MyPrograms\Anaconda3\lib\site-packages\ipython_genutils\importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named 'qtconsole.qtconsoleapp'

dell@DELL-PC C:\Users\dell
```

**Comment by duytrung** [comment] 2015-10-12 10:51
Here is package list:
```
_license                  1.1                      py34_0          
alabaster                 0.7.6                    py34_0          
anaconda-client           1.0.2                    py34_0          
argcomplete               1.0.0                    py34_0          
astropy                   1.0.4                np19py34_0          
babel                     2.1.1                    py34_0          
bcolz                     0.11.3                   py34_0          
beautiful-soup            4.3.2                    py34_1          
binstar                   0.12                          2          
bitarray                  0.8.1                    py34_1          
blaze-core                0.8.3                    py34_0          
blz                       0.6.2                np19py34_1          
bokeh                     0.10.0                   py34_0          
boto                      2.38.0                   py34_0          
bottleneck                1.0.0                np19py34_0          
certifi                   14.05.14                 py34_0          
cffi                      1.2.1                    py34_0          
clyent                    0.4.0                    py34_0          
colorama                  0.3.3                    py34_0          
comtypes                  1.1.2                    py34_0          
conda                     3.18.1                   py34_0          
conda-build               1.18.0                   py34_0          
conda-env                 2.4.2                    py34_0          
configobj                 5.0.6                    py34_0          
cryptography              0.9.3                    py34_0          
cython                    0.23.3                   py34_0          
cytoolz                   0.7.3                    py34_0          
datashape                 0.4.7                    py34_0          
decorator                 4.0.4                    py34_0          
docutils                  0.12                     py34_1          
dynd-python               0.6.5                np19py34_0          
fastcache                 1.0.2                    py34_0          
flask                     0.10.1                   py34_1          
funcsigs                  0.4                      py34_0          
greenlet                  0.4.9                    py34_0          
h5py                      2.5.0                np19py34_2          
hdf5                      1.8.15.1                      2          
idna                      2.0                      py34_0          
ipykernel                 4.1.0                    py34_0          
ipython                   4.0.0                    py34_0          
ipython-notebook          4.0.4                    py34_0          
ipython-qtconsole         4.0.1                    py34_0          
ipython_genutils          0.1.0                    py34_0          
ipywidgets                4.0.3                    py34_0          
itsdangerous              0.24                     py34_0          
jdcal                     1.0                      py34_0          
jedi                      0.8.1                    py34_0          
jinja2                    2.8                      py34_0          
jsonschema                2.4.0                    py34_0          
jupyter                   1.0.0                    py34_0          
jupyter_client            4.1.1                    py34_0          
jupyter_console           4.0.3                    py34_0          
jupyter_core              4.0.6                    py34_0          
launcher                  1.0.0                         1          
llvmlite                  0.7.0                    py34_5          
llvmpy                    0.12.7                   py34_0          
lxml                      3.4.4                    py34_0          
markupsafe                0.23                     py34_0          
matplotlib                1.4.3                np19py34_1          
menuinst                  1.0.4                    py34_0          
mistune                   0.7.1                    py34_0          
mock                      1.3.0                    py34_0          
multipledispatch          0.4.8                    py34_0          
nbconvert                 4.0.0                    py34_0          
nbformat                  4.0.1                    py34_0          
networkx                  1.10                     py34_0          
nltk                      3.0.5                    py34_0          
node-webkit               0.10.1                        0          
nose                      1.3.7                    py34_0          
notebook                  4.0.5                    py34_0          
numba                     0.21.0               np19py34_0          
numexpr                   2.4.4                np19py34_0          
numpy                     1.9.3                    py34_0          
odo                       0.3.4                    py34_0          
openpyxl                  2.0.2                    py34_0          
pandas                    0.16.2               np19py34_0          
patch                     2.5                           0          
path.py                   8.1.2                    py34_0          
patsy                     0.4.0                np19py34_0          
pbr                       1.3.0                    py34_0          
pep8                      1.6.2                    py34_0          
pickleshare               0.5                      py34_0          
pillow                    3.0.0                    py34_0          
pip                       7.1.2                    py34_0          
ply                       3.8                      py34_0          
psutil                    3.2.2                    py34_0          
py                        1.4.30                   py34_0          
pyasn1                    0.1.7                    py34_0          
pycosat                   0.6.1                    py34_0          
pycparser                 2.14                     py34_0          
pycrypto                  2.6.1                    py34_3          
pyflakes                  1.0.0                    py34_0          
pygments                  2.0.2                    py34_0          
pyopenssl                 0.15.1                   py34_1          
pyparsing                 2.0.3                    py34_0          
pyqt                      4.10.4                   py34_1          
pyreadline                2.1                      py34_0          
pytables                  3.2.2                np19py34_0          
pytest                    2.8.1                    py34_0          
python                    3.4.3                         0          
python-dateutil           2.4.2                    py34_0          
pytz                      2015.6                   py34_0          
pywin32                   219                      py34_0          
pyyaml                    3.11                     py34_2          
pyzmq                     14.7.0                   py34_0          
qtconsole                 4.0.1                    py34_0          
requests                  2.8.0                    py34_0          
rope                      0.9.4                    py34_1          
runipy                    0.1.3                    py34_0          
scikit-image              0.11.3               np19py34_0          
scikit-learn              0.16.1               np19py34_0          
scipy                     0.16.0               np19py34_0          
setuptools                18.3.2                   py34_0          
simplegeneric             0.8.1                    py34_0          
six                       1.10.0                   py34_0          
snowballstemmer           1.2.0                    py34_0          
sockjs-tornado            1.0.1                    py34_0          
sphinx                    1.2.3                    py34_0          
sphinx_rtd_theme          0.1.7                    py34_0          
spyder                    2.3.7                    py34_0          
spyder-app                2.3.7                    py34_0          
sqlalchemy                1.0.8                    py34_0          
statsmodels               0.6.1                np19py34_0          
sympy                     0.7.6.1                  py34_0          
toolz                     0.7.4                    py34_0          
tornado                   4.2.1                    py34_0          
traitlets                 4.0.0                    py34_0          
ujson                     1.33                     py34_0          
werkzeug                  0.10.4                   py34_0          
wheel                     0.26.0                   py34_1          
xlrd                      0.9.4                    py34_0          
xlsxwriter                0.7.5                    py34_0          
xlwings                   0.4.1                    py34_0          
xlwt                      1.0.0                    py34_0          
zlib                      1.2.8                         0          
```

**Comment by minrk** [comment] 2015-10-12 10:55
As the ImportError is meant to suggest, you lack the qtconsole package:

    conda install qtconsole

then launch with

    jupyter qtconsole

**Comment by duytrung** [comment] 2015-10-12 11:00
I tried your instruction:
The qtconsole package had already installed.
```

dell@DELL-PC C:\Users\dell
> conda install qtconsole
Fetching package metadata: ....
Solving package specifications: ..........
# All requested packages already installed.
# packages in environment at C:\MyPrograms\Anaconda3:
#
qtconsole                 4.0.1                    py34_0

dell@DELL-PC C:\Users\dell
> jupyter qtconsole
jupyter: 'qtconsole' is not a Jupyter command

dell@DELL-PC C:\Users\dell
```

**Comment by minrk** [comment] 2015-10-12 11:07
Hm, not sure why I didn't see it the first time. What does `python -m qtconsole` do?

**Comment by duytrung** [comment] 2015-10-12 11:14
Hmm, may be something wrong...
```
dell@DELL-PC C:\Users\dell
> python -m qtconsole
C:\MyPrograms\Anaconda3\python.exe: No module named qtconsole.__main__; 'qtconsole' is a package and cannot be directly executed

dell@DELL-PC C:\Users\dell
>
```

**Comment by minrk** [comment] 2015-10-12 12:56
Hm, that suggests a broken installation, since it certainly is not true. Can you remove and reinstall the qtconsole package, perhaps?

**Comment by takluyver** [comment] 2016-01-26 13:18
Closing as it's probably not a bug in IPython. Feel free to continue using the comments for troubleshooting.

**Closed by takluyver** 2016-01-26 13:18 UTC

**Comment by OW51** [comment] 2019-04-23 16:30
Problem statement Qtconsole import error or conflict.

This is the exact error message I was getting

File "uikit/ipython.py", line 5, in <module>
ImportError: No module named qt.console.rich_ipython_widget
[28603] Failed to execute script bosetap

you can dig into uikit/ipython.py and see there is an try catch block around the import of new vs old .

QT_API = os.environ.get('QT_API', None)
if QT_API not in [QT_API_PYSIDE, QT_API_PYSIDE2, QT_API_PYQT, QT_API_PYQT5, None]:
raise RuntimeError("Invalid Qt API %r, valid values are: %r, %r, %r, %r" %
(QT_API, QT_API_PYSIDE, QT_API_PYSIDE2, QT_API_PYQT, QT_API_PYQT5))
if QT_API is None:
api_opts = [QT_API_PYQT5, QT_API_PYSIDE2, QT_API_PYSIDE, QT_API_PYQT]
else:
api_opts = [QT_API]

step 1)
I started running things by hand at a python prompt and I convinced myself that qt.console was installed correctly.  If you find you can not do this.  Install the missing module.

Step 2) if you are using pyqt4 make sure you exclude pyqt5, pyside, and pyside2 modules in your pyinstaller spec file.  It might look something like this.  This goes in the analysis section
   excludes=['pyqtgraph.graphicsItems.PlotItem.plotConfigTemplate_pyqt5',
                'pyqtgraph.graphicsItems.PlotItem.plotConfigTemplate_pyqt5',
                'pyqtgraph.graphicsItems.ViewBox.axisCtrlTemplate_pyqt5',
                'pyqtgraph.GraphicsScene.exportDialogTemplate_pyqt5',
                'PyQt5',' PyQt5.QtCore','PyQt5.QtGui','PyQt5.QtPrintSupport',
                'PyQt5.QtSvg','PySide','PySide2'],

This might have been overkill.  Once I got it working, I didn’t want to touch it.  The optimization is left as an exercise for the reader.

Step3) I’m going to tell you the solution first and then how to get there.  The problem was that pyinstaller was putting my pyqt4 executables at the top level in the package.  Qtconsole was looking for them in a PyQt4 directory.  The following goes in the exe section of your spec file.

          a.binaries + [('PyQt4/QtCore.so','/usr/lib/python2.7/dist-packages/PyQt4/QtCore.so','BINARY'),
                ('PyQt4/QtGui.so','/usr/lib/python2.7/dist-packages/PyQt4/QtGui.so','BINARY'),
                ('PyQt4/QtOpenGL.so','/usr/lib/python2.7/dist-packages/PyQt4/QtOpenGL.so','BINARY'),
                ('PyQt4/QtSvg.so','/usr/lib/python2.7/dist-packages/PyQt4/QtSvg.so','BINARY'),
                ('PyQt4/QtTest.so','/usr/lib/python2.7/dist-packages/PyQt4/QtTest.so','BINARY'),
                ('PyQt4/QtXml.so','/usr/lib/python2.7/dist-packages/PyQt4/QtXml.so','BINARY')
                ],
So, the bad part about this solution is we now get warnings that we have the same executable in two places.  The optimization is left as an exercise for the reader.  Honestly, I haven’t figured out how to resolve this yet.  So, if you do… it would be nice to hear from you.
This is how I got to step 3.  I think this part is important.  I added this to my spec file just for development, not for the customer’s package.  The problem with developing the package was it was failing to run and then the tmp/<some random numbers and letters>  directory would remove itself.  I couldn’t see what the problem was.  I knew I had pyqt4 installed and that the application ran by hand.  It was very frustrating.  So, if you do the below to your spec file you will get a directory built instead of an executable.  That directory stays and you can peak inside and see what is going on.  Then, you are armed and dangerous to enable the solution.  Then when you have it working, you revert this to develop an executable for your customer.

exe = EXE(pyz,
          a.scripts,
         [],
          exclude_binaries=True,
          name='bosetap',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )

coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='bosetap')

Special thanks to my boss as I banged my head against this for 1 week.  Happy Trails.
