### ISSUE TITLE
IPython 4.1.0 broke rescuing into interactive mode after exceptions

### ISSUE THREAD

**Issue by vincentwoo** [ipython/ipython#9297] opened 2016-03-05 11:19 UTC
I use IPython as a dependable way to halt program execution at time of error and deposit me in an IPython shell where the exception occurred. However, I believe this behavior broke in 4.1.0.

Using the example script:

```python
x = 420
null.asdf
```

Running this in 4.0.3 works quite well:

```
root@b0b47c577357:~# ipython -i test2.py
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/home/coderpad/test2.py in <module>()
      1 x = 420
----> 2 null.asdf

NameError: name 'null' is not defined

In [1]: x
Out[1]: 420

In [2]: 
```

However, that same script run in 4.1.0 (and beyond) immediately terminates and returns to the shell:

```
root@b0b47c577357:~# ipython -i test2.py
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/home/coderpad/test2.py in <module>()
      1 x = 420
----> 2 null.asdf

NameError: name 'null' is not defined
root@b0b47c577357:~#
```

I am testing this behavior in clean ubuntu 14.04 docker containers with not much else installed. Was this an intended change? I can't find any information on it in news/release notes, etc.

**Comment by minrk** [comment] 2016-03-05 11:47
Duplicate of #9223, fixed by #9225.

**Closed by minrk** 2016-03-05 11:47 UTC

**Comment by vincentwoo** [comment] 2016-03-05 12:07
Whoops, my bad.

**Comment by minrk** [comment] 2016-03-15 14:51
No problem, sorry for the bug. Hopefully we'll get a release out with the fix soon.
