### ISSUE TITLE
prompt_toolkit breaks matplotlib

### ISSUE THREAD

**Issue by montefra** [ipython/ipython#9659] opened 2016-06-24 19:56 UTC
I have been experimenting with the ipython 5 release candidates and I like it a lot.
Until I try to make some plots and visualize it.

As a test I run:

    import matplotlib.pyplot as plt; plt.ion(); plt.plot([1, 2])

In ipython 4.2.0 it shows a very nice plot, while in 5.0.0rc4 the plot window fires up but it just contains the lines of my konsole below the window:
![screenshot_20160624_215706](https://cloud.githubusercontent.com/assets/1394820/16349084/d81fecca-3a56-11e6-9f25-b8c3b8a0df16.png)

Git bisects indicate the following:

67d7c405d3ee45570b44d4c37a5c23b5f21068d8 is the first bad commit
commit 67d7c405d3ee45570b44d4c37a5c23b5f21068d8
Author: Thomas Kluyver <thomas@kluyver.me.uk>
Date:   Mon Feb 22 17:02:41 2016 +0000

    Switch over to use prompt_toolkit in IPython

:040000 040000 716f84bf64b295c05b6394d096f3d031c446a1fa 5a9f49fcaa2b77fb872c166afe53f69f38897344 M      IPython
:100755 100755 c16bd1d1ed4817707bdac7b1cc85587e4675e47c fe58b5fd2723aca2d6d334eddef96f8d0df9a1ab M      setup.py

I have matplotlib to use qt5agg as backend.
I am on OpenSUSE Tumbleweed, with qt5 5.6.0-1.2

If I use qt4 as backend, the commit before the above works and 67d7c405d3ee45570b44d4c37a5c23b5f21068d8 don't even show the figure window

**Comment by takluyver** [comment] 2016-06-24 20:03
Can you try running `%matplotlib qt` before plotting to enable our event loop integration?

**Comment by montefra** [comment] 2016-06-24 21:50
running ``%matplotlib qt`` before shows the plots correctly with qt4 and qt5 both on the offending commit and in the one just before that.

I forgot one thing, which is way more annoying than the fact that the plots are not shown: the only way to close the figure window is to go out of ipython. 
If I click a lot on the close button of the figure window I get:

> Application " " is not responding
You tried to close window "Figure 1" from application " " (Process ID: 6714) but the application is not responding.
Do you want to terminate this application? 
Warning: Terminating the application will close all of its child windows. Any unsaved data will be lost.

If I then click to terminate the application ipython gets killed:

    In [2]: import matplotlib.pyplot as plt; plt.ion(); plt.plot([1, 2])Killed
    (ipython_db)(137) susefra@ex-lt21:~ ->

**Comment by takluyver** [comment] 2016-06-26 18:22
Strange, it's working OK for me.  Can you interact with the plot in the window at all (e.g. pan/zoom)?

**Comment by montefra** [comment] 2016-06-26 18:38
@takluyver : the menus don't open. I cannot say if I can interact as I only see the part of the konsole that was under the window (see screenshot). I doubt, though, as the only way to close the window is to kill ipython. Tomorrow I can give a try on my kubuntu machine at work.

**Comment by jenshnielsen** [comment] 2016-06-28 11:26
I have not reproduced this specific issue but a related issue seems to be that the OSX backend does not play well with IPython 5 beta. 

Doing some thing simple like:

```
%matplotlib osx
import matplotlib.pyplot as plt
plt.plot(range(10)
```
and closing the figure results in a figure hanging. 

The same works ok with qt4/5 and gtk3

i.e. 
```
%matplotlib qt5
import matplotlib.pyplot as plt
plt.plot(range(10)
```

**Comment by takluyver** [comment] 2016-06-28 11:42
The OSX inputhook code is here: https://github.com/ipython/ipython/blob/master/IPython/terminal/pt_inputhooks/osx.py , but there's not much I can do with it.

**Comment by jenshnielsen** [comment] 2016-06-28 11:58
Thanks @takluyver I will try to get to the bottom of it when I have a bit of spare time

**Comment by montefra** [comment] 2016-06-28 15:51
I just tried on Kubuntu 15.10 and I see exactly the same behaviour.

However I've noticed one detail: if I do ``ctrl+d`` in the ipython console, the plot shows up and I can interact.
If I type ``n`` to ``Do you really want to exit ([y]/n)?`` I cannot interact any more with the plot. 
But if I click, e.g., on the save button, no extra windows come up, until I hit ``ctrl+d``. Then I see the image and I can save the figure.

**Comment by takluyver** [comment] 2016-06-28 16:29
Which backend is this with? Have you done the relevant `%matplotlib <backend>` command for that backend?

**Comment by montefra** [comment] 2016-06-28 19:23
@takluyver : same as before, just different distro
Backends: qt5agg and qt4agg.
With ``%matplotlib qt`` all good.
Without: works on ipython v4.2 but does not v5.
The bisect I reported initially shows the the issue starts with the introduction of the prompt_toolkit.
This points me to some bad interaction between the prompt and qt event loops.

[From the documentation](http://ipython.readthedocs.io/en/stable/interactive/plotting.html?highlight=matplotlib) I see:

> To set this up, before any plotting is performed you must execute the %matplotlib magic command. 

So probably the question is: why was plotting working before (I never had issues, and I'm using ipython since some 0.x version) and now one **must** use the magic command?

**Comment by tacaswell** [comment] 2016-06-28 19:40
The underlying problem here is that to get responsive GUI windows and a responsive repl you have to integrate two event loops (the GUI event loop so it responds to mouse/keyboard events) and the terminal event loop (which echos when you type and executes when you hit enter).

It was only working without the magic in earlier version of IPython because PyQt installs it's own input hook which is picked up by the core python readline implementation of the repl.  It is a that this worked with PyQt (if I recall correctly tk also install's its own (as it is the _reason_ that the input hook exists) as does gtk, but pyside and wx do not).  

With IPython moving over to prompt toolkit it does not use the readline repl and hence does not make use of `PyOS_InputHook` (which is a void pointer in the right place for readline to find it).

The 'official' position of mpl has always been that to get reliable interactive non-blocking plotting in the repl is to use the IPython magics.

**Comment by montefra** [comment] 2016-06-28 20:16
@tacaswell : thank you very much for the detailed explanation.

I'm wondering how many people don't use the ``%matplotlib`` magic, because up to now plotting just works.
If there are more than a handful of people like me, will be annoying for the users, that will have to remember to type the magic command before importing matplotlib, and for the developers, that will have to go through issues like this one countless times.

**Comment by takluyver** [comment] 2016-06-28 20:22
Thanks @tacaswell, that clarifies things.

Yes, our position is also that you need to use the `%matplotlib` magic to integrate the event loops. That certain backends previously worked without that was a happy coincidence, but with the new terminal interface, you'll need to use the magic.

If it were to be automatic, I think that would make most sense to do that in matplotlib - when it was about to create an interactive plot window, it could check 'am I in IPython?' and ensure that the relevant event loop integration is selected if so. This could also fit in with our goal of making `%matplotlib inline` or `%matplotlib notebook` the default when IPython is running as a kernel.

**Comment by tacaswell** [comment] 2016-06-30 01:35
I'm glad that helped!  The input hook stuff is something that I think make sense to me, but every time I try to explain it feels like it is coming out as jibberish.

We are slowly making progress to the point where asking if IPython is in namespace and then calling the code to setup the hook is reasonable.

**Comment by montefra** [comment] 2016-07-02 05:55
@takluyver : the ``inline`` or ``notebook`` backends are only for the notebook, isn't it? What if you are running in the standard ipython terminal?

> We are slowly making progress to the point where asking if IPython is in namespace and then calling the code to setup the hook is reasonable.

@tacaswell : are there issues and/or PR about it? If yes, can you point to them here?

And then we can close the issue, I guess.

**Comment by takluyver** [comment] 2016-07-02 09:16
`notebook` is only for the notebook, `inline` can work in other Jupyter frontends. However, I was making a distinction between IPython running as a kernel (for Jupyter frontends) and IPython running in the terminal, which is what's in question here.

**Comment by dwyatte** [comment] 2016-07-09 14:43
This is related to ion() for me (Mac OS X 10.10.5, Python 2.7.10, matplotlib 1.5.1 from pypi). 

When doing:
```
import matplotlib.pyplot as plt
plt.ion()
plt.plot([1, 2])
```

I get a figure window that does not render and cannot be closed except by exiting my ipython session.

But doing:
```
%matplotlib osx
import matplotlib.pyplot as plt
plt.plot([1, 2])

Works as expected.

**Comment by montefra** [comment] 2016-07-12 15:40
As I was afraid, the issue is [beginning to surface](https://plus.google.com/104621157278332750444/posts/ARJFQsBEAXx).

I should begin to track ipython stackoverflow and get lots of reputation :wink:

**Comment by tacaswell** [comment] 2016-07-12 16:19
I have single-vote close-as-duplicate power for anything labeled as matplotlib, @montefra if you want to write a cononical answer and point me at it :smiling_imp: .

**Comment by tacaswell** [comment] 2016-07-12 16:38
I wrote an answer on GH or on SO?

**Comment by montefra** [comment] 2016-07-12 16:43
You described the cause of the issue here [14 days ago](https://github.com/ipython/ipython/issues/9659#issuecomment-229159278)

**Comment by aasensio** [comment] 2016-07-27 08:34
Adding to this issue, in previous versions of IPython, running a script through the %run magic when matplotlib was in interactive mode, also updated the figures without the necessity to invoke `show`. However, even though using the magic %matplotlib solves the issue as said before, no plot is shown when running a script that generates figures using %run. I know that %run is used to run scripts non-interactively but, is there any way to return to the previous behavior?

**Comment by tacaswell** [comment] 2016-07-27 21:19
Explictily call `show` and (possibly) spin the GUI event loop.

**Comment by tacaswell** [comment] 2016-07-28 18:19
On a bit more consideration, I think explicitly spinning the GUI event loop in code you want to update during a `%run` call.

**Comment by takluyver** [comment] 2016-08-10 10:19
Closing as it mostly seems to be solved by using the `%matplotlib` magic, which was always recommended. matplotlib/matplotlib#6734 should make that unnecessary with matplotlib 2.

If there are still problems you're encountering, please find or file separate issues about those so we can debug them.

**Closed by takluyver** 2016-08-10 10:19 UTC
