### ISSUE TITLE
Autocompletion: Do not complete non-member-modules when completing on a module

### ISSUE THREAD

**Issue by zachriggle** [ipython/ipython#13570] opened 2022-03-04 06:23 UTC
I love IPython!  Its autocompletion is great, but when autocompleting `submodule.x<tab>` it would be nice if the only things displayed in the auto-complete are module members.

It should be easy to check `xyz.__module__` versus `submodule.__name__` to do this.  It seems like there are configuration points that I might be able to do this already, but it would be nice to have!

```
>>> rich.__name__
'rich'
>>> rich.pretty.__name__
'rich.pretty'
>>> rich.pretty.pprint.__module__
'rich.pretty'
>>> rich.pretty.pick_bool.__module__
'rich._pick'
```

Ideally, `pick_bool` would not show up in completion on the CLI.

**Comment by MrMino** [comment] 2022-03-05 00:37
Hi, we're glad to here you like it!

Regarding your issue: isn't `pick_bool` actually a member of the module `pretty` here?

```
In [6]: 'pick_bool' in dir(rich.pretty)
Out[6]: True
```

**Comment by MrMino** [comment] 2022-03-27 16:39
In the interest of keeping the issue tracker cleaner, I'm going to close this issue. As I mentioned above, it seems to be the expected behavior - by Python's definition of "member", `pick_bool` _is_ a member of module `pretty`.

If you think otherwise, you can always ping us here to reopen the issue.

**Closed by MrMino** 2022-03-27 16:39 UTC
Labels: tab-completion, needs-info
