### ISSUE TITLE
docker build . broken on java install

### ISSUE THREAD

**Issue by kbroughton** [ipython/ipython#8740] opened 2015-08-18 14:39 UTC
To reproduce, on a system that has no docker cache of the jupyter/demo image

```
Step 16 : RUN apt-get install -y --no-install-recommends openjdk-7-jre-headless
 ---> Running in 860915f1a3ea
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  ca-certificates-java java-common libasyncns0 libavahi-client3
  libavahi-common-data libavahi-common3 libcups2 libflac8 libjson-c2 libnspr4
  libnss3 libogg0 libpcsclite1 libpulse0 libsndfile1 libvorbis0a libvorbisenc2
  libwrap0 libx11-xcb1 libxi6 libxtst6 tzdata tzdata-java
Suggested packages:
  default-jre equivs cups-common pcscd pulseaudio icedtea-7-jre-jamvm
  libnss-mdns sun-java6-fonts fonts-ipafont-gothic fonts-ipafont-mincho
  ttf-wqy-microhei ttf-wqy-zenhei fonts-indic
Recommended packages:
  tcpd
The following NEW packages will be installed:
  ca-certificates-java java-common libasyncns0 libavahi-client3
  libavahi-common-data libavahi-common3 libcups2 libflac8 libjson-c2 libnspr4
  libnss3 libogg0 libpcsclite1 libpulse0 libsndfile1 libvorbis0a libvorbisenc2
  libwrap0 libx11-xcb1 libxi6 libxtst6 openjdk-7-jre-headless tzdata-java
The following packages will be upgraded:
  tzdata
1 upgraded, 23 newly installed, 0 to remove and 9 not upgraded.
Need to get 43.0 MB of archives.
After this operation, 68.1 MB of additional disk space will be used.
Get:1 http://security.debian.org/ jessie/updates/main libcups2 amd64 1.7.5-11+deb8u1 [283 kB]
Err http://security.debian.org/ jessie/updates/main openjdk-7-jre-headless amd64 7u79-2.5.5-1~deb8u1
  404  Not Found [IP: 128.31.0.63 80]
Get:2 http://httpredir.debian.org/debian/ jessie/main libjson-c2 amd64 0.11-4 [24.8 kB]
Get:3 http://httpredir.debian.org/debian/ jessie/main libwrap0 amd64 7.6.q-25 [58.5 kB]
Get:4 http://httpredir.debian.org/debian/ jessie/main libasyncns0 amd64 0.8-5 [12.5 kB]
Get:5 http://httpredir.debian.org/debian/ jessie/main libavahi-common-data amd64 0.6.31-5 [98.6 kB]
Get:6 http://httpredir.debian.org/debian/ jessie/main libavahi-common3 amd64 0.6.31-5 [51.1 kB]
Get:7 http://httpredir.debian.org/debian/ jessie/main libavahi-client3 amd64 0.6.31-5 [54.4 kB]
Get:8 http://httpredir.debian.org/debian/ jessie/main libogg0 amd64 1.3.2-1 [19.9 kB]
Get:9 http://httpredir.debian.org/debian/ jessie/main libflac8 amd64 1.3.0-3 [89.3 kB]
Get:10 http://httpredir.debian.org/debian/ jessie/main libnspr4 amd64 2:4.10.7-1 [116 kB]
Get:11 http://httpredir.debian.org/debian/ jessie/main libnss3 amd64 2:3.17.2-1.1 [1130 kB]
Get:12 http://httpredir.debian.org/debian/ jessie/main libpcsclite1 amd64 1.8.13-1 [56.2 kB]
Get:13 http://httpredir.debian.org/debian/ jessie/main libvorbis0a amd64 1.3.4-2 [92.9 kB]
Get:14 http://httpredir.debian.org/debian/ jessie/main libvorbisenc2 amd64 1.3.4-2 [77.9 kB]
Get:15 http://httpredir.debian.org/debian/ jessie/main libsndfile1 amd64 1.0.25-9.1 [214 kB]
Get:16 http://httpredir.debian.org/debian/ jessie/main libx11-xcb1 amd64 2:1.6.2-3 [163 kB]
Get:17 http://httpredir.debian.org/debian/ jessie/main libxi6 amd64 2:1.7.4-1+b2 [79.7 kB]
Get:18 http://httpredir.debian.org/debian/ jessie/main libxtst6 amd64 2:1.2.2-1+b1 [27.3 kB]
Get:19 http://httpredir.debian.org/debian/ jessie/main libpulse0 amd64 5.0-13 [255 kB]
Get:20 http://httpredir.debian.org/debian/ jessie/main ca-certificates-java all 20140324 [13.7 kB]
Err http://httpredir.debian.org/debian/ jessie-updates/main tzdata all 2015e-0+deb8u1
  404  Not Found [IP: 54.192.145.48 80]
Err http://httpredir.debian.org/debian/ jessie-updates/main tzdata-java all 2015e-0+deb8u1
  404  Not Found [IP: 54.192.145.48 80]
Get:21 http://httpredir.debian.org/debian/ jessie/main java-common all 0.52 [136 kB]
Fetched 3054 kB in 4s (709 kB/s)
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/t/tzdata/tzdata_2015e-0+deb8u1_all.deb  404  Not Found [IP: 54.192.145.48 80]

E: Failed to fetch http://httpredir.debian.org/debian/pool/main/t/tzdata/tzdata-java_2015e-0+deb8u1_all.deb  404  Not Found [IP: 54.192.145.48 80]

E: Failed to fetch http://security.debian.org/pool/updates/main/o/openjdk-7/openjdk-7-jre-headless_7u79-2.5.5-1~deb8u1_amd64.deb  404  Not Found [IP: 128.31.0.63 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

------------------------------

If I add apt-get update to the first apt line in Dockerfile

Step 36 : RUN $CONDA_DIR/envs/python2/bin/python $CONDA_DIR/envs/python2/bin/ipython kernelspec install-self --user
 ---> Running in 53d78d8e9260
Traceback (most recent call last):
  File "/opt/conda/envs/python2/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named jupyter_client.kernelspecapp
```

**Comment by minrk** [comment] 2015-10-12 11:46
cc @rgbkrk @parente any ideas? I expect this is fixed on more recent docker-stacks, no?

**Comment by parente** [comment] 2015-10-12 11:55
Yes. We fixed this one. I think this is a dupe of one filed against docker-demo-image.

**Closed** 2015-10-12 12:17 UTC
