### ISSUE TITLE
%cpaste garbles long inputs

### ISSUE THREAD

**Issue by nilsbecker** [ipython/ipython#7042] opened 2014-11-26 14:33 UTC
i am using console ipython with %cpaste, getting input from vim-slime via tmux. this works fine for smallish selections of pasted code. for pasted fragments above ~1024 characters, the input gets garbled. it is not truncated but the linebreaks appear not to be there anymore for the last pasted lines.

the problem is not with vim-slime or with tmux: when sending code to `cat -` no garbling occurs even with long text fragments. also, the same code, broken down to smaller bits can be %cpasted successfully.

IPython 2.2.0, ITerm2 on os x 10.9

**Comment by nilsbecker** [comment] 2015-02-27 12:41
actually, %cpaste-ing long inputs from the system clipboard in mac os x does work. 

so this does have something to do with tmux or vim-slime, but in a way that does not affect the simple command `cat -`

**Comment by argoneus** [comment] 2015-02-27 15:58
I'm seeing this issue as well, see https://github.com/jpalardy/vim-slime/issues/71.  In my case, unlike @nilsbecker, I still see the issue if I copy from the clipboard.

**Comment by nilsbecker** [comment] 2015-02-27 16:08
update: i also see it with manual copy-paste into plain ipython running in iTerm2 on os x. the threshold for when it starts to occur is a bit higher than via vim-slime, but it does still occur. so definitely, this looks like a bug in ipython itself.

**Comment by nilsbecker** [comment] 2015-02-27 16:12
update: it works fine with copy-paste in os x Terminal.app (!) @argoneus which terminal emulator are you using?

**Comment by argoneus** [comment] 2015-02-27 16:46
I'm using Terminal.app

**Comment by nilsbecker** [comment] 2015-02-27 16:55
ok, so my results in summary:

manual copy- %cpaste works on Terminal.app for one example of a 380 line function with 27k characters.

using %cpaste via vim-slime into Terminal.app does _not_ work for a 35 line, 1.5k characters function

likewise, %cpaste via vim-slime does not work into iTerm2; neither does manual copy-paste into iTerm2, both fail at a few thousand characters.

**Comment by meawoppl** [comment] 2015-06-15 19:31
I have had this similar problem with bash and gterm.  It has something to do with input length.  Somewhere c. 500-1000 characters, things fall over.

**Comment by nilsbecker** [comment] 2015-06-15 19:33
i have since switched to vim-cellmode. this uses %load from temporary files instead of the fragile %cpaste. it's quite reliable.

**Comment by meawoppl** [comment] 2015-06-15 22:41
might as well just run -i?

**Comment by minrk** [comment] 2015-07-11 17:16
Since this occurs in bash as well, my guess is that it's an issue with readline.

**Comment by meawoppl** [comment] 2015-07-11 18:15
@minrk, can you point me to the relevant code snippets?  This has been a
thorn for me for a while now.

--Matthew Goodman

=====================
Check Out My Website: http://craneium.net
Find me on LinkedIn: http://tinyurl.com/d6wlch

**Comment by minrk** [comment] 2015-07-11 22:28
@meawoppl I'm not sure. I've never been able to reproduce this. 64k character lines work fine in cpaste for me.

**Comment by meawoppl** [comment] 2015-07-15 18:44
Interesting, @minrk you are on osx then?

**Comment by minrk** [comment] 2015-07-15 18:53
I am, 10.10.4, using Terminal.app.

**Comment by kdheepak89** [comment] 2015-09-13 03:47
I am having the exact same issue as @nilsbecker.
Tested using Terminal.app and iTerm.app

**Comment by ushuz** [comment] 2015-11-13 04:49
Having the same issue with iTerm 2.1.4 + tmux 1.6 + ipython 4.0.0. Pasting really long text in `nano` `vim` is OK. It seems that there is a 4k limit on `%cpaste`.

**Comment by kobejohn** [comment] 2016-05-17 02:16
It would be nice to have this solved. As others have said, pasting the same text into nano / vim etc. works. **The most insight I got is that it is a stateful problem (behavior changes continuously) and related to new lines.** As I try to make a minimal reproducible example, the behavior keeps shifting. If I remove all new lines, I seem to be able to paste whatever I want.

Additionally, many garbled inputs still work somehow so what is being displayed does not match what ipython is using. However beyond a certain length or some other criterion I haven't figured out, ipython fails to interpret the pasted input correctly, resulting in syntax errors or whatever errors come out of the mangled text.

Interestingly, I get different behavior on the same input in these cases:

- pasting into ipython with iterm2 (osx --> ssh --> linux bash session) garbles but works
- pasting into ipython with iterm2 (osx --> local bash session) causes error
- pasting into ipython with all text on a single line works in all cases

Here is the simple input I used. I wanted to reduce it more carefully but don't have the time. I think it is important to note again that the garbling behavior does not require nearly this much text. I got it to garble with 128 characters sometimes.

    breaking_list = ['12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890',
                     '12345678901234567890123456789012345678901234567890']

**Comment by takluyver** [comment] 2016-05-17 09:11
In master, using cpaste is no longer necessary, and you can paste multiple lines directly into the shell, thanks to prompt_toolkit. Other people have found that this handles long input better.

I don't think we can fix this for %cpaste on our side, as it's most likely something to do with the terminal emulator and readline.

**Comment by kobejohn** [comment] 2016-05-17 14:28
@takluyver Ok that will be nice. Thanks for the heads up. For the benefit of people coming here from the internets, how will we know when the new behavior is available on the standard release?

**Comment by takluyver** [comment] 2016-05-17 14:50
It will be in IPython 5. When you notice syntax highlighting in your terminal, you can paste away ;-)

**Comment by ivanov** [comment] 2016-10-21 22:01
IPython 5 has been released, so I am closing this issue, along with #9454

**Closed by ivanov** 2016-10-21 22:01 UTC
Labels: core

**Comment by javadba** [comment] 2017-07-13 17:03
This is still broken in `ipython 5.4.1` on Sierra.  I am using iTerm2.  The breakage is for a low number of characters - several hundred-ish
