### ISSUE TITLE
Last updated date on /tree page

### ISSUE THREAD

**Issue by kylepolich** [ipython/ipython#8352] opened 2015-04-21 17:57 UTC
This is a feature request.

So long as one's filenames are not quite long, on most monitors, there's a lot of horizontal space between the notebook name and the "Running" message (if applicable).

In very collaborative environments, its helpful to know when a notebook may have been updated, especially when there are many notebooks in a directory.  It would be a nice feature to show the last updated date in this available whitespace.

One of my colleagues looked into it with the intent of making an extension to do this.  An extension seems like the right approach because this feature might not be appreciated by everyone.  However, his analysis was that there was no easy way to do this.

**Comment by minrk** [comment] 2015-04-21 18:48
Closing as duplicate of #1547

**Closed by minrk** 2015-04-21 18:48 UTC
