### ISSUE TITLE
Windows; can't input some Lithuanian characters

### ISSUE THREAD

**Issue by lv-gh** [ipython/ipython#10004] opened 2016-10-14 01:34 UTC
OS: Microsoft Windows [Version **10.0.14393**]
IPython: **5.1.0**  
Python **3.5.2** (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
System Locale: **lt;Lithuanian**
chcp: **Active code page: 775**
Input method: **Lithuanian**

Here are two keyboard layouts: **English**:
![en_kb](https://cloud.githubusercontent.com/assets/3296959/19372711/1d79a23a-91c7-11e6-83e7-514ea042438d.PNG)
and **Lithuanian**:
![lt_kb](https://cloud.githubusercontent.com/assets/3296959/19372712/1d91f0ba-91c7-11e6-87f9-c736b252485d.PNG)

Can't input characters: '**ą**' (1), '**č**' (2), '**ę**' (3), '**ė**' (4). 
Other keys works: 'į' (5), 'š' (6), 'ų' (7), 'ū' (8), 'ž' (+/=)
Keypressing invokes some actions without any visible char on the screen; e.g. č ('2') acts like 'Enter', 'Ą' (Shift+1) maybe like 'Ctrl+D' (Do you really want to exit ([y]/n)?)

Separately tried win_unicode_console (thought it's in action):
> python -i -m run

and everything is fine.

**Comment by takluyver** [comment] 2016-10-14 13:16
That's weird, because we do use win_unicode_console. @Drekin , any ideas on this?

**Comment by Drekin** [comment] 2016-10-14 15:13
Well, this is about input, right? But for input you use some readline hook to have autocompletion, etc., so `win_unicode_console` is not used in this case. I can reproduce the issue with my Czech locale. `sys.stdin.readline()` works, `input()` also works, whereas directly typing to console not: in my case, ě (key 2) puts the character but does not increment the cursor, and č (key 4) behaves like Enter. It seems that this is connected with the readline hook you are using (configuration or bug in `prompt_toolkit`?).

**Comment by takluyver** [comment] 2016-10-14 15:27
Aha, right. Input goes through prompt_toolkit, so the expert we need to invoke is @jonathanslenders :-). @lv-gh - can you make sure your prompt_toolkit is up to date (1.0.7 is currently the lastest).

**Comment by lv-gh** [comment] 2016-10-14 15:27
Some crude debugging (promp_toolkit/interface.py:feed_key()):

> feed_key(), key_press:  KeyPress(key=Key('<C-E>'), data='ą')
 feed_key(), key_press:  KeyPress(key=Key('<C-D>'), data='Ą')
feed_key(), key_press:  KeyPress(key=Key('<C-J>'), data='\n') # č
feed_key(), key_press:  KeyPress(key=Key('<C-Y>'), data='ę')
feed_key(), key_press:  KeyPress(key=Key('<C-X>'), data='Ę')
feed_key(), key_press:  KeyPress(key=Key('<C-W>'), data='ė')
feed_key(), key_press:  KeyPress(key=Key('<C-V>'), data='Ė')

**Comment by lv-gh** [comment] 2016-10-14 15:33
C:\Python64\3.5>python.exe -m pip freeze
colorama==0.3.7
decorator==4.0.10
ipython==5.1.0
ipython-genutils==0.1.0
pickleshare==0.7.4
pip-autoremove==0.9.0
prompt-toolkit==1.0.7
Pygments==2.1.3
simplegeneric==0.8.1
six==1.10.0
traitlets==4.3.1
virtualenv==15.0.3
wcwidth==0.1.7
win-unicode-console==0.5

**Comment by jonathanslenders** [comment] 2016-10-14 15:58
Hi @lv-gh,

Maybe it's the same as this issue? https://github.com/jonathanslenders/python-prompt-toolkit/issues/389
Could you try the patch that was proposed there? (Replace ``ascii_char in self.mappings`` by ``u_char.encode("utf8") in self.mappings`` in win32_input.py)

**Comment by lv-gh** [comment] 2016-10-14 16:20
Hi, @jonathanslenders,
Thanks, that seems to solve my/this issue. Here is actual patch:
```
--- prompt_toolkit/terminal/win32_input.py.orig	2016-10-14 19:12:10.347119900 +0300
+++ prompt_toolkit/terminal/win32_input.py	2016-10-14 19:10:56.506989100 +0300
@@ -225,7 +225,8 @@
             if ev.VirtualKeyCode in self.keycodes:
                 result = KeyPress(self.keycodes[ev.VirtualKeyCode], '')
         else:
-            if ascii_char in self.mappings:
+            if u_char.encode("utf8") in self.mappings:
+            #if ascii_char in self.mappings:
                 if self.mappings[ascii_char] == Keys.ControlJ:
                     u_char = '\n'  # Windows sends \n, turn into \r for unix compatibility.
                 result = KeyPress(self.mappings[ascii_char], u_char)

```

**Comment by jonathanslenders** [comment] 2016-10-16 11:21
Hi @lv-gh,

This should be fixed in this commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/5ab81d7aa5a8081725fd21563b489713719ab7dd
Could you try the latest prompt_toolkit master?
Thanks.

**Comment by lv-gh** [comment] 2016-10-16 21:18
@jonathanslenders 
Confirming: updated prompt_toolkit works fine.

**Closed** 2016-10-16 21:22 UTC
