### ISSUE TITLE
OperationalError: Could not decode to UTF-8 column 'kernel_id'

### ISSUE THREAD

**Issue by ghost** [ipython/ipython#10295] opened 2017-02-16 01:20 UTC
hello, 

I keep getting errors whenever I creatre a notebook. 
the error meassage is as below.
I am working on unix and my python version is 2.7.6 
And additional info is 
```
[rna@dlfrontend ~]$ python -c 'import IPython; print(IPython.sys_info())'
{'commit_hash': '681fd77',
 'commit_source': 'installation',
 'default_encoding': 'ISO-8859-15',
 'ipython_path': '/home/rna/.local/lib/python2.7/site-packages/IPython',
 'ipython_version': '2.1.0',
 'os_name': 'posix',
 'platform': 'Linux-2.6.32-279.14.1.el6.x86_64-x86_64-with-centos-6.3-Final',
 'sys_executable': '/home/rna/src/Python-2.7.6/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.6 (default, Feb 15 2017, 18:29:08) \n[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)]'}
```
can anyone help?

Thank you in advance.

best regards,
########################################
```
2017-02-16 10:12:16.535 [NotebookApp] ERROR | Unhandled error in API request
Traceback (most recent call last):
  File "/home/rna/.local/lib/python2.7/site-packages/IPython/html/base/handlers.py", line 286, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/rna/.local/lib/python2.7/site-packages/IPython/html/services/sessions/handlers.py", line 66, in post
    model = sm.create_session(name=name, path=path, kernel_id=kernel_id)
  File "/home/rna/.local/lib/python2.7/site-packages/IPython/html/services/sessions/sessionmanager.py", line 75, in create_session
    return self.save_session(session_id, name=name, path=path, kernel_id=kernel_id)
  File "/home/rna/.local/lib/python2.7/site-packages/IPython/html/services/sessions/sessionmanager.py", line 103, in save_session
    return self.get_session(session_id=session_id)
  File "/home/rna/.local/lib/python2.7/site-packages/IPython/html/services/sessions/sessionmanager.py", line 134, in get_session
    self.cursor.execute(query, list(kwargs.values()))
OperationalError: Could not decode to UTF-8 column 'kernel_id' with text '񧹐³೽¹𮼰°౽´𹾐­񧻐£ල¡þ´᤾¡೹❳'
ERROR:tornado.application:Uncaught exception POST /api/sessions (211.174.205.132)
HTTPServerRequest(protocol='http', host='211.174.205.93:9999', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='211.174.205.132', headers={'Content-Length': '58', 'Accept-Language': 'ko-KR', 'Accept-Encoding': 'gzip, deflate', 'Host': '211.174.205.93:9999', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko', 'Dnt': '1', 'Connection': 'Keep-Alive', 'X-Requested-With': 'XMLHttpRequest', 'Cache-Control': 'no-cache', 'Referer': 'http://211.174.205.93:9999/notebooks/shin/test/Untitled1.ipynb', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
Traceback (most recent call last):
  File "/home/rna/.local/lib/python2.7/site-packages/tornado-4.1-py2.7-linux-x86_64.egg/tornado/web.py", line 1346, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/rna/.local/lib/python2.7/site-packages/tornado-4.1-py2.7-linux-x86_64.egg/tornado/web.py", line 2626, in wrapper
    return method(self, *args, **kwargs)
  File "/home/rna/.local/lib/python2.7/site-packages/IPython/html/base/handlers.py", line 301, in wrapper
    self.finish(json.dumps(reply))
  File "/home/rna/local/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/home/rna/local/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/rna/local/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfd in position 1025: invalid start byte
ERROR:tornado.access:{
  "Content-Length": "58", 
  "Accept-Language": "ko-KR", 
  "Accept-Encoding": "gzip, deflate", 
  "Connection": "Keep-Alive", 
  "Accept": "application/json, text/javascript, */*; q=0.01", 
  "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko", 
  "Dnt": "1", 
  "Host": "211.174.205.93:9999", 
  "X-Requested-With": "XMLHttpRequest", 
  "Cache-Control": "no-cache", 
  "Referer": "http://211.174.205.93:9999/notebooks/shin/test/Untitled1.ipynb", 
  "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"
}
```

**Comment by Carreau** [comment] 2017-02-16 06:26
Hi there, 

Thanks for your bug report. IPython 2.1 was released mid 2014, and further version of the 2.x branch (up to 2.4) containing bugfixes were released as well. So I would suggest trying at least these new-er version.

IPython (and now Jupyter) have had major upgrade since then, the notebook is currently in version 4.x and IPython in version 5.x versions older than that are not supported and don't get bugfixes. If it's a bug on our side it has either already been fixed in more recent versions (likely), or we'll be happy to fix it if it can be reproduced on more recent versions.

Regardless, I would try to nuke sql files that should be in your `~/.ipython` directory, I'm unsure which one(s) as this version of the codebase is about 3 years old.  (or nuke everything except your config files)

Hope that will help.

**Comment by takluyver** [comment] 2017-02-16 11:12
> Regardless, I would try to nuke sql files that should be in your ~/.ipython directory, I'm unsure which one(s) as this version of the codebase is about 3 years old. (or nuke everything except your config files)

I think that's the session database, which IIRC was always created in memory. So I'm not sure that removing files helps here. I would definitely recommend upgrading, though.

**Closed** 2022-06-16 15:33 UTC
