### ISSUE TITLE
Tooltip for class constructors gone in IPython 3.0

### ISSUE THREAD

**Issue by netheril96** [ipython/ipython#7896] opened 2015-02-28 06:58 UTC
The IPython 3.0 upgrade now shows less helpful tooltips. In particular, tooltips for class constructors are now gone.

This is what we get in IPython 2.4:

![ipython2 4](https://cloud.githubusercontent.com/assets/836839/6425205/ef719e42-bf59-11e4-9611-cdd66ff001e7.png)

And this is what we get now:

![ipython3 0](https://cloud.githubusercontent.com/assets/836839/6425211/0966264c-bf5a-11e4-9b34-a0eb1868a9a1.png)

Also worth notice is that auto closing parentheses is also missing in the new version.

**Comment by Carreau** [comment] 2015-02-28 07:00
First part is duplicate of #7817

**Comment by Carreau** [comment] 2015-02-28 07:20
Autoclose bracket seem to have been [lost in migrating to codemirror 4](https://github.com/ipython/ipython/pull/6221/files#diff-e0448d3a56ba7953d13dec9b09665fcdL107).
It could probably be re-added as default.

**Comment by netheril96** [comment] 2015-02-28 08:17
@Carreau 

Any reason that the autoclose bracket is removed? Just a mistake in migration?

**Comment by Carreau** [comment] 2015-02-28 08:18
Probably just a mistake, or was not working and we forgot reenable after bug fix. The addon is included but just not activated.

**Comment by drorata** [comment] 2015-03-02 11:27
@Carreau: can you explain how can one re-enable the auto-closing?

**Comment by Carreau** [comment] 2015-03-02 17:43
@drorata do you want to make a PR ? 

I woudl do somethign like 

in `/IPython/html/static/notebook/js/codecell.js` around line 120 smth, near `mode: 'ipython',` in `cm_config` add the key `autoCloseBrackets: true` The exact name/casing of option is somewhere [in codemirror manual](http://codemirror.net/3/doc/manual.html).

**Comment by minrk** [comment] 2015-03-03 02:44
titular bug closed by #7903, autoclose of brackets is tracked as #7919.

**Closed by minrk** 2015-03-03 02:44 UTC

**Comment by drorata** [comment] 2015-03-03 10:24
@ Carreau: Everything is correct, except the line number. Should be 130.

**Comment by drorata** [comment] 2015-03-03 14:26
@minrk Correct me if I'm wrong, but this patch doesn't enable to auto-closing of parentheses, right?

**Comment by minrk** [comment] 2015-03-03 17:45
@drorata autoclose of brackets hasn't been fixed. It should be fixed by #7926, and when that happens, #7919 will be closed.
