### ISSUE TITLE
Code cell vertical scrolling

### ISSUE THREAD

**Issue by mathieu1** [ipython/ipython#7395] opened 2015-01-08 16:39 UTC
All code cells are scrolling vertically like there's extra space below the code.

![code_scroll](https://cloud.githubusercontent.com/assets/7703352/5665689/6f60841a-975a-11e4-80c8-d44c45c6078f.gif)

I'm on OS X Yosemite, here's the output of `python -c "import IPython; print(IPython.sys_info())"`

    {'commit_hash': u'12277c7',
     'commit_source': 'repository',
     'default_encoding': 'UTF-8',
     'ipython_path': '/Users/me/github/ipython/IPython',
     'ipython_version': '3.0.0-dev',
     'os_name': 'posix',
     'platform': 'Darwin-14.0.0-x86_64-i386-64bit',
     'sys_executable': '/Users/me/.virtualenvs/test/bin/python',
     'sys_platform': 'darwin',
     'sys_version': '2.7.6 (default, Sep  9 2014, 15:04:36) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]'}

**Comment by juhasch** [comment] 2015-01-08 17:23
This should be fixed in 4.10.0
https://github.com/codemirror/CodeMirror/issues/3009

@Carreau could you update codemirror  ?

**Comment by Carreau** [comment] 2015-01-08 17:25
It's already 4.10.0, we never shipped 4.9.x, and I can reproduce and verrify that we are on 4.10.0

**Comment by juhasch** [comment] 2015-01-08 17:33
I applied the patches from the issue and this went away. Looks like they did not make it into 4.10.0.

**Comment by Carreau** [comment] 2015-01-08 17:46
Reported here https://github.com/codemirror/CodeMirror/issues/3022, the second patch is not actually on 4.10.0, but just after. I've requested a 4.10.1.

**Comment by ellisonbg** [comment] 2015-01-09 20:24
@jdfreder has seen this as well.

**Comment by ellisonbg** [comment] 2015-01-11 01:45
With this bug in play the overall page scrolling on the notebook becomes impossibly slow as well.

**Closed** 2015-01-11 19:12 UTC
Labels: notebook, prio-blocker, type-bug
