### ISSUE TITLE
Won't import module in notebook until kernel is refreshed.

### ISSUE THREAD

**Issue by fgregg** [ipython/ipython#8446] opened 2015-05-19 14:42 UTC
1. install dedupe https://github.com/datamade/dedupe
2. import dedupe.sampling from ipython notebook (fails)
3. restart ipython kernel
4. import dedupe.sampling from ipython notebook (should succeed)

https://github.com/datamade/dedupe/issues/371#issuecomment-103364833

**Comment by minrk** [comment] 2015-05-19 16:23
I repeated these steps and it imported fine. It is unlikely for this to be an IPython issue, since we don't mess with imports. Does this happen only once per install? Once you have installed it, it fails exactly once and every attempt to import after that succeeds in any notebook, python script, or other environment? Or do you see the failure more than once? Are you running dedupe master or stable? What version of Python and IPython?

**Comment by titipata** [comment] 2015-05-19 17:27
Hello @minrk, so in dedupe issue (mentioned in dedupe issue [#371](https://github.com/datamade/dedupe/issues/371#issuecomment-103526062). I use `IPython 2.4.1` and it only occurs once and I cannot reproduce it. However, once I restart kernel after I did `pip install dedupe`, it works just fine.

**Comment by minrk** [comment] 2015-05-19 17:54
If nobody can reproduce it, that makes it hard to figure out what's going on. Can you verify that it imported successfully outside the notebook immediately prior to failing to load in the notebook, with no other changes happening on the system in between? I would be surprised if that were the case. My guess is the issue has something to do with the use of `pkgutil.extend_path` in `dedupe.__init__`.

The only thing IPython does differently from non-interactive Python that's import-related is adding `''` to `sys.path` so that things can be imported from the working directory. If anyone does encounter the problem again, can they `print(dedupe)`, to verify its location? When you do see the problem, have you tried re-running the same import in the same process without starting the kernel?

**Comment by titipata** [comment] 2015-05-19 20:44
Yeah, sorry that I cannot even reproduce the error. Even I uninstalled dedupe and re-install it, no error occurs afterward. In my case, it seems like problem occur only once. Here is the output when I do `print(dedupe)`

```bash
<module 'dedupe' from '/home/ubuntu/anaconda/lib/python2.7/site-packages/dedupe/__init__.pyc'>
```

Hope other people can give more information. If you guys want to test, I can start an ec2 instance and install dedupe to reproduce the error.

**Comment by takluyver** [comment] 2016-01-16 21:55
Had you tried to import dedupe in that kernel before installing it? The import system might be caching something, so if the import had already failed in that process, it might not have searched for the module after installing.

**Comment by Carreau** [comment] 2017-07-19 20:06
Hi, 

This issue has been quiet for almost a year, and I don't think there is anything we can do. It has been marked as no-action, and I'm going to close it to attempt to reduce the number of opened issue. Feel free to reopen if needed. 

Thanks.

**Closed by Carreau** 2017-07-19 20:06 UTC
