### ISSUE TITLE
AssertionError of cursor_position

### ISSUE THREAD

**Issue by frankyjuang** [ipython/ipython#10492] opened 2017-04-29 20:15 UTC
It happens when I accidently enter `p = state.get_clabel?`. But I cannot reproduce it anymore.
```
In [66]: p = state.get_clabel?
Traceback (most recent call last):
  File "/usr/sbin/ipython", line 5, in <module>
    start_ipython()
  File "/usr/lib/python3.6/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/usr/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 440, in mainloop
    self.interact()
  File "/usr/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 423, in interact
    code = self.prompt_for_code()
  File "/usr/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 333, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 408, in run
    self._pre_run(pre_run)
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 383, in _pre_run
    pre_run()
  File "/usr/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 410, in pre_prompt
    self.pt_cli.application.buffer.text = cast_unicode_py2(self.rl_next_input)
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 371, in text
    assert self.cursor_position <= len(value)
AssertionError
```
I was using docker image [tiagopeixoto/graph-tool](https://hub.docker.com/r/tiagopeixoto/graph-tool/).
System information:
```
{'commit_hash': '<not found>',
 'commit_source': '(none found)',
 'default_encoding': 'ANSI_X3.4-1968',
 'ipython_path': '/usr/lib/python3.6/site-packages/IPython',
 'ipython_version': '5.1.0',
 'os_name': 'posix',
 'platform': 'Linux-4.9.13-moby-x86_64-with-arch',
 'sys_executable': '/usr/sbin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.0 (default, Jan 16 2017, 12:12:55) \n[GCC 6.3.1 20170109]'}
```

**Comment by Carreau** [comment] 2017-05-01 03:35
Closing as duplicate of #10464 #10450 #10418 #10381 and #10348.

**Closed by Carreau** 2017-05-01 03:35 UTC
