### ISSUE TITLE
Hang after running pdb in a cell, Kernel/Interrupt doesn't help

### ISSUE THREAD

**Issue by nealmcb** [ipython/ipython#10516] opened 2017-05-08 13:30 UTC
If you debug a cell via pdb, then don't quit it before rerunning the cell, you can't get back to your IPython environment.  Reproduce it via [Test case for pdb hang in Jupyter notebook](https://gist.github.com/nealmcb/1f0a14d63d539940e8dfccc29d6d69ae). Here's a screenshot:

![pdb_resists_kernel_interrupt ipynb](https://cloud.githubusercontent.com/assets/119472/25805924/bddd3162-33be-11e7-8a89-d54245abfd87.png)

For the record and search engines, to hang your notebook:
* Run the following cell
* Do not "quit" via the pdb prompt
* Then run it again.

```
def test():
    import pdb; pdb.set_trace()  # XXX BREAKPOINT
    return 0

test()
```

Note that Kernel/Interupt doesn't help. You can save the notebook, but to run cells again, you need to restart the kernel, at which point "All variables will be lost"

This happens to me not infrequently if I am searching thru the rest of the notebook for hints on how to debug the cell, then forget to quit before changing the cell and running it again.  Yes, I can be more careful, but others have the same experience.  Thanks to @wmayner for a convenient test case described at #3400.

I'm running Jupyter notebook 4.3.1 on Python 3.4.3 (default, Nov 17 2016, 01:08:31) [GCC 4.8.4]
Kernel Information: Python 3.4.3 (default, Nov 17 2016, 01:08:31)

Input from @takluyver at #10499 
> pdb runs in the same process, and we do know when it's expecting input. I think it needs someone to do the work so that when the HTML input box is removed in the frontend, a message is sent back to the kernel which will raise EOFError.
> That may need a new message type, or we could do it as a metadata field on the existing stdin reply message.

**Comment by danolson1** [comment] 2017-06-22 22:48
I am running into the same problem.

**Comment by iNLyze** [comment] 2017-08-15 21:37
Absolutely, same here. This is a royal pain in the rather sensitive parts of my body. If a convenient way to stop pdb from without the running cell existed this could be alleviated. Alternatively, at least a way of saving your work before shutting down the notebook would be important (e.g. trained neural network and the notebook crashes on save after 2000 epochs).

**Comment by vsbuffalo** [comment] 2017-08-23 07:06
I also have this issue, with Jupyter version 4.30, Python 3.6.2.

**Comment by ihincks** [comment] 2017-10-05 13:31
Just lost an 8 hour calculation due to this...time to start again.

**Comment by hsorsky** [comment] 2018-07-06 08:08
Just lost a 64 hour calculation on which I'm meant to be presenting results today -.-

No one found a solution?

**Comment by WilliamCarlos** [comment] 2018-08-22 18:57
Just got bitten by this as well. How do people typically debug in jupyter notebook? Using pdb is like juggling a grenade :(

**Comment by olabreche** [comment] 2018-09-26 20:45
Please please please fix this! I am constantly getting this issue.

**Comment by cristianmtr** [comment] 2018-11-12 16:45
Same here. Have to redo a very long calculation

**Comment by joel-odlund** [comment] 2018-11-21 11:55
same here.

**Comment by zsal** [comment] 2018-11-22 21:00
someone please fix and I will pay you $5

**Comment by sbliven** [comment] 2018-11-30 12:18
@zsal If you're serious, you could add this is issue on https://www.bountysource.com

**Comment by jerrykaplan** [comment] 2019-04-28 17:26
Same problem here. Need a way to interrupt a runaway process or one that is "waiting" on input and get control back ... even if I can no longer get to the input prompt. 

I'm a newby - How on earth do advanced programmers debug in notebooks? Surely they don't use PDB with this "time bomb" in it? Please, share your secrets! :)

**Comment by handrew** [comment] 2019-04-28 20:47
+1

**Comment by carrutstick** [comment] 2019-07-24 15:05
+1

**Comment by ShapingView** [comment] 2019-08-21 13:02
+1

**Comment by daveliu-riviera** [comment] 2019-11-07 18:59
+1

**Comment by louismartin** [comment] 2020-01-29 07:36
Up!
This problem has been a pain for me for years now every time I use pdb and forget to quit before I re-run the cell.

**Comment by louismartin** [comment] 2020-01-29 07:41
I created a bounty on BountySource. Maybe this will finally be fixed if we can gather enough money.
https://www.bountysource.com/issues/44958889-hang-after-running-pdb-in-a-cell-kernel-interrupt-doesn-t-help

**Comment by murtazacornerstone** [comment] 2020-01-29 15:07
+1

**Comment by michaelkyu** [comment] 2020-01-30 22:14
+1

This has driven me crazy for years.

**Comment by nekketsuuu** [comment] 2020-02-11 10:57
How about using `IPython.core.debugger.Pdb` instead?

```
from IPython.core.debugger import Pdb; Pdb().set_trace()
```

**Comment by itamarst** [comment] 2020-02-19 16:30
Run `Pdb().set_trace()` twice has the same issue.

**Comment by itamarst** [comment] 2020-03-02 19:13
I am investigating this. The basic way interrupts work is that they (on Unix) send a signal to the process, which then raises KeyboardInterrupt.

There are appear to be multiple issues with this happening:

1. SIGINT won't interrupt zeromq. This is fixed hopefully by https://github.com/zeromq/pyzmq/pull/1368
2. Even once zeromq is interruptible, I believe `pdb` has a whole bunch of KeyboardInterrupt-catching code that prevents it from percolating up. This may perhaps be fixable in `IPython.core.debugger.Pdb`.

**Comment by minrk** [comment] 2020-03-03 10:51
1. is not accurate, zeromq does get interrupted by SIGINT and raises KeyboardInterrupt, at least unless the SIGINT handler has itself been overridden.

**Comment by itamarst** [comment] 2020-03-03 22:27
@minrk is correct and I was wrong, sorry.

**Comment by itamarst** [comment] 2020-04-22 00:16
To get this fix in, the following needs to happen:

* [ ] Merge https://github.com/ipython/ipython/pull/12168
* [ ] New IPython release
* [ ] Merge https://github.com/ipython/ipykernel/pull/490
* [ ] Merge https://github.com/ipython/ipykernel/pull/498
* [ ] New IPykernel release

**Comment by louismartin** [comment] 2020-04-22 09:07
Thanks so much for looking into this!!

**Comment by itamarst** [comment] 2020-05-27 18:02
As soon as there is a new IPykernel release, this can be closed as fixed.

**Comment by itamarst** [comment] 2020-06-11 19:04
Done! This can be closed.

**Closed** 2020-06-11 19:18 UTC
Labels: notebook

**Comment by vityas** [comment] 2020-06-23 18:51
```
import IPython
import ipykernel
print(IPython.__version__)
print(ipykernel.__version__)
IPython.core.debugger.set_trace(frame=)
```

> 7.15.0
> 5.3.0

```   250         sys.stdout.flush()
    251 
--> 252     def __call__(self, result=None):
    253         """Printing with history cache management.
    254 

--KeyboardInterrupt--
--KeyboardInterrupt--```

KeyboardInterrupt seems to do nothing in my case. Is that the expected behavior?

**Comment by itamarst** [comment] 2020-06-23 19:37
I would expect that to interrupt. I will see if I can reproduce. This is Windows, yes?

**Comment by vityas** [comment] 2020-06-23 22:30
macOS 10.15.5
```
Python 3.6.2 (default, May  4 2018, 19:40:30)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
```
Oh, so this is not expected. Let me know if there is any info I can add to clarify.

**Comment by mhellb** [comment] 2020-06-24 10:24
For me problem also persisted after updating. Also on the remote linux compute nodes I use for work, see:

```python
import IPython
import ipykernel
import os
import platform

print(IPython.__version__)
print(ipykernel.__version__)
print(os.name,platform.system(),platform.release())
IPython.core.debugger.set_trace()
```

> 7.15.0
5.3.0
posix Linux 4.19.94-300.el7.x86_64

Currently working in a pretty bulky environment so cannot rule out some dependencies might be causing it? I can try to see if the error also reproduces in a minimal environment if that would be useful?

**Comment by Carreau** [comment] 2020-06-26 20:47
This needs master of IPykernel that has not been released yet.
