### ISSUE TITLE
Badly formed notebook tracebacks ending with `AssertionError: Pieces mismatches`

### ISSUE THREAD

**Issue by maximlt** [ipython/ipython#13840] opened 2022-11-22 10:56 UTC
We've been having this new issue for a while now, probably about a few months. In some cases the tracebacks displayed in a Jupyter Notebook seem to be incorrectly parsed at some point and cause an `AssertionError` to be raised. After some long bug hunting I've been able to reproduce the error consistently with the following procedure:

1. create a module with this content:
```python
# reproduce.py
raise ValueError('error')

a = 1 ; b = ("""
   unhappy """
)
```
2. import the module (`import reproduce`) in a Jupyter notebook

The traceback you will get is:

```
Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/c9/s6_8wl553ql93tjgvmbmsn5h0000gp/T/ipykernel_70407/484344519.py", line 1, in <module>
    import unhappy
  File "/Users/mliquet/work/dev/param/mltmess/unhappy.py", line 1, in <module>
    raise ValueError('error')
ValueError: error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1997, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1112, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1006, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/IPython/core/ultratb.py", line 859, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/IPython/core/ultratb.py", line 812, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/IPython/core/ultratb.py", line 730, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/stack_data/core.py", line 734, in lines
    pieces = self.included_pieces
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/stack_data/core.py", line 677, in included_pieces
    scope_pieces = self.scope_pieces
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/stack_data/core.py", line 617, in scope_pieces
    for piece in self.source.pieces
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/stack_data/core.py", line 106, in pieces
    return list(self._clean_pieces())
  File "/Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/stack_data/core.py", line 130, in _clean_pieces
    raise AssertionError("Pieces mismatches: %s" % mismatches)
AssertionError: Pieces mismatches: [{3, 4}]
```

It *seems* that the issue comes down to the fact that in the module there's a piece of code with multiple statements on a single line (`;`) and the last statement spans over multiple lines. There's no *additional* error when the code is formatted differently, the `ValueError` is displayed as usual:

```python
# alright.py
raise ValueError('error')

a = 1 
b = ("""
   unhappy """
)
```

Issue reproduces with:
- python 3.10.8
- ipython 8.6.0
- notebook 6.5.2
- stack_data 0.6.1

ref: https://github.com/holoviz/holoviews/issues/5515

**Comment by krassowski** [comment] 2022-11-27 16:23
Thanks for the report! It looks like it originates from stack-data; I opened https://github.com/alexmojaki/stack_data/issues/44 with self-contained reproducer which removes import from file and IPython from the equation.

**Comment by alexmojaki** [comment] 2022-11-27 17:52
> We've been having this new issue for a while now, probably about a few months.

This is reminding me of https://github.com/ipython/ipython/issues/13598#issuecomment-1207451886. Please report issues sooner if possible. A notebook which reproduced the problem and that you're willing to share would be sufficient even if you didn't know how to narrow it down further. But I can understand if even achieving that was difficult, and if narrowing the problem down to https://github.com/holoviz/param/pull/663 or the semicolons was the relatively easy part.

**Comment by maximlt** [comment] 2022-11-27 19:52
Sure happy to report issues as soon as possible! This one though was quite unexpected, so much that I thought that my dev environment was broken in some way, same conclusion for others in our group until we all realized we were having the same error and one of us decided to track it down :) Thanks for stack_data!

**Comment by alexmojaki** [comment] 2022-11-27 20:14
Fix released in stack_data 0.6.2

**Comment by krassowski** [comment] 2022-12-04 01:31
Thank you Alex, that was super quick!

Closing this as resolved upstream as per https://github.com/ipython/ipython/issues/13840#issuecomment-1328330865.

**Closed by krassowski** 2022-12-04 01:31 UTC
Labels: bug, external-software-interaction

**Comment by chsubhan804** [comment] 2025-03-29 03:45
i gotthis issue can some body immediatekly silve it====AssertionError                            Traceback (most recent call last)
<ipython-input-4-28b44f71aa21> in <cell line: 55>()
     53 start_init = time.time()
     54 
---> 55 llm = LLM(
     56     llm_model_pth,
     57     max_num_seqs=MAX_NUM_SEQS,    # Maximum number of sequences per iteration.

/kaggle/usr/lib/vllm_0_7/vllm/utils.py in inner(*args, **kwargs)
   1037                     )
   1038 
-> 1039             return fn(*args, **kwargs)
   1040 
   1041         return inner  # type: ignore

/kaggle/usr/lib/vllm_0_7/vllm/entrypoints/llm.py in __init__(self, model, tokenizer, tokenizer_mode, skip_tokenizer_init, trust_remote_code, allowed_local_media_path, tensor_parallel_size, dtype, quantization, revision, tokenizer_revision, seed, gpu_memory_utilization, swap_space, cpu_offload_gb, enforce_eager, max_seq_len_to_capture, disable_custom_all_reduce, disable_async_output_proc, hf_overrides, mm_processor_kwargs, task, override_pooler_config, compilation_config, **kwargs)
    238         # to avoid import order issues
    239         self.engine_class = self.get_engine_class()
--> 240         self.llm_engine = self.engine_class.from_engine_args(
    241             engine_args, usage_context=UsageContext.LLM_CLASS)
    242 

/kaggle/usr/lib/vllm_0_7/vllm/engine/llm_engine.py in from_engine_args(cls, engine_args, usage_context, stat_loggers)
    480         executor_class = cls._get_executor_cls(engine_config)
    481         # Create the LLM engine.
--> 482         engine = cls(
    483             vllm_config=engine_config,
    484             executor_class=executor_class,

/kaggle/usr/lib/vllm_0_7/vllm/engine/llm_engine.py in __init__(self, vllm_config, executor_class, log_stats, usage_context, stat_loggers, input_registry, mm_registry, use_cached_outputs)
    269             self.model_config)
    270 
--> 271         self.model_executor = executor_class(vllm_config=vllm_config, )
    272 
    273         if self.model_config.runner_type != "pooling":

/kaggle/usr/lib/vllm_0_7/vllm/executor/executor_base.py in __init__(self, *args, **kwargs)
    258         self.parallel_worker_tasks: Optional[Union[Any, Awaitable[Any]]] = None
    259 
--> 260         super().__init__(*args, **kwargs)
    261 
    262     def execute_model(

/kaggle/usr/lib/vllm_0_7/vllm/executor/executor_base.py in __init__(self, vllm_config)
     47         self.prompt_adapter_config = vllm_config.prompt_adapter_config
     48         self.observability_config = vllm_config.observability_config
---> 49         self._init_executor()
     50         self.is_sleeping = False
     51 

/kaggle/usr/lib/vllm_0_7/vllm/executor/mp_distributed_executor.py in _init_executor(self)
    121         self._run_workers("init_worker", all_kwargs)
    122         self._run_workers("init_device")
--> 123         self._run_workers("load_model",
    124                           max_concurrent_workers=self.parallel_config.
    125                           max_parallel_loading_workers)

/kaggle/usr/lib/vllm_0_7/vllm/executor/mp_distributed_executor.py in _run_workers(***failed resolving arguments***)
    181         ]
    182 
--> 183         driver_worker_output = run_method(self.driver_worker, sent_method,
    184                                           args, kwargs)
    185 

/kaggle/usr/lib/vllm_0_7/vllm/utils.py in run_method(obj, method, args, kwargs)
   2206     else:
   2207         func = partial(method, obj)  # type: ignore
-> 2208     return func(*args, **kwargs)

/kaggle/usr/lib/vllm_0_7/vllm/worker/worker.py in load_model(self)
    180             context = nullcontext()
    181         with context:
--> 182             self.model_runner.load_model()
    183 
    184     def save_sharded_state(

/kaggle/usr/lib/vllm_0_7/vllm/worker/model_runner.py in load_model(self)
   1111         logger.info("Starting to load model %s...", self.model_config.model)
   1112         with DeviceMemoryProfiler() as m:
-> 1113             self.model = get_model(vllm_config=self.vllm_config)
   1114 
   1115         self.model_memory_usage = m.consumed_memory

/kaggle/usr/lib/vllm_0_7/vllm/model_executor/model_loader/__init__.py in get_model(vllm_config)
     10 def get_model(*, vllm_config: VllmConfig) -> nn.Module:
     11     loader = get_model_loader(vllm_config.load_config)
---> 12     return loader.load_model(vllm_config=vllm_config)
     13 
     14 

/kaggle/usr/lib/vllm_0_7/vllm/model_executor/model_loader/loader.py in load_model(self, vllm_config)
    378 
    379             weights_to_load = {name for name, _ in model.named_parameters()}
--> 380             loaded_weights = model.load_weights(
    381                 self._get_all_weights(model_config, model))
    382             # We only enable strict check for non-quantized models

/kaggle/usr/lib/vllm_0_7/vllm/model_executor/models/qwen2.py in load_weights(self, weights)
    511                            if self.config.tie_word_embeddings else None),
    512         )
--> 513         return loader.load_weights(weights)
    514 
    515 

/kaggle/usr/lib/vllm_0_7/vllm/model_executor/models/utils.py in load_weights(self, weights, mapper)
    231             weights = mapper.apply(weights)
    232 
--> 233         autoloaded_weights = set(self._load_module("", self.module, weights))
    234         return autoloaded_weights
    235 

/kaggle/usr/lib/vllm_0_7/vllm/model_executor/models/utils.py in _load_module(self, base_prefix, module, weights)
    192                     continue
    193 
--> 194                 yield from self._load_module(prefix,
    195                                              child_modules[child_prefix],
    196                                              child_weights)

/kaggle/usr/lib/vllm_0_7/vllm/model_executor/models/utils.py in _load_module(self, base_prefix, module, weights)
    169             module_load_weights = getattr(module, "load_weights", None)
    170             if callable(module_load_weights):
--> 171                 loaded_params = module_load_weights(weights)
    172                 if loaded_params is None:
    173                     logger.warning(

/kaggle/usr/lib/vllm_0_7/vllm/model_executor/models/qwen2.py in load_weights(self, weights)
    411                 weight_loader = getattr(param, "weight_loader",
    412                                         default_weight_loader)
--> 413                 weight_loader(param, loaded_weight)
    414             loaded_params.add(name)
    415         return loaded_params

/kaggle/usr/lib/vllm_0_7/vllm/model_executor/layers/linear.py in weight_loader(self, param, loaded_weight)
   1109             loaded_weight = loaded_weight.reshape(1)
   1110 
-> 1111         assert param_data.shape == loaded_weight.shape
   1112         param_data.copy_(loaded_weight)
   1113 

AssertionError:
