### ISSUE TITLE
Highlighting does not like underscore in numeric literals

### ISSUE THREAD

**Issue by Carreau** [ipython/ipython#10363] opened 2017-03-01 17:15 UTC
<img width="148" alt="screen shot 2017-03-01 at 09 13 50" src="https://cloud.githubusercontent.com/assets/335567/23471810/70539448-fe5f-11e6-92e9-e587587aa4bd.png">

nor f-strings, but it's less visible as only `f` is of wrong color.

**Comment by takluyver** [comment] 2017-03-01 17:16
I imagine this probably needs a fix in pygments.

**Comment by Carreau** [comment] 2017-03-01 17:23
Likely yes.

**Comment by tchajed** [comment] 2017-08-15 13:24
This looks like a duplicate of #10461 (which came later but has some more discussion).

**Comment by takluyver** [comment] 2017-08-15 14:26
Thanks @tchajed !

**Closed by takluyver** 2017-08-15 14:26 UTC
