### ISSUE TITLE
IPython leaks local variables when an exception is thrown

### ISSUE THREAD

**Issue by ianh** [ipython/ipython#13103] opened 2021-08-21 03:42 UTC
**To Reproduce**
1. Enter this code into a cell:
```python
import gc
gc.collect()
objs = gc.get_objects()
for obj in objs:
    try:
        if isinstance(obj, X):
            print(obj)
    except NameError:
        class X:
            pass
def f():
    x = X()
    raise Exception()
f()
```
2. Run the cell.  An exception will be displayed.
3. Keep running the cell.

**Expected behavior**
No `X` objects are leaked during the execution of the cell.

**Actual behavior**
An `X` object is leaked every time the cell is run -- each one is printed to the cell output.

**Version**
Here is the info from the Jupyter About menu:
```
You are using Jupyter notebook.

The version of the notebook server is: 6.4.3-265c8c36a
The server is running on this version of Python:
Python 3.9.6 (default, Jun 28 2021, 19:24:41) 
[Clang 12.0.5 (clang-1205.0.22.9)]

Current Kernel Information:

Python 3.9.6 (default, Jun 28 2021, 19:24:41) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.26.0 -- An enhanced Interactive Python. Type '?' for help.
```

**Additional context**
This issue was discovered in the context of Google's Colab (where leaked PyTorch tensors can exhaust GPU memory), but it reproduces in a local Jupyter instance as well.

**Comment by ianh** [comment] 2021-08-21 03:43
Originally filed as https://github.com/jupyter/notebook/issues/6147, where it was diagnosed as an IPython issue rather than something specific to Jupyter.

**Comment by MrMino** [comment] 2021-08-31 19:28
This reminds me of circular references stemming from traceback infos. I don't remember the exact details of that, there was a long thread about it on python-dev back in the day.

In any case, the same behavior is exhibited by Python interpreter itself, so it's probably not related to IPython either.

**Comment by alexmojaki** [comment] 2021-09-18 00:15
I could also reproduce this in a standard Python 3.8.5 shell:

```
>>> import gc
>>> gc.collect()
0
>>> objs = gc.get_objects()
>>> for obj in objs:
...     try:
...         if isinstance(obj, X):
...             print(obj)
...     except NameError:
...         class X:
...             pass
... 
>>> def f():
...     x = X()
...     raise Exception()
... 
>>> f()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in f
Exception
>>> 
>>> 
>>> gc.collect()
0
>>> objs = gc.get_objects()
>>> for obj in objs:
...     try:
...         if isinstance(obj, X):
...             print(obj)
...     except NameError:
...         class X:
...             pass
... 
<__main__.X object at 0x7fc35414aee0>
>>> f()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in f
Exception
>>> 
>>> gc.collect()
0
>>> objs = gc.get_objects()
>>> for obj in objs:
...     try:
...         if isinstance(obj, X):
...             print(obj)
...     except NameError:
...         class X:
...             pass
... 
<__main__.X object at 0x7fc35414aee0>
<__main__.X object at 0x7fc3541e6fd0>
>>> f()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in f
Exception
>>> gc.collect()
0
>>> objs = gc.get_objects()
>>> for obj in objs:
...     try:
...         if isinstance(obj, X):
...             print(obj)
...     except NameError:
...         class X:
...             pass
... 
<__main__.X object at 0x7fc3541e6fd0>
<__main__.X object at 0x7fc35414aee0>
<__main__.X object at 0x7fc3541cf130>
>>> f()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in f
Exception
>>> 
```

**Comment by MrMino** [comment] 2021-09-18 01:49
Going to close this given it looks like there's nothing to do for us here, but @ianh if you want to propose something, don't hesitate, we'll reopen.

**Closed by MrMino** 2021-09-18 01:49 UTC
Labels: needs-info, core

**Comment by ianh** [comment] 2021-09-19 08:22
Sounds good -- I can also reproduce this behavior in the Python REPL itself.  I filed https://bugs.python.org/issue45241 in case they want to fix it there.  Thanks for taking a look.
