### ISSUE TITLE
Create notebook based documentation about nbextensions

### ISSUE THREAD

**Issue by chriddyp** [ipython/ipython#7392] opened 2015-01-06 23:09 UTC
Hey all --

Not sure if there is a recommended way to import custom widget JS in distributed packages. Has anything changed since this email thread from last April: http://mail.scipy.org/pipermail/ipython-dev/2014-April/013835.html?

I'm planning on just loading and [displaying the JS code on import, here's a snippet](https://github.com/plotly/python-api/pull/172/files) : 

```python
## graph_widget.py

directory = os.path.dirname(os.path.realpath(__file__))
js_widget_file = os.path.join(directory, 'graphWidget.js')
with open(js_widget_file) as f:
    js_widget_code = f.read()

display(Javascript(js_widget_code))

class Graph(widgets.DOMWidget):
    ...
```

Thanks for the help!

**Comment by ellisonbg** [comment] 2015-01-11 22:24
The current way for handling custom JS code is to install the JS as a notebook extension and then load it using require.js. Our documentation for this is pretty bad right now. I am going to change this issue as a note for us to document how to do this in our notebook based docs.

**Comment by ellisonbg** [comment] 2015-01-11 22:25
The notebook documentation should cover all aspects:

* How library authors can install nbextensions programatically.
* How users can install nbextensions from the command line.
* How library authors can load the JS code using require.js.

**Comment by juhasch** [comment] 2015-01-11 22:28
I tried to document installing and loading of extensions for ipython-contrib here:
https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Home_3x

I personally am using a server extension for this task:
https://github.com/ipython-contrib/IPython-notebook-extensions/pull/164

**Comment by minrk** [comment] 2015-01-20 20:40
Closing as duplicate of #6229

**Closed by minrk** 2015-01-20 20:40 UTC
Labels: docs, notebook
