### ISSUE TITLE
IPython notebook slowdown when it includes huge latex expressions

### ISSUE THREAD

**Issue by jrjohansson** [ipython/ipython#6753] opened 2014-10-21 04:26 UTC
Recently me and @eunjongkim have been working with IPython notebooks that contains a lot of SymPy generated LaTeX equations, and we are experiencing that the notebook interface becomes very sluggish and difficult to work with when it contains large latex expressions. This is not only while the expressions are being rendered, but also after mathjax has completed rendering and when the IPython kernel is not busy.

Here is an example notebook in which we are seeing this problem:

http://nbviewer.ipython.org/github/eunjongkim/reproduced-papers/blob/master/Reproduce-Nature-460-724-2009-Groblacher.ipynb

If this notebook is downloaded and opened in IPython notebook, even without being executed, just viewed, the browser almost freezes up. We see this in Safari and Chrome (in chrome the "Google Chrome Helper" process takes 100% CPU load).

After clearing all output the notebook gets fast and responsive again.

**Comment by ellisonbg** [comment] 2015-01-12 18:15
@jrjohansson the pager has been removed from master. Can you test with HTML/MathJax equation rendering to see if the issue is resolved?

**Comment by jrjohansson** [comment] 2015-01-13 02:54
Indeed, this seems to have solved the problem. The notebooks that previously were sluggish are now very responsive also when using HTML/MathJax rendering with current master. @ellisonbg, thanks for following up on this!

**Comment by ellisonbg** [comment] 2015-01-13 03:44
Great! Closing.

**Closed by ellisonbg** 2015-01-13 03:44 UTC
Labels: notebook, type-bug
