### ISSUE TITLE
Fix for infinite recursion in autoreload

### ISSUE THREAD

**Issue by mccullerlp** [ipython/ipython#10214] opened 2017-01-28 16:43 UTC
I have a class which memoizes contains a link to itself as an attribute. This is used as a to ensure that a class specific memoized computation is unique and not inherited from bases.

It turns out that this causes an infinite recursion between update_generic and update_class in autoreload.

This is fixed with a quick check to prevent this case. added after the "prevent recursion" comment.

Furthermore in this code, the for loop also loops on "new" object attributes, which will fix #8771

```python
def update_class(old, new):
    """Replace stuff in the __dict__ of a class, and upgrade
    method code objects"""
    #for key in list(old.__dict__.keys()):
    for key in set(list(old.__dict__.keys()) + list(new.__dict__.keys())):
        old_obj = getattr(old, key)

        try:
            new_obj = getattr(new, key)
        except AttributeError:
            # obsolete attribute: remove it
            try:
                delattr(old, key)
            except (AttributeError, TypeError):
                pass
            continue

        #prevent recursion 
        if old_obj not in [old, new] and new_obj not in [old, new]:
            if update_generic(old_obj, new_obj): continue

        try:
            setattr(old, key, getattr(new, key))
        except (AttributeError, TypeError):
            pass # skip non-writable attributes
```

**Comment by takluyver** [comment] 2017-01-29 09:46
Do you want to make a pull request so we can see the change in context?

**Comment by Carreau** [comment] 2017-02-22 22:41
Can you share the object you are using or try master ? 

Would #10316 and if so would #10232 be a duplicate ?

**Comment by Carreau** [comment] 2017-02-22 22:47
Also here is the diff, for people interested:

```diff
diff --git a/IPython/extensions/autoreload.py b/IPython/extensions/autoreload.py
index 2fe9974..3b266ce 100644
--- a/IPython/extensions/autoreload.py
+++ b/IPython/extensions/autoreload.py
@@ -272,8 +272,9 @@ def update_function(old, new):
 def update_class(old, new):
     """Replace stuff in the __dict__ of a class, and upgrade
     method code objects"""
-    for key in     list(old.__dict__.keys()):
+    for key in set(list(old.__dict__.keys()) + list(new.__dict__.keys())):
         old_obj = getattr(old, key)
+
         try:
             new_obj = getattr(new, key)
             if old_obj == new_obj:
@@ -286,7 +287,9 @@ def update_class(old, new):
                 pass
             continue

-        if update_generic(old_obj, new_obj): continue
+        if old_obj not in [old, new] and new_obj not in [old, new]:
+            if update_generic(old_obj, new_obj):
+                continue

         try:
             setattr(old, key, getattr(new, key))
```

And i think it make sens as well, I'd like test cases though to include.

**Comment by takluyver** [comment] 2017-02-23 12:02
I'll bump this to 5.4 if no-one tackles it soon.

**Comment by takluyver** [comment] 2017-02-24 14:42
Bumped. Stand by for IPython 5.3. :-)

**Comment by fenwickipedia** [comment] 2017-11-20 15:56
I'm interested in working on the issue, but curious what's needed. Has anyone been able to reproduce it and/or do any verification of the OP's fix?

**Comment by takluyver** [comment] 2017-11-20 16:10
Thanks @fenwickipedia . I don't think we tried to reproduce it, but from the description, I imagine it would require code something like this:

```python
class A(object):
    def __init__(self):
        self.memos = [A]

a = A()
```

I'm not 100% sure, though. This may have been fixed by #10316, so if it's working on IPython 6.x, try it also on IPython 5.x (before #10316 was merged) to see if that can reproduce it.

**Comment by fenwickipedia** [comment] 2017-11-20 16:33
Thanks @takluyver that ran with no recursion issue in 6.x, will try 5.x in a Py3 and Py2.7 env to see if it recreates.

**Comment by fenwickipedia** [comment] 2017-11-20 16:55
@takluyver couldn't reproduce with 5.0 in Py 3.6 or 2.7

**Comment by takluyver** [comment] 2017-11-20 17:12
That probably means I've misunderstood what the OP meant about "a class which memoizes contains a link to itself as an attribute"

**Comment by fenwickipedia** [comment] 2017-11-20 17:18
Yes, I'm trying to decrypt that statement as well. @mccullerlp can you provide an example to reproduce?

**Comment by mccullerlp** [comment] 2017-11-20 17:38
I was doing something a bit more strange to trigger it. It is a bit of a metaclass emulating behavior that needs some notion whether or not the logic has been run. In my case I was memoizing some class-specific values. This should be able to trigger it.

```python
class A(object):
    _clsetup = None

    @classmethod
    def clsetup_do(cls):
        pass #do some kind of unique class-specific setup

    def clsetup_check(self):
        if self._clsetup is not self.__class__:
             self.clsetup_do()
             self.__class__._clsetup = self.__class__

    def __init__(self):
         self.clsetup_check()
```

**Comment by takluyver** [comment] 2017-11-20 17:45
Thanks for the timely response!

**Comment by fenwickipedia** [comment] 2017-11-20 18:19
I put the code into sprint.py, instantiated the class ok, plus called the methods, but not seeing the issue still. Is there something else I should try? 
`Python 2.7.10 (default, Feb  7 2017, 00:08:15)
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sprint import A

In [2]: a = A()

In [3]: a.clsetup_check
Out[3]: <bound method A.clsetup_check of <sprint.A object at 0x10f8444d0>>

In [4]: a.clsetup_do
Out[4]: <bound method type.clsetup_do of <class 'sprint.A'>>`

**Comment by takluyver** [comment] 2017-11-20 19:01
You need autoreload enabled. I'm on my phone just now, but if you search
the IPython docs, it should show you how.

**Comment by fenwickipedia** [comment] 2017-11-20 19:14
tried these and no luck
```
In [1]: %load_ext autoreload

In [2]: %autoreload

In [3]: from sprint import A

In [4]: a = A()

In [5]: a.clsetup_check
Out[5]: <bound method A.clsetup_check of <sprint.A object at 0x10e4d8990>>

In [6]: a.clsetup_do
Out[6]: <bound method type.clsetup_do of <class 'sprint.A'>>

In [7]: %autoreload
```

```
In [1]: %load_ext autoreload

In [2]: %autoreload 2

In [3]: from sprint import A

In [4]: a = A()

In [5]: a.clsetup_check
Out[5]: <bound method A.clsetup_check of <sprint.A object at 0x10e12fb10>>

In [6]: a.clsetup_do
Out[6]: <bound method type.clsetup_do of <class 'sprint.A'>>

In [7]: %autoreload
```

**Comment by fenwickipedia** [comment] 2017-11-20 19:29
Some other attempts, added print statements to __init__ see it actually reloaded.
```
In [8]: b = A()
add a change

In [9]: a = A()
add a change

In [10]: %autoreload

In [11]: a = A()
add a change
add another

In [12]: %autoreload

In [13]: %autoreload 0

In [14]: a = A()
add a change
add another

In [15]: %autoreload

In [16]: a = A()
add a change
add another
add another2
```

**Comment by takluyver** [comment] 2017-11-20 21:41
Thanks for checking through this. I assume you were doing some of those checks with IPython 5.x?

Unless @mccullerlp has some other ideas how to reproduce this, I think we can close it as incidentally fixed somewhere along the line.

**Comment by fenwickipedia** [comment] 2017-11-20 21:57
Fair enough, no problem and thanks for getting back @takluyver!

**Comment by takluyver** [comment] 2017-11-21 13:09
Closing - we can reopen if we find a way to reproduce it.

**Closed by takluyver** 2017-11-21 13:09 UTC
Labels: help wanted
