### ISSUE TITLE
Combining assignment and help operator (?) crashes ipython

### ISSUE THREAD

**Issue by halflings** [ipython/ipython#10450] opened 2017-04-13 22:12 UTC
Reproduction steps (ipython 5.2.2):

1) Launch ipython3
2) Execute `s = str?`
3) ipython crashes with the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ipython3", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python3.6/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/usr/local/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 455, in mainloop
    self.interact()
  File "/usr/local/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 438, in interact
    code = self.prompt_for_code()
  File "/usr/local/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 343, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 408, in run
    self._pre_run(pre_run)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 383, in _pre_run
    pre_run()
  File "/usr/local/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 425, in pre_prompt
    self.pt_cli.application.buffer.text = cast_unicode_py2(self.rl_next_input)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 371, in text
    assert self.cursor_position <= len(value)
AssertionError
```

**Comment by carlsmith** [comment] 2017-04-13 23:18
Your example works perfectly in IPython 5.1.0.

**Comment by Carreau** [comment] 2017-04-14 16:47
That's a duplicate of #10418 and a few other similar bugs. Try upgrading to IPython 5.3 or downgrading/upgrading prompt_toolkit.

**Closed by Carreau** 2017-04-14 16:47 UTC
