### ISSUE TITLE
erro get_completions

### ISSUE THREAD

**Issue by f0l1v31r4** [ipython/ipython#12754] opened 2021-01-01 20:03 UTC
When starting ipython and making some definitions of variables when using the tab, the error occurs:

for item in self.get_completions(document, complete_event):
  File "/home/foliveira/.local/share/virtualenvs/alura-9fWr_lwZ/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    exc_type, exc_value, exc_tb = sys.exc_info()
**NameError: name 'sys' is not defined**

my enviroment:
Python 3.8.5  
IPython 7.19.0

**Comment by LuanComputacao** [comment] 2021-01-02 00:48
same thing here, when using venv

**Comment by chanochan** [comment] 2021-01-02 03:20
Same thing here.

And after I tried to import `sys` and `traceback` in `IPython/terminal/ptutils.py` got another exception:

```
Traceback (most recent call last):
  File "/home/myuser/Envs/myvenv/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 115, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/myuser/Envs/myvenv/lib/python3.8/site-packages/IPython/terminal/ptutils.py", line 131, in _get_completions
    for c in completions:
  File "/home/myuser/Envs/myvenv/lib/python3.8/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/home/myuser/Envs/myvenv/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/myuser/Envs/myvenv/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/home/myuser/Envs/myvenv/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/home/myuser/Envs/myvenv/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/home/myuser/Envs/myvenv/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'
```

**Comment by krzysieqq** [comment] 2021-01-02 07:41
Just install older jedi version
`pip install jedi==0.17.2`

**Comment by MattMoony** [comment] 2021-01-02 08:53
Thanks a lot @krzysieqq - worked nicely :+1:

**Comment by SerpentByte** [comment] 2021-01-03 02:19
@krzysieqq thanks. Worked like a charm.

**Comment by pbregener** [comment] 2021-01-04 10:39
Duplicate of #12740

**Comment by minrk** [comment] 2021-01-12 10:20
thanks, closing duplicates

**Closed by minrk** 2021-01-12 10:20 UTC
