### ISSUE TITLE
%matplolib qt causes notebook to hang when using Run-All

### ISSUE THREAD

**Issue by tritemio** [ipython/ipython#7039] opened 2014-11-26 01:04 UTC
Create a notebook with the following 2 cells:

    %matplolib qt

and 

    print 1

When running the notebook with *Cell -> Run All* the notebook hangs, the print statement is never executed and a kernel restart is needed.

This behavior happens both with PySide and with PyQt4. Both on Windows and on Linux. 

System info for the Windows PC:
```
{'commit_hash': 'd87a8cd',
 'commit_source': 'installation',
 'default_encoding': 'cp437',
 'ipython_path': 'C:\\Users\\laser2002j\\Anaconda\\lib\\site-packages\\IPython',
 'ipython_version': '2.2.0',
 'os_name': 'nt',
 'platform': 'Windows-7-6.1.7601-SP1',
 'sys_executable': 'C:\\Users\\laser2002j\\Anaconda\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.7 |Anaconda 2.1.0 (64-bit)| (default, Jun 11 2014, 10:40:02) [MSC v.1500 64 bit (AMD64)]'}
```

**Comment by Carreau** [comment] 2016-01-19 19:14
duplicate of #5629 , which is older and have more discussion. Closing here.

**Closed by Carreau** 2016-01-19 19:14 UTC
Labels: bug, matplotlib
