### ISSUE TITLE
nbconvert crashes on Windows

### ISSUE THREAD

**Issue by blokeley** [ipython/ipython#7946] opened 2015-03-03 13:53 UTC
I just used conda to update to ipython 3.0.

"File > Print Preview" and "File > Download as..." do not work (except for download as .ipynb)

1. At first, I got an exception saying that "mistune" could not be found (and I have no idea what this has to do with PDF export). This is #7936.
2. "conda install mistune" does not work so I used "pip install mistune" which installed OK.
3. Now, "Print Preview" or "Download as" cause python.exe to crash.

Opening the Windows command line and trying:
ipython nbconvert <file>

Also crashes every time.

Please advise how I can fix this because I will need to save some notebooks as reports over the next few days!

Versions:
Windows 7 Professional 64-bit
conda 3.9.1
ipython 3.0.0

**Comment by takluyver** [comment] 2015-03-03 17:16
Ping @asmeurer - I think you need to package mistune for conda, because nbconvert now requires it.

Back to this issue - do you get an error message at the command line when Python crashes?

**Comment by blokeley** [comment] 2015-03-03 17:47
@takluyver I get no error message from ipython or from the python interpreter.

I just get the Windows dialog box which says:

"python.exe has stopped working"
"A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available."

**Comment by juhasch** [comment] 2015-03-03 18:02
This is a problem of Anaconda with Windows 7. If you install mistune using pip it will compile a Cython version and crash. This is due to some Unicode handling problems.
Either use the pure Python version (remove  mistune.pyd and copy mistune.py into your installation) or try my mistune conda package on binstar.

**Comment by takluyver** [comment] 2015-03-03 18:04
Thanks @juhasch. Do you have a handle on what the issue is? Please report it at https://github.com/lepture/mistune/issues so we can get it fixed upstream.

**Comment by juhasch** [comment] 2015-03-03 18:09
It looks like when you are compiling programs under Windows 8 it has a code path for Unicode that uses system DLLs not available in Windows 7. I don't think there is a fix other than not using Unicode, or upgrading to Windows 8, or not using Windows 8 compiled programs in Windows 7.

**Comment by takluyver** [comment] 2015-03-03 18:14
I'm confused, how is Windows 8 involved? mistune doesn't have Windows binaries on PyPI, so it should be compiling locally.

**Comment by juhasch** [comment] 2015-03-03 18:20
Anacoda is compiled under Windows 8. If you now compile any Cython extension under Windows 7 that does unicode string handling it crashes. I can avoid this using the Microsoft compiler MSVC2010.

**Comment by takluyver** [comment] 2015-03-03 18:22
That sounds pretty disastrous! Are Continuum aware of this? Ping @asmeurer again.

**Comment by juhasch** [comment] 2015-03-03 19:15
This is not really Continuums fault, as it looks like mingw (which is packaged with Anaconda) is causing the problems.

I see that there is now a mistune conda package from Continuum available.
So I guess the new advice is to do a "conda install mistune" and be happy :-)

**Comment by takluyver** [comment] 2015-03-03 19:26
Thanks again for digging into this. Closing here as it should be fixed, and there's nothing IPython can do in any case.

**Closed by takluyver** 2015-03-03 19:26 UTC

**Comment by asmeurer** [comment] 2015-03-03 19:45
Anaconda is compiled on Windows XP.

**Comment by juhasch** [comment] 2015-03-03 19:51
Thanks for the info. So where do these dependencies to Windows 8 come from ?
(at least this is what dependencywalker tells me). I don't have any access to Win8 machines, so it is hard to look further for me.

**Comment by asmeurer** [comment] 2015-03-03 19:56
I'm not really clear what your issue is. If you could open an issue at https://github.com/continuumio/anaconda-issues with full information that would help.

**Comment by juhasch** [comment] 2015-03-03 20:03
I guess this is the issue:
https://github.com/ContinuumIO/anaconda-issues/issues/271

i.e. building Cython modules using Anaconda Python3 + Windows7 64 bit and the default MinGW compiler doesn't really work. Everything in the Anaconda distribution coming from Continuum itself does work.

**Comment by blokeley** [comment] 2015-03-03 20:57
I just did:
> pip uninstall mistune
> conda install mistune

OK so far. 
Now can I download as PDF?
I try "File > Download As... PDF" and get...
*500 server error. 'pandoc' is not installed*

Gah! So I go and download an 18 MB WIndows installer to get pandoc. 
Now surely... I try "File > Download As.... PDF" and get...
"500 server error: nbconvert failed: command could not be found: pdflatex"

Double gah!
Please, please don't tell me I have to install latex on a WIndows machine this day in age. I thought that native PDF output was one of the features of IPython 3.

IPython has so much going for it but this makes me just want to pack it in and use MATLAB. Sorry for the rant. I've just lost too much time on this today.

**Comment by takluyver** [comment] 2015-03-03 21:48
Sorry, no, PDF export still goes via Latex. If someone wants to write an alternative conversion via HTML using something like [weasyprint](http://weasyprint.org/), or even direct export with e.g. [reportlab](https://pypi.python.org/pypi/reportlab), that would be good. But no-one has been motivated enough to do it yet.

**Comment by minrk** [comment] 2015-03-03 21:48
> Please, please don't tell me I have to install latex on a Windows machine this day in age

If you want IPython's PDF output via nbconvert, that's exactly right. You can get a PDF of the HTML with the browser's print to pdf functionality via the Print Preview link. Maybe that's closer to what you are after.

> I thought that native PDF output was one of the features of IPython 3.

I don't quite know what 'native' means here, but what gave you that impression? We are not likely to write our own PDF implementation. Perhaps we have some docs to clarify.

**Comment by juhasch** [comment] 2015-03-04 10:26
To generate a PDF that looks "good enough" for documentation, I use the print to PDF capabilities of Chrome. For really nice looking documents, this is not a good solution, though.
