### ISSUE TITLE
ipython/jupyter qtconsole copy issue in windows

### ISSUE THREAD

**Issue by ifmihai** [ipython/ipython#8799] opened 2015-09-08 14:31 UTC
I'm having exactly [the same issue as this guy](http://stackoverflow.com/questions/20858336/copy-code-from-ipython-without-leading-triple-dots/20870555)

I'm on win7, anaconda, python 2.7.9, 32bit, ipython 4 (or jupyter, i dont get it yet)

how am i supposed to copy some functions written in ipython, without those triple dots?
i'm not aware on any other method, and in OSX i remember it worked with simple ctrl+c

**Comment by minrk** [comment] 2015-09-10 14:08
closing as duplicate of jupyter/qtconsole#48

**Closed by minrk** 2015-09-10 14:08 UTC
