### ISSUE TITLE
Crash during completion (latest git version)

### ISSUE THREAD

**Issue by ThiefMaster** [ipython/ipython#9579] opened 2016-06-08 11:34 UTC
Basically I did `from itertools import chai` and then tab-completed to `chain` and pressed enter.

```
  File "./ipy5-test/bin/ipython", line 9, in <module>
    load_entry_point('ipython==5.0.0.dev0', 'console_scripts', 'ipython')()
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/IPython/terminal/ptshell.py", line 400, in mainloop
    self.interact()
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/IPython/terminal/ptshell.py", line 383, in interact
    code = self.prompt_for_code()
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/IPython/terminal/ptshell.py", line 326, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/prompt_toolkit/interface.py", line 387, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 154, in run
    t()
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 82, in read_from_stdin
    inputstream.feed(data)
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 376, in feed
    self._input_parser.send(c)
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 295, in _input_parser_generator
    self._call_handler(match, prefix)
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 328, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/prompt_toolkit/interface.py", line 916, in feed_key
    self._active_cli.input_processor.feed_key(key_press)
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 174, in feed_key
    self._process_coroutine.send(key_press)
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 146, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 190, in _call_handler
    handler.call(event)
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/prompt_toolkit/key_binding/registry.py", line 32, in call
    return self.handler(event)
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/IPython/terminal/ptshell.py", line 189, in _
    b.apply_completion(cs.current_completion)
  File "/tmp/ipy5-test/lib64/python3.5/site-packages/prompt_toolkit/buffer.py", line 762, in apply_completion
    assert isinstance(completion, Completion)
AssertionError
```

https://asciinema.org/a/70vwskydo2oxyt60nme5j78bb

**Comment by stromnov** [comment] 2016-06-08 12:50
Looks like duplicate of the #9578

**Comment by Carreau** [comment] 2016-06-08 18:32
Thanks ! I can reproduce by downgrading to prompt_toolkit 1.0.0 :-)

**Closed** 2016-06-09 08:43 UTC
