### ISSUE TITLE
Want find + replace in ipython notebook

### ISSUE THREAD

**Issue by abrahamneben** [ipython/ipython#8672] opened 2015-07-29 13:05 UTC
This would be an extremely helpful feature, and it is unclear to be why ipython notebook doesn't have it yet. Please include it in next release.

**Comment by anguta** [comment] 2015-07-29 13:14
Find and replace is an essential feature and present in nearly every text editor. Please add it.

**Comment by minrk** [comment] 2015-07-29 16:46
Closing as duplicate of #1579

**Closed by minrk** 2015-07-29 16:46 UTC
