### ISSUE TITLE
Image problems in output

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#8055] opened 2015-03-14 20:51 UTC
I am seeing problems with images in the output area. Here are screen shots of two failure modes I am seeing...

This one happens when you collapse the output area with an image in it:

![image-display-collapse-bug](https://cloud.githubusercontent.com/assets/27600/6653465/43c3a448-ca6a-11e4-8ee2-058dcc33b779.png)

This one is where the image sticks out of the output area (thought we had fixed this):

![screen shot 2015-03-14 at 4 49 32 pm](https://cloud.githubusercontent.com/assets/27600/6653468/5f75649c-ca6a-11e4-975b-92bb7b434fa9.png)

**Comment by takluyver** [comment] 2015-03-14 20:59
Plots sticking out of the notebook 'page': we kind of fixed it, but not consistently across browsers, and not in a way that worked for markdown images as well. Then some people complained that they wanted plots to stick out of the notebook so they could make them larger deliberately. So we reverted it pending a better fix. See #7701.

**Comment by Carreau** [comment] 2015-03-14 21:44
can't reproduce the first one.

**Comment by minrk** [comment] 2015-03-18 23:13
I was finally able to reproduce the first one (also reported as JuliaLang/IJulia.jl#285), and it should be fixed by #8082. Since the second part of this is a duplicate, #8082 should close this Issue.

**Closed** 2015-03-19 17:59 UTC
Labels: bug, needs-info, notebook
