### ISSUE TITLE
ipython kernel keeps dying (installed ipython uisng bash on windows )

### ISSUE THREAD

**Issue by sudha2990** [ipython/ipython#9973] opened 2016-10-01 14:01 UTC
Am facing an issue that ipython terminal keeps dying continuously.
I tried running as shell script but still am getting same error

**Comment by SrivastavaKshitij** [comment] 2016-10-01 20:38
why dont you use an ubuntu virtual machine on windows platform. I mean if  you are developing something , linux is always a better choice

**Comment by takluyver** [comment] 2016-10-02 08:21
What's the error message? Bash on Windows is fairly new and a bit of a weird environment, so there may well be things that cause problems.

**Comment by sudha2990** [comment] 2016-10-03 16:53
Am trying to run ipython notebook from bash and am able to run.But am not able to execute code in python shell of ipython notebook.Am getting popup saying "ipython terminal keeps dying continuously"

**Comment by takluyver** [comment] 2016-10-04 10:26
Are there any error messages in the terminal where you launched the notebook? That often shows more info if the kernel is dying.

**Comment by sudha2990** [comment] 2016-10-04 12:03
On launching notebook am getting below warning

[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future

Also am getting below during ipython terminal launch
KernelRestarter: restarting kernel (2/5)
Invalid argument (tcp_address.cpp:161)

**Comment by takluyver** [comment] 2016-10-04 12:14
```
Invalid argument (tcp_address.cpp:161)
```

That looks like the problem. @minrk may know more about what's wrong, as that's in ZMQ. It may just be that WSL is not supported yet.

**Comment by sudha2990** [comment] 2016-10-04 12:23
Issue got resolved by following below command from https://github.com/jupyter/notebook/issues/1331

sudo add-apt-repository ppa:aseering/wsl
sudo apt-get update
sudo apt-get install --upgarde libzmq3 libzmq3-dev
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
pip install --no-use-wheel -v pyzmq
pip install jupyter

**Comment by minrk** [comment] 2016-10-04 12:43
I'm pretty sure that libzmq doesn't work in WSL when you build it yourself, but apt-installed libzmq seems to work.

**Comment by takluyver** [comment] 2016-10-04 12:49
OK, glad you found a workaround. Closing this since it's not a bug in IPython.

**Closed by takluyver** 2016-10-04 12:49 UTC

**Comment by JimSEOW** [comment] 2016-10-18 16:40
# ipython kernel keeps dying
![applicationframehost_2016-10-18_18-37-29](https://cloud.githubusercontent.com/assets/8244633/19487223/1e876f6a-9562-11e6-9f46-a81910645f00.png)
![applicationframehost_2016-10-18_18-37-44](https://cloud.githubusercontent.com/assets/8244633/19487225/2172aeba-9562-11e6-8dc7-922a98e46624.png)



>Kernel started: c81deaed-dfc4-4733-8ba7-173dc82d646c
Invalid argument (src/tcp_address.cpp:190)
>KernelRestarter: restarting kernel (1/5)
Invalid argument (src/tcp_address.cpp:190)
>KernelRestarter: restarting kernel (2/5)
Invalid argument (src/tcp_address.cpp:190)
>KernelRestarter: restarting kernel (3/5)
Invalid argument (src/tcp_address.cpp:190)
>Timeout waiting for kernel_info reply from c81deaed-dfc4-4733-8ba7-173dc82d646c
>KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel c81deaed-dfc4-4733-8ba7-173dc82d646c restarted
Invalid argument (src/tcp_address.cpp:190)
![applicationframehost_2016-10-18_18-37-29]
>KernelRestarter: restart failed
>Kernel c81deaed-dfc4-4733-8ba7-173dc82d646c died, removing from map.
ERROR:root:kernel c81deaed-dfc4-4733-8ba7-173dc82d646c restarted failed!
>Kernel deleted before session
>410 DELETE /api/sessions/21a9b67b-1a2c-45cd-8df7-41885ae62f2e (127.0.0.1) 4.49ms referer=http://localhost:8888/notebooks/a.ipynb
