### ISSUE TITLE
multiple line edit broke in 7.0.1

### ISSUE THREAD

**Issue by laoshaw** [ipython/ipython#11346] opened 2018-09-30 01:56 UTC
under ipython 7.0.1:

```
x=[1,2,3]
for i in x:
    print(i)
```
After entering 'print(i)' it will end, leaves no chance for me to type a following line at the same indent level, i.e. the below is impossible:

```
x=[1,2,3]
for i in x:
    print(i)
    print("impossible to enter this line")
```

older version of ipython does not have this issue.

**Comment by cosven** [comment] 2018-09-30 07:36
I have met the same problem.

workaround: press `Ctrl-O` to get a newline. 
`Ctrl-O`: insert a newline and leave point before it.

**Comment by ssanderson** [comment] 2018-10-01 16:17
I think this is another dupe of https://github.com/ipython/ipython/issues/11334.

**Comment by eirnym** [comment] 2018-10-08 14:13
indeed, it's a duplicate

**Comment by tonyfast** [comment] 2018-10-08 22:32
@meeseeksdev[bot] close

**Closed by tonyfast** 2018-10-08 22:32 UTC
