### ISSUE TITLE
ipython 7.0.1 with rlipython crashes after pressing enter for first time

### ISSUE THREAD

**Issue by shusso** [ipython/ipython#11447] opened 2018-10-25 10:06 UTC
I'm running ipython with rlipython in emacs with elpy with command `ipython -i --TerminalIPythonApp.interactive_shell_class=rlipython.TerminalInteractiveShell`. Not sure is this supposed to work in `ipython7` but..

To repro the issue
```
[foo] > pipenv shell
(foo) [foo] > which ipython
/usr/local/bin/ipython
(foo) [foo] > pip3 install ipython
(foo) [foo] > ipython --version
7.0.1
(foo) [foo] > pip3 install rlipython gnureadline
# it seems ipython will start but pressing ENTER at the first line of repl will crash it
(foo) [foo] > ipython -i --TerminalIPythonApp.interactive_shell_class=rlipython.TerminalInteractiveShell
will try to use gnureadline
Python 3.6.6 (default, Jul 24 2018, 10:55:09)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]:
Traceback (most recent call last):
  File "/Users/shusso/foo/.venv/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/shusso/foo/.venv/lib/python3.6/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/shusso/foo/.venv/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/shusso/foo/.venv/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/Users/shusso/foo/.venv/lib/python3.6/site-packages/rlipython/shell.py", line 454, in mainloop
    self.interact(display_banner=display_banner)
  File "/Users/shusso/foo/.venv/lib/python3.6/site-packages/rlipython/shell.py", line 571, in interact
    self.input_splitter.push(line)
AttributeError: 'TransformerManager' object has no attribute 'push'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

Seems like a regression from `ipython6.5.0` as
```
(foo) [foo] > pip3 uninstall ipython
(foo) [foo] > pip3 install ipython==6.5.0
(foo) [foo] > ipython --version
6.5.0
(foo) [foo] > ipython -i --TerminalIPythonApp.interactive_shell_class=rlipython.TerminalInteractiveShell
will try to use gnureadline
Python 3.6.6 (default, Jul 24 2018, 10:55:09)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]:

In [1]:

In [1]:
```

sys_info
```
(foo) [foo] > python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': 'dd83a2163',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/shusso/foo/.venv/lib/python3.6/site-packages/IPython',
 'ipython_version': '6.5.0',
 'os_name': 'posix',
 'platform': 'Darwin-18.0.0-x86_64-i386-64bit',
 'sys_executable': '/Users/shusso/foo/.venv/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.6.6 (default, Jul 24 2018, 10:55:09) \n'
                '[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]'}
```

Let me know if you need any help!

**Comment by Carreau** [comment] 2018-10-25 15:51
duplicate of ipython/rlipython#21  rlipython need to be patched.

**Closed by Carreau** 2018-10-25 15:51 UTC
