### ISSUE TITLE
Equations in notebook jump from centered to L aligned upon rendering

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipython#7827] opened 2015-02-21 05:34 UTC
This is a quick jump where the equation initially appears centered and slightly smaller and then a fraction of a second later, jumps over to the left and gets bigger.

**Comment by rsmith31415** [comment] 2015-02-21 20:02
Regarding the part in which the equation appears smaller and then gets bigger, I think that is a MathJax issue because I noticed the same behavior in [Cross Validated](http://stats.stackexchange.com/) when answering a question. The same happens in other MathJax-enabled sites of the StackExchange family. However, I don't see the equation jumping to the left.

**Comment by ellisonbg** [comment] 2015-02-23 07:24
Hmm, sounds like we need to look into it more...

On Sat, Feb 21, 2015 at 12:02 PM, rsmith31415 <notifications@github.com>
wrote:

> Regarding the part in which the equation appears smaller and then gets
> bigger, I think that is a MathJax issue because I noticed the same behavior
> in Cross Validated <http://stats.stackexchange.com/> when answering a
> question. The same happens in other MathJax-enabled sites of the
> StackExchange family. However, I don't see the equation jumping to the left.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7827#issuecomment-75389864>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakobgager** [comment] 2015-02-23 12:04
This is the new _fast preview_  mode of mathjax 2.5, see [News](http://www.mathjax.org/mathjax-v2-5-now-available/). There you also find the required modification to disable this feature.

**Comment by ellisonbg** [comment] 2015-02-23 16:05
Great, thanks for finding that. Thoughts on this? Should we disable it?

On Mon, Feb 23, 2015 at 4:05 AM, Jakob Gager <notifications@github.com>
wrote:

> This is the new *fast preview* mode of mathjax 2.5, see News
> <http://www.mathjax.org/mathjax-v2-5-now-available/>. There you also find
> the required modification to disable this feature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7827#issuecomment-75530440>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by rsmith31415** [comment] 2015-02-23 17:10
As I understood this feature, the main purpose is to provide a rough but readable rendering very fast: 

>This extension provides a two-pass rendering mode. A first, fast-but-rough rendering is genereated as a preview, using the The CommonHTML output processor, then a second pass using the configured output jax runs to update the preview output.

If you read the [documentation](http://docs.mathjax.org/en/latest/options/CommonHTML.html#configure-commonhtml) for the CommonHTML output processor, there is a parameter that controls the scale of the first rendering. Initially, it is based on the surrounding text and that might be the reason why we are seeing a smaller preview. Maybe if the scale value is increased, we can get a better preview that looks more like a feature than a bug.

**Comment by ellisonbg** [comment] 2015-02-23 17:17
OK thanks, we will look into that.

On Mon, Feb 23, 2015 at 9:10 AM, rsmith31415 <notifications@github.com>
wrote:

> As I understood this feature, the main purpose is to provide a rough but
> readable rendering very fast:
>
> This extension provides a two-pass rendering mode. A first, fast-but-rough
> rendering is genereated as a preview, using the The CommonHTML output
> processor, then a second pass using the configured output jax runs to
> update the preview output.
>
> If you read the documentation
> <http://docs.mathjax.org/en/latest/options/CommonHTML.html#configure-commonhtml>
> for the CommonHTML output processor, there is a parameter that controls the
> scale of the first rendering. Initially, it is based on the surrounding
> text and that might be the reason why we are seeing a smaller preview.
> Maybe if the scale value is increased, we can get a better preview that
> looks more like a feature than a bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/issues/7827#issuecomment-75585692>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment] 2015-02-23 18:43
I'm looking into this right now.

**Comment by jdfreder** [comment] 2015-02-23 18:55
Has someone fixed this?  The problem isn't really a problem for me:

![centeredtex](https://cloud.githubusercontent.com/assets/3292874/6334507/edd5ef20-bb49-11e4-82d9-642a89bba68b.gif)

Here's what the preview mode looks like:
![screen shot 2015-02-23 at 10 52 51 am](https://cloud.githubusercontent.com/assets/3292874/6334538/1e68dddc-bb4a-11e4-8d9b-c455045475c5.png)

And the final mode:
![screen shot 2015-02-23 at 10 53 09 am](https://cloud.githubusercontent.com/assets/3292874/6334544/258a86ce-bb4a-11e4-9f36-3283c44b05d8.png)

And here's left aligned tex:
![lefttex](https://cloud.githubusercontent.com/assets/3292874/6334579/5b353f80-bb4a-11e4-95c5-930c867bb14b.gif)


I was there in person last week when @ellisonbg noticed this bug.  This is definitely not is bad as what we saw then.  @ellisonbg were those markdown cells or Latex objects?

**Comment by rsmith31415** [comment] 2015-02-23 20:08
@jdfreder You need to use more complex LaTeX expressions to notice a big change. Actually, the fast preview mode is focused on improving rendering of complex expressions.

**Comment by jdfreder** [comment] 2015-02-23 20:31
@rsmith31415 still the main problem (title of this issue) @ellisonbg mentioned, the center align to left align jump problem, clearly doesn't exist for me.

**Comment by rsmith31415** [comment] 2015-02-23 20:55
@jdfreder Correct. I haven't noticed jumps either.

**Comment by jakobgager** [comment] 2015-02-23 21:11
I see the jumps with sympy objects. Try something like

```python 
import sympy as sp
from sympy.abc import t, alpha, beta
from sympy import Function, exp, Eq
sp.init_printing()
y=Function('Y')
diffgl = y(t).diff(t) + alpha*y(t)*exp(-beta/t)
Eq(diffgl,0)
```

**Comment by rsmith31415** [comment] 2015-02-24 00:39
@jakobgager Now I see the jumps. It seems there are a couple of competing CSS rules: `div.output_area .MathJax_Display` and `.MathJax_Display` when rendering from sympy. The first rule contains `text-align: left !important;` and overrides the second rule (with `text-align: center;`) 

However, I don't know why there is a different styling depending on the source. I also noticed that the MathJax from Sympy is slightly different from the MathJax generated with `$$` or `\\[`

**Comment by billpage** [comment] 2016-08-11 19:23
Still a problem in SageMath --notebook=jupyter

Everything jumps to the left. Can't seem to customize this behavior with ~/.jupyter/custom/custom.css

**Comment by billpage** [comment] 2016-08-11 19:39
I found this annoying behavior in a newly install instance of SageMath 7.2. I would like it to remain centered as in  normal "display math" style.

In the file:

`/usr/lib/sagemath/local/lib/python2.7/site-packages/notebook/static/style/style.min.css
`

in line 9956:

```
div.output_area .MathJax_Display {
  text-align: left !important;
}
```

This overrides any attempt to customize this behavior using for example

`~/.jupyter/custom/custom.css`

Getting rid of "!important" resolves the problem.

**Comment by Carreau** [comment] 2017-07-23 00:12
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.

**Closed by Carreau** 2017-07-23 00:12 UTC
Labels: bug, notebook
