### ISSUE TITLE
Web front end becomes unresponsive

### ISSUE THREAD

**Issue by abeerag** [ipython/ipython#7693] opened 2015-02-05 19:23 UTC
From time to time, especially after I run a long task, or use multiprocessing, the IPython web front end becomes unresponsive. On running the cell, the number next to the cell changes to a *, but the kernel does not show up as busy on the top right. The cell is never executed.

**Comment by takluyver** [comment] 2015-02-05 20:07
Do you see anything in your browser's JS console when this happens?

**Comment by abeerag** [comment] 2015-02-05 20:22
Nope, there’s nothing there.

**Comment by kain88-de** [comment] 2015-05-07 09:53
I have a the same problem I think. after executing the cell with the call to `pool.map()` I can't execute other cells anymore and it is just shown as busy. When i restart the kernel I get an zmq error. I have created a gist with a minimal notebook to reproduce the error on my machine and also posted the zmq error I'm getting.

https://gist.github.com/kain88-de/501558bf18142fc863c2

**Comment by kain88-de** [comment] 2015-05-07 10:09
I found the solution for me on stackoverflow

the problem is that I create the function after I have created the processing pool. If I create all functions used in the map call before I create the pool everything works just fine.

https://stackoverflow.com/questions/2782961/yet-another-confusion-with-multiprocessing-error-module-object-has-no-attribu

**Comment by Carreau** [comment] 2017-07-20 17:09
Closing as this issue is not in IPython itself and if still problematic and relevant should be opened on the right repository.  This will allow to keep the number of opened issue on the IPython repo under control. 

Feel free to keep commenting or reopen if necessary.

Thanks.

**Closed by Carreau** 2017-07-20 17:09 UTC
Labels: notebook
