### ISSUE TITLE
Image overflow in IPython Notebook 3 (beta)

### ISSUE THREAD

**Issue by JeremyMMulcahey** [ipython/ipython#7701] opened 2015-02-06 01:02 UTC
When my notebook converted from v3 to v4, running the code below, yielded the image below:

![code](https://cloud.githubusercontent.com/assets/8571234/6072598/5be1770a-ad58-11e4-890a-c4a5be5c6da1.PNG)
![overflow](https://cloud.githubusercontent.com/assets/8571234/6072599/5ec866d6-ad58-11e4-80c1-ebff00466a19.PNG)

Additionally, the plot below, with dimensions (18,6) did not overflow in the previous version of the IPython Notebook:

![plot](https://cloud.githubusercontent.com/assets/8571234/6072637/c7037ede-ad58-11e4-8bf1-ce42f44b4c66.PNG)

**Comment by takluyver** [comment] 2015-02-06 01:45
The behaviour hasn't actually changed, but we made the background around the notebook 'page' grey, so it's much more obvious now when things extend beyond the page.

We're not sure what to do about this, because we do think the grey surround looks much nicer when things aren't extending outside the page.

**Comment by JeremyMMulcahey** [comment] 2015-02-06 07:22
The original issue came up in ellisonbg's office and he requested that I submit the screen shots. To investigate the possibility of a difference, he requested that I go back to ipython 2 and rerun the code (then submit those screen shots). These are the resulting screen shots:

![overflow2](https://cloud.githubusercontent.com/assets/8571234/6075731/7316f7ee-ad8d-11e4-9356-fe4c46ed36c0.PNG)

![plot2](https://cloud.githubusercontent.com/assets/8571234/6075733/7722ec4e-ad8d-11e4-9e5e-f822ee532c5d.PNG)

Side note: Agreed, the grey surround does look much nicer.

**Comment by JeremyMMulcahey** [comment] 2015-02-06 07:24
It appears the image dimensions, and the plot dimensions, are contained within the notebook.

**Comment by takluyver** [comment] 2015-02-07 00:04
I've marked this as 3.0 to ensure one of us takes a look at it.

**Comment by rsmith31415** [comment] 2015-02-07 22:17
I also noticed this issue while I was testing IRKernel in Ipython 3. I give a self-contained example in which I made a silly mistake when switching from R to Python:

    import pandas as pd
    import ggplot as gg
    %matplotlib inline

    gdURL = "http://www.stat.ubc.ca/~jenny/notOcto/STAT545A/examples/gapminder/data/gapminderDataFiveYear.txt"
    df = pd.read_table(gdURL)
    gg.ggplot(df, gg.aes(x = df.gdpPercap, y = df.lifeExp)) + gg.geom_point() # this is an error.

![screenshot from 2015-02-07 16 05 50](https://cloud.githubusercontent.com/assets/599274/6094142/409ad5d6-aee3-11e4-9833-313744134e45.png)

This is the result in Ipython 2:

![screenshot from 2015-02-07 16 07 11](https://cloud.githubusercontent.com/assets/599274/6094146/68a1e326-aee3-11e4-96b1-6e203068b3f3.png)

The reason this happens is because the following `div` doesn't have a `width: 100%`:

    <div class="ui-wrapper" style="overflow: hidden; position: relative; width: 1146px; height: 964px; top: auto; left: auto; margin: 0px;"></div>

**Comment by jdfreder** [comment] 2015-02-09 18:31
> The reason this happens is because the following div doesn't have a width: 100%:

It's not that simple.  We can't set the width to 100% because that's used by the resize handle.

**Comment by takluyver** [comment] 2015-02-09 18:43
@jdfreder's PR #7718 would put oversize outputs in a scrolling box instead of letting them spill out of the page. Is that preferable?

> We can't set the width to 100% because that's used by the resize handle.

Could we set max-width?

**Comment by jdfreder** [comment] 2015-02-09 19:27
> Could we set max-width?

That worked.  

Yet another alternative solution, which I attempted but didn't have any luck achieving, is what @JeremyMMulcahey suggests, to make the page resize to the output contents.

**Closed** 2015-02-12 17:42 UTC
Labels: notebook

**Comment by takluyver** [comment] 2015-02-19 18:45
Looking back at this, I was under the impression that in IPython 2.x images were resized to fit in the page, based on the screenshots people showed. Going and fiddling with IPython 2.x myself, I can easily get images to spill out of the page area. Possibly we've just made the page area a bit narrower for IPython 3?

![screenshot showing plots exceeeding page width](https://cloud.githubusercontent.com/assets/327925/6273462/68e45856-b824-11e4-95e8-8659e23f59eb.png)

**Comment by rsmith31415** [comment] 2015-02-19 23:46
@takluyver 

I'm not getting that behavior in Ipython 2.4.1 (Ubuntu 14.10, Chrome 40.0.2)

![screenshot from 2015-02-19 17 43 55](https://cloud.githubusercontent.com/assets/599274/6278744/01d2ea3e-b85f-11e4-99fe-bbd6ad507a51.png)

**Comment by takluyver** [comment] 2015-02-19 23:56
It's a Firefox/Webkit difference - If I open the same notebook in Chromium, the images are resized to fit the notebook page.

**Comment by takluyver** [comment] 2015-02-20 00:11
Gah, browsers and CSS flexbox. It's all inconsistent.

Firefox with or without the #7721 fix (it appears to make no difference):

![screenshot from 2015-02-19 16 02 58](https://cloud.githubusercontent.com/assets/327925/6279045/65cdfa3c-b851-11e4-94b6-f95133328fa1.png)

Chromium with #7721 applied:

![screenshot from 2015-02-19 16 03 23](https://cloud.githubusercontent.com/assets/327925/6279048/6fd00fe8-b851-11e4-9597-c64e1a1ec39b.png)

Chromium with #7721 reverted:

![screenshot from 2015-02-19 16 07 51](https://cloud.githubusercontent.com/assets/327925/6279054/8010ca5a-b851-11e4-866b-4a8547aa7d5d.png)

So if we revert #7721, the behaviour of wide images in outputs is consistent across browsers, but it's a regression for Chrome users who like image output resized to fit in the notebook.

I think resizing is probably the right thing to do for images in markdown cells, though.

**Comment by rsmith31415** [comment] 2015-02-20 00:41
Yes, I see the problem in Firefox. 

There are widths (e.g. 1262px) as inline properties being set on the fly, which is causing this issue.

By the way, why a "resize handler" is needed? Maybe that is not required and then would be permissible to use percentages to fix this issue.

**Comment by takluyver** [comment] 2015-02-20 00:54
> why a "resize handler" is needed?

I don't know the details for this one, but making complex applications behave as you expect in the browser, especially across different browsers, requires a pile of hacks. If we're doing things on resize events, I seriously doubt that we can get rid of that without breaking something else fairly badly.

@jdfreder @minrk or @Carreau may be able to fill in the details.

**Comment by rsmith31415** [comment] 2015-02-20 01:09
That's okay. Maybe @jdfreder was talking about media queries or something like that, because I didn't see a listener for the resize event in the Firefox console.
