### ISSUE TITLE
no tab completion in terminal when using debugger 

### ISSUE THREAD

**Issue by mhearne-usgs** [ipython/ipython#9759] opened 2016-07-13 20:39 UTC
@Carreau I chatted with Brian Granger, who said I should bring this to your attention.

OS: Mac OS 10.10.5
python -V: Python 3.5.2 : Anaconda custom (x86_64)
ipython --version : 5.0.0
source of ipython: conda-forge build

When I am in the ipython terminal and using the debugger, tab completion does not work (i.e., I just get a tab).  This happened in the version of IPython I had before installing this a few minutes ago, so I wonder if it's something wrong with the conda-forge build?

I'm at Scipy, so if someone wants a demo of the problem, I'm happy to do that.

**Comment by Carreau** [comment] 2016-07-13 21:06
Are you at the sprints ?

**Comment by mhearne-usgs** [comment] 2016-07-13 21:08
No, I won't be, but I'm here through Friday evening.

**Comment by Carreau** [comment] 2016-07-13 21:08
Ok, we can try to find some time.

**Comment by mhearne-usgs** [comment] 2016-07-14 14:50
@Carreau How about between the keynote and talks today?  I'm free.

**Comment by Carreau** [comment] 2016-07-14 16:11
Sorry overslept.. missed the keynote.

I'm up we can meet whenever.

**Comment by mhearne-usgs** [comment] 2016-07-14 19:03
@Carreau are you free at the next break  (3-3:30?)  Maybe outside the ballroom at one of the small tables?

**Comment by mhearne-usgs** [comment] 2016-07-14 19:25
@Carreau or after the lightning talks and before social stuff?  Same location.

**Comment by Carreau** [comment] 2016-07-17 15:36
Oh, I hate GitHub / Gmail  I never received your pings they got marked as read automatically. Sorry about that. 
Hope you enjoyed the conference .. i'll try to investigate.

**Comment by dekoza** [comment] 2016-07-20 07:47
I'm glad you had this little chat here but the problem is not resolved ;)

**Comment by takluyver** [comment] 2016-07-20 15:02
How are you entering the debugger?

**Comment by takluyver** [comment] 2016-07-20 15:05
If you're using ipdb, see gotcha/ipdb#105 . If you're importing something from `IPython.core.debugger`, see #9781. If it's something else, furnish details and we'll look into it.

**Comment by mhearne-usgs** [comment] 2016-07-20 15:40
In the terminal, I'm doing "run -d script.py".  I guess I'm not sure if that's ipdb or not, but it's how I always do my debugging.

**Closed** 2016-07-21 12:50 UTC
