### ISSUE TITLE
Notebook calls both __repr__ and _repr_html_

### ISSUE THREAD

**Issue by EntilZha** [ipython/ipython#9771] opened 2016-07-16 22:09 UTC
# Observed Behavior:
1. Define `_repr_html_` on class
2. In Jupyter/IPython notebook create an instance of the class
3. Showing the variable by it being the last line in a cell calls both `__repr__` and `_repr_html_`

# Expected Behavior:
Jupyter/IPython notebook should call only `_repr_html_` if it is defined.

Rationale:

1. The return of `repr` is never shown to the user so there is no need to call it if `_repr_html_` is defined already.
2. For object's whose `repr` function is expensive to call (eg large collections), `_repr_html_` can be implemented efficiently by only showing a subset of the collection. This is allowed since although `repr` in general should adhere to its output being runnable by `eval`, `_repr_html_` does not have to adhere to this since it produces HTML.

# Minimal Example

```python
class Custom:
    def __repr__(self):
        raise Exception("oops called repr")
    
    def _repr_html_(self):
        return "<h1>HTML repr</h1>"
```

In  jupyter cell:

```python
a = Custom()
a
```

This results in: https://gist.github.com/EntilZha/6b81fc9ced2540a5b7acdebc37c66346

Note, the HTML output is still printed despite the exception.

# System Information
* Mac OS X 10.11.5
* Safari 9
* IPython 5.0.0
* Jupyter 1.0.0
* Python 3 via brew

Thanks!

**Comment by takluyver** [comment] 2016-07-16 22:31
Sorry, this is by design. Although the notebook frontend prefers HTML, we store any output formats that are available, because if you convert the notebook document to other formats, a different output format may be used. We've discussed before whether we might filter e.g. image types for plots, but I don't think we'd ever skip the plain text repr.

The eval-able repr is a guideline rather than a rule, and there are common cases where large objects do not provide a full repr:

```
In [2]: numpy.zeros((1000, 1000))
Out[2]: 
array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])
```

**Comment by EntilZha** [comment] 2016-07-17 04:57
Makes sense. I am guessing providing an option flag to tell ipython not to call repr also gets messy so the best solution is to truncate `repr` in the first place.

**Comment by takluyver** [comment] 2016-07-17 08:27
If you want to provide a different repr in IPython, I think defining the `_repr_pretty_()`, which is intended for customising pretty-printing, should override `__repr__`. I haven't checked that `__repr__` is not called at all in that case, though.

**Comment by EntilZha** [comment] 2016-07-17 10:50
Still calls `__repr__` even if `_repr_pretty_` is defined. I think in any case it would be better for me to make `__repr__` truncate since the main use case for it is inspecting data and I have various functions for persisting said data anyway. Thanks for the pointer to `_repr_pretty_`, might implement that as well possibly

**Comment by Carreau** [comment] 2016-07-19 17:47
Closing as this is expected behavior.

**Closed by Carreau** 2016-07-19 17:47 UTC
