### ISSUE TITLE
Jupyter Notebook unknow files in the list

### ISSUE THREAD

**Issue by CarlosSchettini** [ipython/ipython#11511] opened 2018-11-27 16:30 UTC
Hi,

I'm a newcomer to python, ipython, etc... (migrating from matlab!), operating with Windows 10. I installed Jupyter Notebook using pip.

When I launch it by the command line, I take the token and copy to the browser. That's ok... 

1) First issue:

But, when it opens, there is a huge list of files in the dashboard... (3000+, all sort of extensions, created from months to years ago).

I following the youtube tutorial https://www.youtube.com/watch?v=HW29067qVWk&t=124s   
and there, when the notebook is open, there is no files. 

What are this files? and why are they there?

2) Second issue:

Every command or changes seems to be too slow... 

3) Third issue:

When I try to create a new notebook, I get " Permission denied: Untitled.ipynb (I'm the administrator!)

![jn_strange_files](https://user-images.githubusercontent.com/30525791/49095939-a4bdae80-f250-11e8-81a7-7eff2566c00b.png)

**Comment by Carreau** [comment] 2018-11-30 18:44
Hi, 

> I'm a newcomer to python, ipython, etc... (migrating from matlab!)

Congratulation ! it takes some time to get used to, but it's worth it. 

I think all the issues are link to the same root cause. It's on windows so i'm unsure exactly. 
But likely when you start the notebook server with `jupyter notebook` , it is supposed to start in current working directory. It is lilkey that  it starts somewhere else. Like in `C:\`, hence why you see all these files. 

Even if you are administrator, the notebook server is not and then can't write a file. .

You could try to run `jupyter notebook --notebook-dir=<path to where you want to start>`

Let us know if that works. 

Side note this question may be better in https://github.com/jupyter/notebook

**Comment by CarlosSchettini** [comment] 2018-12-01 14:50
Thank you Carreau,

You're right! It was 'root' cause and related to another doubt I had (where and I?). I was expecting I would chose the working path once I was in the notebook.

I didn't get form the youtube tutorial I should start from an empty folder, despite of it was there! 

I started from Windows 'start menu'  opening a command window with  "cmd", and Windows put me in the "C:\WINDOWS\system32" folder... starting Jupyter Notebook from there, so the files in the dashboard was the content of this folder (so obvious now!). Windows doesn't allow me to create nothing there, even I'm the administrator, so the permission issue. Changing to other folders (non-system ones), all runs nicely. 

Thanks!

**Comment by Carreau** [comment] 2018-12-01 20:08
> I was expecting I would chose the working path once I was in the notebook.

That's because of security. Once you start a notebook server you can only go "down".
And by default it start in current working directory. 

Don't forget to set a password (even if executing on localhost). 

CLosing as solved.

**Closed by Carreau** 2018-12-01 20:08 UTC
