### ISSUE TITLE
Crash when pasting continued line

### ISSUE THREAD

**Issue by bnaul** [ipython/ipython#9737] opened 2016-07-12 05:14 UTC
Copying and pasting, e.g.,
```
('a',
'b')
```
into `ipython==5.0.0` gives a crash and the following traceback:
```
Traceback (most recent call last):
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 581, in get_processed_line
    return cache[i]
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brettnaul/miniconda3/envs/cesium/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 348, in start
    self.shell.mainloop()
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 402, in mainloop
    self.interact()
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 385, in interact
    code = self.prompt_for_code()
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 321, in prompt_for_code
    pre_run=self.pre_prompt, reset_current_buffer=True)
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 389, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 154, in run
    t()
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 326, in redraw
    self._redraw()
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 346, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/renderer.py", line 429, in render
    extended_height=size.rows,
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 142, in write_to_screen
    sizes = self._divide_heigths(cli, write_position)
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 177, in _divide_heigths
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 177, in <listcomp>
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 175, in get_dimension_for_child
    return c.preferred_height(cli, write_position.width, write_position.extended_height)
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 395, in preferred_height
    return self.content.preferred_height(cli, width, max_available_height)
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 128, in preferred_height
    dimensions = [c.preferred_height(cli, width, max_available_height) for c in self.children]
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 128, in <listcomp>
    dimensions = [c.preferred_height(cli, width, max_available_height) for c in self.children]
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/containers.py", line 1000, in preferred_height
    cli, width - total_margin_width, max_available_height, wrap_lines),
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 502, in preferred_height
    content = self.create_content(cli, width, None)
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 641, in create_content
    document.cursor_position_col),
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 623, in translate_rowcol
    return Point(y=row, x=get_processed_line(row).source_to_display(col))
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 583, in get_processed_line
    processed_line = transform(i, get_line(i))
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/controls.py", line 559, in transform
    cli, document, lineno, source_to_display, tokens)
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/processors.py", line 554, in apply_transformation
    cli, document, lineno, source_to_display, tokens)
  File "/Users/brettnaul/miniconda3/envs/cesium/lib/python3.5/site-packages/prompt_toolkit/layout/processors.py", line 255, in apply_transformation
    token, text = tokens[col]
IndexError: list index out of range
```

Mentioned this to @Carreau yesterday but couldn't come up with a reproducible example...here you go ;).

Edit: `prompt-toolkit==1.0.3`

**Comment by Carreau** [comment] 2016-07-12 05:19
```
>>> import prompt_toolkit
>>> prompt_toolkit.__version__
'1.0.3'
```

If not, what if you upgrade ?

**Comment by Carreau** [comment] 2016-07-12 05:19
Sorry, dump read too fast.

**Comment by bnaul** [comment] 2016-07-12 05:20
Plot thickens: same virtual environment, two different terminal tabs, one has this behavior and the other doesn't...I'll leave it open for you to keep the magic alive.

**Comment by Carreau** [comment] 2016-07-12 05:22
:-( cc @jonathanslenders Can't reproduce here... Which Pygments ?

**Comment by bnaul** [comment] 2016-07-12 05:23
`Pygments==2.1.3`

**Comment by Carreau** [comment] 2016-07-12 05:24
Where are you ? I'm in the lobby.

**Comment by Carreau** [comment] 2016-07-12 05:25
Same version of pygments.. can't get it to crash ...

**Comment by bnaul** [comment] 2016-07-12 05:28
I'm in some faraway AirBnB with @stefanv...can show you tomorrow though.

**Comment by Carreau** [comment] 2016-07-12 05:29
Ok.

**Comment by takluyver** [comment] 2016-07-12 15:27
I have also tried and failed to reproduce this.

**Comment by Carreau** [comment] 2016-07-12 15:58
this seem to be when you achieve to insert a `\r` instead of a `\n`.

**Comment by jonathanslenders** [comment] 2016-07-12 16:10
This is probably indeed caused by a ``\r\n`` in some string instead of a single ``\n``.
I guess we can work around this by patching the key binding for BracketedPaste and replacing the input string over there, but I will try to reproduce it and see for a real solution.

**Comment by Carreau** [comment] 2016-07-12 16:37
That might be @bnaul terminal that's borked, as we could only reproduce in 1 terminal window, and it was not `\r\n` but just `\n`. I'll try to see if I can reproduce by internally setting the buffer to a wrong value.

**Comment by abadabanades** [comment] 2016-08-04 11:56
I got the same issue after upgrading to `5.0.0`. If I can help providing some information, just let me know

**Comment by takluyver** [comment] 2016-08-04 11:58
Thanks @abadabanades . What platform are you on, and do you have a way to reproduce the issue?

**Comment by azmras** [comment] 2016-08-04 12:34
Same problem, reproducible every time..

Python 3.5.2 (default, Jul 28 2016, 21:28:00) 
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

prompt_toolkit.__version__
Out[2]: '1.0.4'


brew info python3
python3: stable 3.5.2 (bottled), devel 3.6.0a3, HEAD

OSX El Capitan
10.11.6 (15G31)

**Comment by takluyver** [comment] 2016-08-04 12:36
What do you have to do to reproduce it?

**Comment by abadabanades** [comment] 2016-08-04 12:56
I am running an Ubuntu 14.04.
No way to reproduce the issue.
I've closed my terminal, reopened it and it works. I did it again, and it failed again. I'll keep investigating

**Comment by azmras** [comment] 2016-08-05 04:22
crashes on pasting this or anything like this
(1,2,
 3,4)

hangs on pasting this or any code fragment with starts with import
import pandas
import numpy

**Comment by takluyver** [comment] 2016-08-05 13:51
It may depend where you copy from - copying either of those from your comment in Firefox and pasting into IPython works fine for me (on Fedora).

**Comment by bryant1410** [comment] 2016-08-05 15:20
I've got the same issue without importing anything, being the first thing I do after executing ipython. I'm on Ubuntu 16.04 using Guake terminal emulator (also happens with GNOME Terminal). Python version 3.5.1.

**Comment by takluyver** [comment] 2016-08-05 15:26
And where did you copy the text from?

**Comment by bryant1410** [comment] 2016-08-05 15:27
From Sublime. Also I use pyenv with virtualenv.

**Comment by bryant1410** [comment] 2016-08-05 15:27
Also happens when copying from Chrome.

**Comment by takluyver** [comment] 2016-08-05 15:33
Weird, I still can't reproduce it when copying from Chrome to Gnome-terminal.

**Comment by takluyver** [comment] 2016-08-05 15:47
I've also tested setting the clipboard manually from tkinter to test the theory that it's due to `\r` or `\r\n`, but I don't get a crash on either. Here's the code to set the clipboard from Tkinter in IPython:

```python
from tkinter import Tk
r = Tk()
r.withdraw()
r.clipboard_clear()
r.clipboard_append('[1,2,\r\n3,4]')
%gui tk
```

**Comment by Carreau** [comment] 2016-08-05 16:34
When we tried with @bnaul it was not due to where we would copy from.  It would often only affect a single terminal window and not all the program. Like pure python would get a `\r\n`, but IPython/PTK would get a `\r` only. 

If @bryant1410 you can reproduce it on all his terminal windows, we can try to track it down. But for most of us it's a but that appear randomly, and than disappear without being able to reproduce it...

**Comment by bryant1410** [comment] 2016-08-05 16:42
@Carreau you meant a `\n` only instead of `\r` only, don't you?

What can I do to provide help?

**Comment by Carreau** [comment] 2016-08-05 16:45
> you meant a \n only instead of \r only, don't you?

No, I meant `\r`, we figured out that somewhere inside of IPython, the "pasted string" would be in the case of @bnaul , in IPython: `('a',\r'b')`,  while a pure python shell was seeing `('a',\r\n'b')`

I'll try to dig out were to put breakpoints and figure out where the `\n` is stripped.

**Comment by jonathanslenders** [comment] 2016-08-05 20:41
Hi all,

I found this bug.
In Pygments, Lexer.get_tokens replaces both \r\n and \r by \n. So, the text output after  lexing can have a length which is different from the input. See: https://bitbucket.org/birkenfeld/pygments-main/src/e79a7126551c39d5f8c1b83a79c14e86992155a4/pygments/lexer.py?at=default&fileviewer=file-view-default#lexer.py-179

Assinging the following string in ``prompt_toolkit.buffer`` makes it crash. (Because, internally, prompt_toolkit doesn't consider \r to be a newline (it renders it as ^M), while Pygments does and returns more lines after lexing):

```python
self.text = '(1, 2\r3,4)'
```

So, now I'm using ``pygments.Lexer.get_tokens_unprocessed``, which doesn't do this replacement. After this patch, this would display as ``(1, 2^M3,4)``.
https://github.com/jonathanslenders/python-prompt-toolkit/commit/3c2f68101d357848f9de3e9c95d7e6e35e9e4c51

Now the second problem is that inside a bracketed paste, I think we want to replace \r by \n. I have a pull request for this.
https://github.com/jonathanslenders/python-prompt-toolkit/compare/master...replace-r-in-bracketed-paste

Can you please test whether the latest master commit does solve the issue? (That should display ^M instead of a newline if everything works well.) And also test whether it is completely solved after merging this pull request?

Thanks!

**Comment by bnaul** [comment] 2016-08-08 22:27
Couldn't test this until I ended up with another wonky iTerm2 tab, but I have one now: upgrading `prompt-toolkit` to the current master branch appears to fix the issue :+1:.

**Comment by takluyver** [comment] 2016-08-09 11:37
Thanks @bnaul . I'll close this as it doesn't seem like any change is needed in IPython, but discussion of the issue and the fix can continue here.

**Closed by takluyver** 2016-08-09 11:37 UTC

**Comment by anentropic** [comment] 2016-08-15 15:41
well, since v1.0.4 and v1.0.5 of python-prompt-toolkit are broken maybe the IPython setup.py should require >= 1.0.6 as soon as that version is available

(I just upgraded to IPython 5.1.0 today, from 2.x, and the colour-coding, IDE-like features blew my mind... for about 30 seconds until I tried to use it... installing HEAD version of prompt_tookit from github fixed it for me)

**Comment by takluyver** [comment] 2016-08-15 15:52
It's bizarre, because for many of us it's working fine, and so far we haven't been able to find a common factor in the cases where it's broken. However, we may indeed bump our requirement once there's a new version of prompt_toolkit, since several people have reported this issue.

**Comment by jonathanslenders** [comment] 2016-08-15 17:11
FYI: prompt_toolkit 1.0.6 has been released.
